import { ProfessionOption } from './types';

export const professions: ProfessionOption[] = [
  // MANUAL_TRADES
  {
    id: 'ELECTRICIAN',
    sectorId: 'MANUAL_TRADES',
    nameAr: 'كهربائي',
    nameEn: 'Electrician',
    aliases: ['فني كهرباء', 'عامل كهرباء'],
    profileTypes: ['حرفي', 'فني'],
    specializationIds: ['residential', 'commercial', 'industrial', 'high_voltage', 'low_voltage', 'solar', 'networks'],
    serviceIds: ['installation', 'maintenance', 'repair', 'diagnosis', 'emergency', 'mobile_service'],
  },
  {
    id: 'PLUMBER',
    sectorId: 'MANUAL_TRADES',
    nameAr: 'سباك',
    nameEn: 'Plumber',
    aliases: ['فني سباكة', 'عامل سباكة'],
    profileTypes: ['حرفي', 'فني'],
    specializationIds: ['residential', 'commercial', 'industrial', 'plumbing'],
    serviceIds: ['installation', 'maintenance', 'repair', 'emergency', 'mobile_service'],
  },
  {
    id: 'HVAC_TECHNICIAN',
    sectorId: 'MANUAL_TRADES',
    nameAr: 'فني تكييف',
    nameEn: 'HVAC Technician',
    aliases: ['مكيف', 'فني مكيفات'],
    profileTypes: ['حرفي', 'فني'],
    specializationIds: ['residential', 'commercial', 'industrial', 'hvac'],
    serviceIds: ['installation', 'maintenance', 'repair', 'cleaning', 'emergency'],
  },
  {
    id: 'PAINTER',
    sectorId: 'MANUAL_TRADES',
    nameAr: 'دهان',
    nameEn: 'Painter',
    aliases: ['عامل دهان', 'فني دهان'],
    profileTypes: ['حرفي'],
    specializationIds: ['painting_interior', 'painting_exterior', 'industrial_painting', 'decorative'],
    serviceIds: ['painting', 'polishing', 'design', 'execution'],
  },
  {
    id: 'CARPENTER',
    sectorId: 'MANUAL_TRADES',
    nameAr: 'نجار',
    nameEn: 'Carpenter',
    aliases: ['فني نجارة', 'عامل خشب'],
    profileTypes: ['حرفي'],
    specializationIds: ['wood', 'tables', 'chairs', 'doors', 'windows', 'cabinets', 'upholstery'],
    serviceIds: ['fabrication', 'installation', 'repair', 'design', 'execution'],
  },
  {
    id: 'ALUMINUM_TECHNICIAN',
    sectorId: 'MANUAL_TRADES',
    nameAr: 'فني ألمنيوم',
    nameEn: 'Aluminum Technician',
    aliases: ['ألمنيوم', 'ألمنيوم وشبابيك'],
    profileTypes: ['حرفي', 'فني'],
    specializationIds: ['aluminum', 'doors', 'windows', 'cabinets'],
    serviceIds: ['fabrication', 'installation', 'repair', 'maintenance'],
  },
  {
    id: 'TILER',
    sectorId: 'MANUAL_TRADES',
    nameAr: 'مبلط',
    nameEn: 'Tiler / Marble Worker',
    aliases: ['رخامي', 'سيراميك'],
    profileTypes: ['حرفي'],
    specializationIds: ['tile_work', 'residential', 'commercial'],
    serviceIds: ['installation', 'repair', 'polishing', 'execution'],
  },
  {
    id: 'WELDER',
    sectorId: 'MANUAL_TRADES',
    nameAr: 'لحام',
    nameEn: 'Welder',
    aliases: ['فني لحام', 'حديد'],
    profileTypes: ['حرفي', 'فني'],
    specializationIds: ['tig', 'mig', 'arc', 'structural', 'decorative', 'metalwork'],
    serviceIds: ['welding', 'fabrication', 'repair', 'cutting', 'bending'],
  },
  {
    id: 'METAL_FABRICATOR',
    sectorId: 'MANUAL_TRADES',
    nameAr: 'حداد / مصفّح معدني',
    nameEn: 'Metal Fabricator / Blacksmith',
    aliases: ['حداد', 'مصنع حديد'],
    profileTypes: ['حرفي'],
    specializationIds: ['metalwork', 'steel', 'blacksmithing', 'decorative', 'structural'],
    serviceIds: ['fabrication', 'installation', 'repair', 'welding', 'cutting'],
  },
  {
    id: 'PLASTERER',
    sectorId: 'MANUAL_TRADES',
    nameAr: 'جبس وبناء',
    nameEn: 'Plasterer / Builder',
    aliases: ['جباص', 'عامل بناء'],
    profileTypes: ['حرفي'],
    specializationIds: ['gypsum', 'structural', 'decorative'],
    serviceIds: ['installation', 'repair', 'execution'],
  },
  {
    id: 'GLASS_TECHNICIAN',
    sectorId: 'MANUAL_TRADES',
    nameAr: 'فني زجاج',
    nameEn: 'Glass Technician',
    aliases: ['زجاج', 'مرايا'],
    profileTypes: ['حرفي'],
    specializationIds: ['glass', 'doors', 'windows', 'decorative'],
    serviceIds: ['installation', 'repair', 'cutting', 'design'],
  },
  {
    id: 'AUTO_ELECTRICIAN',
    sectorId: 'MANUAL_TRADES',
    nameAr: 'كهربائي سيارات',
    nameEn: 'Auto Electrician',
    aliases: ['فني كهرباء سيارات'],
    profileTypes: ['فني'],
    specializationIds: ['auto_electrical'],
    serviceIds: ['diagnosis', 'repair', 'installation', 'maintenance'],
  },
  {
    id: 'APPLIANCE_TECHNICIAN',
    sectorId: 'MANUAL_TRADES',
    nameAr: 'فني أجهزة منزلية',
    nameEn: 'Appliance Technician',
    aliases: ['فني ثلاجات', 'فني غسالات'],
    profileTypes: ['فني'],
    specializationIds: ['home_appliances'],
    serviceIds: ['repair', 'maintenance', 'installation', 'diagnosis'],
  },
  {
    id: 'MOBILE_REPAIR_TECH',
    sectorId: 'MANUAL_TRADES',
    nameAr: 'فني صيانة جوالات',
    nameEn: 'Mobile Phone Repair Technician',
    aliases: ['صيانة هواتف', 'تبديل شاشات'],
    profileTypes: ['فني'],
    specializationIds: ['mobile_phones'],
    serviceIds: ['repair', 'diagnosis', 'maintenance'],
  },
  {
    id: 'COMPUTER_TECHNICIAN',
    sectorId: 'MANUAL_TRADES',
    nameAr: 'فني حاسوب',
    nameEn: 'Computer Technician',
    aliases: ['صيانة كمبيوتر', 'فني لابتوب'],
    profileTypes: ['فني'],
    specializationIds: ['computers'],
    serviceIds: ['repair', 'maintenance', 'diagnosis', 'installation'],
  },

  // TECHNICAL_SERVICES
  {
    id: 'IT_SUPPORT_SPECIALIST',
    sectorId: 'TECHNICAL_SERVICES',
    nameAr: 'أخصائي دعم تقني',
    nameEn: 'IT Support Specialist',
    aliases: ['IT', 'دعم IT'],
    profileTypes: ['فني', 'متخصص'],
    specializationIds: ['it_support', 'network_setup', 'computers'],
    serviceIds: ['maintenance', 'consulting', 'training', 'installation'],
  },
  {
    id: 'WEB_DEVELOPER',
    sectorId: 'TECHNICAL_SERVICES',
    nameAr: 'مطوّر مواقع',
    nameEn: 'Web Developer',
    aliases: ['مبرمج مواقع', 'ويب'],
    profileTypes: ['متخصص', 'مهني'],
    specializationIds: ['web_development', 'programming'],
    serviceIds: ['development', 'design', 'consulting', 'maintenance'],
  },
  {
    id: 'APP_DEVELOPER',
    sectorId: 'TECHNICAL_SERVICES',
    nameAr: 'مطوّر تطبيقات',
    nameEn: 'Mobile App Developer',
    aliases: ['مبرمج تطبيقات', 'موبايل ديف'],
    profileTypes: ['متخصص', 'مهني'],
    specializationIds: ['app_development', 'programming'],
    serviceIds: ['development', 'consulting', 'maintenance'],
  },
  {
    id: 'DEVOPS_ENGINEER',
    sectorId: 'TECHNICAL_SERVICES',
    nameAr: 'مهندس DevOps',
    nameEn: 'DevOps Engineer',
    aliases: ['ديف أوبس'],
    profileTypes: ['متخصص'],
    specializationIds: ['devops'],
    serviceIds: ['consulting', 'development', 'maintenance', 'training'],
  },
  {
    id: 'DATA_ANALYST',
    sectorId: 'TECHNICAL_SERVICES',
    nameAr: 'محلل بيانات',
    nameEn: 'Data Analyst',
    aliases: ['تحليل بيانات', 'داتا'],
    profileTypes: ['متخصص'],
    specializationIds: ['data_analysis'],
    serviceIds: ['consulting', 'training', 'development'],
  },
  {
    id: 'CYBERSECURITY_SPECIALIST',
    sectorId: 'TECHNICAL_SERVICES',
    nameAr: 'أخصائي أمن سيبراني',
    nameEn: 'Cybersecurity Specialist',
    aliases: ['سكيوريتي', 'حماية'],
    profileTypes: ['متخصص'],
    specializationIds: ['cybersecurity'],
    serviceIds: ['consulting', 'development', 'training'],
  },
  {
    id: 'NETWORK_ENGINEER',
    sectorId: 'TECHNICAL_SERVICES',
    nameAr: 'مهندس شبكات',
    nameEn: 'Network Engineer',
    aliases: ['شبكات', 'تمديد شبكات'],
    profileTypes: ['فني', 'متخصص'],
    specializationIds: ['networks', 'network_setup'],
    serviceIds: ['installation', 'consulting', 'maintenance', 'diagnosis'],
  },
  {
    id: 'ELECTRONICS_TECHNICIAN',
    sectorId: 'TECHNICAL_SERVICES',
    nameAr: 'فني إلكترونيات',
    nameEn: 'Electronics Technician',
    aliases: ['إلكترونيات', 'دوائر'],
    profileTypes: ['فني'],
    specializationIds: ['computers', 'mobile_phones', 'home_appliances'],
    serviceIds: ['repair', 'maintenance', 'diagnosis', 'installation'],
  },
  {
    id: 'CNC_OPERATOR',
    sectorId: 'TECHNICAL_SERVICES',
    nameAr: 'مشغّل CNC',
    nameEn: 'CNC Operator',
    aliases: ['سي إن سي', 'ماكينة'],
    profileTypes: ['فني'],
    specializationIds: ['cnc', 'metalwork', 'wood'],
    serviceIds: ['fabrication', 'cutting', 'consulting'],
  },

  // CREATIVE_MEDIA
  {
    id: 'GRAPHIC_DESIGNER',
    sectorId: 'CREATIVE_MEDIA',
    nameAr: 'مصمم جرافيك',
    nameEn: 'Graphic Designer',
    aliases: ['جرافيك', 'تصميم فني'],
    profileTypes: ['مبدع'],
    specializationIds: ['branding', 'ui_ux', 'packaging', 'social_media', 'illustration'],
    serviceIds: ['design', 'consulting', 'execution'],
  },
  {
    id: 'MOTION_DESIGNER',
    sectorId: 'CREATIVE_MEDIA',
    nameAr: 'مصمم موشن جرافيك',
    nameEn: 'Motion Designer',
    aliases: ['موشن', 'أنيميشن'],
    profileTypes: ['مبدع'],
    specializationIds: ['motion', 'ads', 'social_media'],
    serviceIds: ['design', 'video', 'execution'],
  },
  {
    id: 'VIDEOGRAPHER',
    sectorId: 'CREATIVE_MEDIA',
    nameAr: 'مصوّر فيديو',
    nameEn: 'Videographer',
    aliases: ['تصوير فيديو', 'فيديوجرافر'],
    profileTypes: ['مبدع', 'موهوب'],
    specializationIds: ['video_production', 'short_form', 'documentary', 'ads', 'events', 'weddings'],
    serviceIds: ['video', 'photography', 'montage', 'execution'],
  },
  {
    id: 'VIDEO_EDITOR',
    sectorId: 'CREATIVE_MEDIA',
    nameAr: 'محرّر فيديو',
    nameEn: 'Video Editor',
    aliases: ['مونتير', 'مونتاج'],
    profileTypes: ['مبدع'],
    specializationIds: ['video_editing', 'short_form', 'documentary', 'ads'],
    serviceIds: ['montage', 'design', 'sound'],
  },
  {
    id: 'PHOTOGRAPHER',
    sectorId: 'CREATIVE_MEDIA',
    nameAr: 'مصوّر',
    nameEn: 'Photographer',
    aliases: ['فوتوغرافر'],
    profileTypes: ['موهوب', 'مبدع'],
    specializationIds: ['portrait', 'product', 'aerial', 'food', 'events', 'weddings'],
    serviceIds: ['photography', 'video', 'montage'],
  },
  {
    id: 'VOICEOVER_ARTIST',
    sectorId: 'CREATIVE_MEDIA',
    nameAr: 'مؤدي تعليق صوتي',
    nameEn: 'Voiceover Artist',
    aliases: ['فويس أوفر', 'معلق صوتي'],
    profileTypes: ['موهوب'],
    specializationIds: ['voice_ads', 'voice_drama', 'voice_elearning', 'voice_recitation'],
    serviceIds: ['sound', 'recording', 'consulting'],
  },
  {
    id: 'CONTENT_CREATOR',
    sectorId: 'CREATIVE_MEDIA',
    nameAr: 'صانع محتوى',
    nameEn: 'Content Creator',
    aliases: ['كرييتور', 'مؤثر'],
    profileTypes: ['مبدع'],
    specializationIds: ['social_media', 'short_form', 'copywriting', 'video_production'],
    serviceIds: ['content_creation', 'photography', 'video', 'consulting'],
  },
  {
    id: 'COPYWRITER',
    sectorId: 'CREATIVE_MEDIA',
    nameAr: 'كاتب إعلاني',
    nameEn: 'Copywriter',
    aliases: ['كوبي رايتر', 'نصوص إعلانية'],
    profileTypes: ['مبدع', 'مهني'],
    specializationIds: ['copywriting', 'social_media', 'ads'],
    serviceIds: ['content_creation', 'consulting', 'translation'],
  },
  {
    id: 'TRANSLATOR',
    sectorId: 'CREATIVE_MEDIA',
    nameAr: 'مترجم',
    nameEn: 'Translator',
    aliases: ['ترجمة', 'ترجمة معتمدة'],
    profileTypes: ['مهني', 'متخصص'],
    specializationIds: ['translation', 'language'],
    serviceIds: ['translation', 'consulting', 'content_creation'],
  },
  {
    id: 'INTERIOR_DESIGNER',
    sectorId: 'CREATIVE_MEDIA',
    nameAr: 'مصمم داخلي',
    nameEn: 'Interior Designer',
    aliases: ['ديكور داخلي', 'مهندس ديكور'],
    profileTypes: ['مبدع', 'متخصص'],
    specializationIds: ['interior_design', 'landscape', 'decorative'],
    serviceIds: ['design', 'consulting', 'supervision', 'execution'],
  },
  {
    id: 'EVENT_DESIGNER',
    sectorId: 'CREATIVE_MEDIA',
    nameAr: 'منسّق / مصمم فعاليات',
    nameEn: 'Event Designer / Coordinator',
    aliases: ['تنسيق فعاليات', 'منظم مناسبات'],
    profileTypes: ['مبدع', 'مقدم خدمة'],
    specializationIds: ['events', 'weddings', 'exhibitions'],
    serviceIds: ['design', 'coordination', 'execution', 'consulting'],
  },
  {
    id: 'PRESENTER',
    sectorId: 'CREATIVE_MEDIA',
    nameAr: 'مقدم',
    nameEn: 'Presenter / Host',
    aliases: ['مذيع', 'مقدم برامج'],
    profileTypes: ['موهوب'],
    specializationIds: ['events', 'ads', 'social_media'],
    serviceIds: ['hosting', 'content_creation'],
  },

  // PROFESSIONAL_SERVICES
  {
    id: 'ACCOUNTANT',
    sectorId: 'PROFESSIONAL_SERVICES',
    nameAr: 'محاسب',
    nameEn: 'Accountant',
    aliases: ['محاسب قانوني', 'محاسب زكاة'],
    profileTypes: ['مهني', 'متخصص'],
    specializationIds: ['accounting_bookkeeping', 'accounting_taxes', 'accounting_payroll', 'accounting_audit'],
    serviceIds: ['accounting', 'auditing', 'advisory', 'consulting'],
  },
  {
    id: 'AUDITOR',
    sectorId: 'PROFESSIONAL_SERVICES',
    nameAr: 'مدقّق مالي',
    nameEn: 'Financial Auditor',
    aliases: ['مراجع قانوني', 'تدقيق'],
    profileTypes: ['مهني', 'متخصص'],
    specializationIds: ['accounting_audit'],
    serviceIds: ['auditing', 'consulting', 'advisory'],
  },
  {
    id: 'TAX_CONSULTANT',
    sectorId: 'PROFESSIONAL_SERVICES',
    nameAr: 'مستشار ضرائب وزكاة',
    nameEn: 'Tax & Zakat Consultant',
    aliases: ['ضرائب', 'زكاة'],
    profileTypes: ['خبير / مستشار'],
    specializationIds: ['accounting_taxes'],
    serviceIds: ['advisory', 'consulting', 'auditing'],
  },
  {
    id: 'LEGAL_ADVISOR',
    sectorId: 'PROFESSIONAL_SERVICES',
    nameAr: 'مستشار قانوني',
    nameEn: 'Legal Advisor',
    aliases: ['محامي', 'قانون'],
    profileTypes: ['خبير / مستشار', 'مهني'],
    specializationIds: ['legal'],
    serviceIds: ['advisory', 'consulting'],
  },
  {
    id: 'REAL_ESTATE_BROKER',
    sectorId: 'PROFESSIONAL_SERVICES',
    nameAr: 'وسيط عقاري',
    nameEn: 'Real Estate Broker',
    aliases: ['عقارات', 'مسوّق عقاري'],
    profileTypes: ['مهني', 'مقدم خدمة'],
    specializationIds: ['realestate'],
    serviceIds: ['brokerage', 'consulting', 'coordination'],
  },
  {
    id: 'INVESTMENT_ADVISOR',
    sectorId: 'PROFESSIONAL_SERVICES',
    nameAr: 'مستشار استثماري',
    nameEn: 'Investment Advisor',
    aliases: ['استثمار', 'محلل استثماري'],
    profileTypes: ['خبير / مستشار'],
    specializationIds: ['investment'],
    serviceIds: ['advisory', 'consulting'],
  },
  {
    id: 'MARKETING_SPECIALIST',
    sectorId: 'PROFESSIONAL_SERVICES',
    nameAr: 'أخصائي تسويق',
    nameEn: 'Marketing Specialist',
    aliases: ['مسوّق', 'تسويق رقمي'],
    profileTypes: ['مهني', 'متخصص'],
    specializationIds: ['marketing', 'social_media', 'ads'],
    serviceIds: ['consulting', 'content_creation'],
  },
  {
    id: 'HR_SPECIALIST',
    sectorId: 'PROFESSIONAL_SERVICES',
    nameAr: 'أخصائي موارد بشرية',
    nameEn: 'HR Specialist',
    aliases: ['HR', 'موارد بشرية'],
    profileTypes: ['مهني', 'متخصص'],
    specializationIds: ['hr'],
    serviceIds: ['consulting', 'training'],
  },
  {
    id: 'OPERATIONS_CONSULTANT',
    sectorId: 'PROFESSIONAL_SERVICES',
    nameAr: 'مستشار عمليات',
    nameEn: 'Operations Consultant',
    aliases: ['عمليات', 'تحسين'],
    profileTypes: ['خبير / مستشار'],
    specializationIds: ['operations', 'quality', 'logistics'],
    serviceIds: ['consulting', 'advisory', 'training'],
  },

  // CARE_GIVING
  {
    id: 'NURSE',
    sectorId: 'CARE_GIVING',
    nameAr: 'ممرض / ممرضة',
    nameEn: 'Nurse',
    aliases: ['تمريض', 'ممرض', 'ممرضة'],
    profileTypes: ['متخصص', 'مقدم خدمة'],
    specializationIds: ['nursing_care', 'patient_care', 'home_care'],
    serviceIds: ['nursing', 'caregiving', 'consulting'],
    requiresLicense: true,
  },
  {
    id: 'CAREGIVER',
    sectorId: 'CARE_GIVING',
    nameAr: 'مقدّم رعاية',
    nameEn: 'Caregiver',
    aliases: ['مساعد شخصي', 'رعاية'],
    profileTypes: ['مقدم خدمة'],
    specializationIds: ['elderly_care', 'child_care', 'special_needs', 'patient_care', 'home_care'],
    serviceIds: ['caregiving', 'nursing', 'guiding'],
  },
  {
    id: 'PHYSIOTHERAPIST',
    sectorId: 'CARE_GIVING',
    nameAr: 'أخصائي علاج طبيعي',
    nameEn: 'Physiotherapist',
    aliases: ['علاج طبيعي', 'فيزيو'],
    profileTypes: ['متخصص'],
    specializationIds: ['patient_care', 'home_care', 'sports_fitness'],
    serviceIds: ['consulting', 'training', 'caregiving'],
    requiresLicense: true,
  },
  {
    id: 'MIDWIFE',
    sectorId: 'CARE_GIVING',
    nameAr: 'قابلة',
    nameEn: 'Midwife',
    aliases: ['داية', 'قبالة'],
    profileTypes: ['متخصص', 'مقدم خدمة'],
    specializationIds: ['patient_care', 'child_care'],
    serviceIds: ['caregiving', 'consulting'],
  },

  // TOURISM_HOSPITALITY
  {
    id: 'TOUR_GUIDE',
    sectorId: 'TOURISM_HOSPITALITY',
    nameAr: 'مرشد سياحي',
    nameEn: 'Tour Guide',
    aliases: ['مرشد', 'guide'],
    profileTypes: ['مقدم خدمة', 'مهني'],
    specializationIds: ['tourism_local', 'tourism_religious', 'tourism_medical', 'tourism_adventure'],
    serviceIds: ['guiding', 'coordination', 'consulting'],
  },
  {
    id: 'TRAVEL_CONSULTANT',
    sectorId: 'TOURISM_HOSPITALITY',
    nameAr: 'مستشار سفر',
    nameEn: 'Travel Consultant',
    aliases: ['وكيل سفر', 'تنظيم رحلات'],
    profileTypes: ['مهني', 'مقدم خدمة'],
    specializationIds: ['tourism_local', 'tourism_religious', 'tourism_medical'],
    serviceIds: ['consulting', 'coordination'],
  },
  {
    id: 'HOTEL_STAFF',
    sectorId: 'TOURISM_HOSPITALITY',
    nameAr: 'موظف ضيافة',
    nameEn: 'Hospitality Staff',
    aliases: ['فندق', 'استقبال'],
    profileTypes: ['مقدم خدمة', 'مهني'],
    specializationIds: ['events', 'tourism_local'],
    serviceIds: ['hosting', 'coordination', 'consulting'],
  },
  {
    id: 'EVENT_USHER',
    sectorId: 'TOURISM_HOSPITALITY',
    nameAr: 'منسّق / مضيف فعاليات',
    nameEn: 'Event Usher / Host',
    aliases: ['مضيف', 'منظم فعاليات'],
    profileTypes: ['مقدم خدمة'],
    specializationIds: ['events', 'weddings', 'exhibitions'],
    serviceIds: ['hosting', 'coordination'],
  },

  // BEAUTY_WELLNESS
  {
    id: 'BARBER',
    sectorId: 'BEAUTY_WELLNESS',
    nameAr: 'حلاق',
    nameEn: 'Barber',
    aliases: ['حلاق رجالي', 'كوافير'],
    profileTypes: ['حرفي', 'مقدم خدمة'],
    specializationIds: ['men_cuts', 'shaving', 'skincare'],
    serviceIds: ['haircut', 'shaving', 'cleaning'],
  },
  {
    id: 'HAIRDRESSER',
    sectorId: 'BEAUTY_WELLNESS',
    nameAr: 'كوافيرة / مصفف شعر',
    nameEn: 'Hairdresser',
    aliases: ['تسريحات', 'صالون نسائي'],
    profileTypes: ['حرفي', 'مقدم خدمة'],
    specializationIds: ['women_hair', 'makeup', 'skincare', 'henna'],
    serviceIds: ['haircut', 'styling', 'cleaning'],
  },
  {
    id: 'MAKEUP_ARTIST',
    sectorId: 'BEAUTY_WELLNESS',
    nameAr: 'خبيرة / خبير تجميل',
    nameEn: 'Makeup Artist',
    aliases: ['مكياج', 'ميك أب'],
    profileTypes: ['مبدع', 'مقدم خدمة'],
    specializationIds: ['makeup', 'weddings', 'events'],
    serviceIds: ['makeup', 'consulting'],
  },
  {
    id: 'SKINCARE_SPECIALIST',
    sectorId: 'BEAUTY_WELLNESS',
    nameAr: 'أخصائي عناية بالبشرة',
    nameEn: 'Skincare Specialist',
    aliases: ['بشرة', 'فacial'],
    profileTypes: ['مقدم خدمة', 'متخصص'],
    specializationIds: ['skincare'],
    serviceIds: ['cleaning', 'consulting'],
  },
  {
    id: 'HENNA_ARTIST',
    sectorId: 'BEAUTY_WELLNESS',
    nameAr: 'نقّاشة / نقّاش حناء',
    nameEn: 'Henna Artist',
    aliases: ['حناء', 'نقش حناء'],
    profileTypes: ['حرفي', 'مبدع'],
    specializationIds: ['henna'],
    serviceIds: ['embroidery', 'design'],
  },
  {
    id: 'MASSAGE_THERAPIST',
    sectorId: 'BEAUTY_WELLNESS',
    nameAr: 'أخصائي مساج واسترخاء',
    nameEn: 'Massage Therapist',
    aliases: ['مساج', 'استرخاء'],
    profileTypes: ['مقدم خدمة', 'متخصص'],
    specializationIds: ['skincare', 'home_care'],
    serviceIds: ['caregiving', 'consulting'],
  },

  // TRADITIONAL_CRAFTS
  {
    id: 'EMBROIDERER',
    sectorId: 'TRADITIONAL_CRAFTS',
    nameAr: 'مطرّز / مطرّزة',
    nameEn: 'Embroiderer',
    aliases: ['تطريز', 'تطريز تقليدي'],
    profileTypes: ['حرفي', 'مبدع'],
    specializationIds: ['embroidery_hand', 'embroidery_machine', 'traditional_dress'],
    serviceIds: ['embroidery', 'sewing', 'design'],
  },
  {
    id: 'TAILOR',
    sectorId: 'TRADITIONAL_CRAFTS',
    nameAr: 'خيّاط',
    nameEn: 'Tailor',
    aliases: ['خياطة', 'تفصيل'],
    profileTypes: ['حرفي'],
    specializationIds: ['tailoring', 'alterations', 'menswear', 'womenswear', 'childrenswear', 'traditional_dress'],
    serviceIds: ['sewing', 'alterations', 'design'],
  },
  {
    id: 'LEATHER_CRAFTSMAN',
    sectorId: 'TRADITIONAL_CRAFTS',
    nameAr: 'حلّاق جلود / مصنوعات جلدية',
    nameEn: 'Leather Craftsman',
    aliases: ['جلد', 'شنط', 'أحذية'],
    profileTypes: ['حرفي', 'مبدع'],
    specializationIds: ['leather_goods', 'traditional_dress'],
    serviceIds: ['fabrication', 'repair', 'design'],
  },
  {
    id: 'PERFUMER',
    sectorId: 'TRADITIONAL_CRAFTS',
    nameAr: 'عطّار',
    nameEn: 'Perfumer',
    aliases: ['عطور', 'بخور', 'عطارة'],
    profileTypes: ['حرفي', 'مبدع'],
    specializationIds: ['perfume', 'incense', 'cosmetics'],
    serviceIds: ['fabrication', 'consulting', 'design'],
  },
  {
    id: 'SOAP_CRAFTSMAN',
    sectorId: 'TRADITIONAL_CRAFTS',
    nameAr: 'صانع صابون طبيعي',
    nameEn: 'Natural Soap Maker',
    aliases: ['صابون', 'طبيعي'],
    profileTypes: ['حرفي'],
    specializationIds: ['natural_soap', 'cosmetics'],
    serviceIds: ['fabrication', 'consulting'],
  },
  {
    id: 'CALLIGRAPHER',
    sectorId: 'TRADITIONAL_CRAFTS',
    nameAr: 'خطاط',
    nameEn: 'Calligrapher',
    aliases: ['خط عربي', 'خطاط فني'],
    profileTypes: ['مبدع', 'موهوب'],
    specializationIds: ['branding', 'decorative'],
    serviceIds: ['design', 'consulting'],
  },
  {
    id: 'POTTER',
    sectorId: 'TRADITIONAL_CRAFTS',
    nameAr: 'خزّاف',
    nameEn: 'Potter',
    aliases: ['فخار', 'خزف'],
    profileTypes: ['حرفي', 'مبدع'],
    specializationIds: ['decorative'],
    serviceIds: ['fabrication', 'design', 'training'],
  },
  {
    id: 'WEAVING_CRAFTSMAN',
    sectorId: 'TRADITIONAL_CRAFTS',
    nameAr: 'حائك / نسّاج',
    nameEn: 'Weaver',
    aliases: ['نسيج', 'سدو', 'سعف'],
    profileTypes: ['حرفي'],
    specializationIds: ['traditional_dress', 'decorative'],
    serviceIds: ['fabrication', 'design', 'training'],
  },

  // FOOD_BEVERAGE
  {
    id: 'CHEF',
    sectorId: 'FOOD_BEVERAGE',
    nameAr: 'طباخ',
    nameEn: 'Chef / Cook',
    aliases: ['شيف', 'طباخ منزلي', 'طباخ فعاليات'],
    profileTypes: ['حرفي', 'مقدم خدمة'],
    specializationIds: ['catering', 'pastry', 'sweets', 'coffee', 'grill', 'seafood', 'healthy_food'],
    serviceIds: ['cooking', 'consulting', 'training'],
  },
  {
    id: 'BAKER',
    sectorId: 'FOOD_BEVERAGE',
    nameAr: 'خباز / معجّن',
    nameEn: 'Baker',
    aliases: ['معجنات', 'خبز'],
    profileTypes: ['حرفي'],
    specializationIds: ['pastry', 'sweets'],
    serviceIds: ['fabrication', 'cooking', 'consulting'],
  },
  {
    id: 'PASTRY_CHEF',
    sectorId: 'FOOD_BEVERAGE',
    nameAr: 'صانع حلويات',
    nameEn: 'Pastry Chef',
    aliases: ['حلويات', 'كيك', 'حلويات شرقية'],
    profileTypes: ['حرفي', 'مبدع'],
    specializationIds: ['sweets', 'pastry'],
    serviceIds: ['fabrication', 'design', 'consulting'],
  },
  {
    id: 'BARISTA',
    sectorId: 'FOOD_BEVERAGE',
    nameAr: 'باريستا',
    nameEn: 'Barista',
    aliases: ['قهوة', 'تحضير قهوة'],
    profileTypes: ['مقدم خدمة', 'حرفي'],
    specializationIds: ['coffee'],
    serviceIds: ['preparation', 'training', 'consulting'],
  },
  {
    id: 'BUTCHER',
    sectorId: 'FOOD_BEVERAGE',
    nameAr: 'جزار',
    nameEn: 'Butcher',
    aliases: ['جزارة', 'لحوم'],
    profileTypes: ['حرفي'],
    specializationIds: ['butchery'],
    serviceIds: ['butchery', 'preparation'],
  },
  {
    id: 'CATERER',
    sectorId: 'FOOD_BEVERAGE',
    nameAr: 'مقدّم تموين',
    nameEn: 'Caterer',
    aliases: ['تموين', 'ولائم'],
    profileTypes: ['مقدم خدمة'],
    specializationIds: ['catering', 'events', 'weddings'],
    serviceIds: ['cooking', 'coordination', 'execution'],
  },

  // AGRICULTURE_ANIMALS
  {
    id: 'LIVESTOCK_BREEDER',
    sectorId: 'AGRICULTURE_ANIMALS',
    nameAr: 'مربّي مواشٍ',
    nameEn: 'Livestock Breeder',
    aliases: ['مواشي', 'إبل', 'أغنام'],
    profileTypes: ['مهني', 'حرفي'],
    specializationIds: ['livestock'],
    serviceIds: ['breeding', 'feeding', 'consulting'],
  },
  {
    id: 'POULTRY_FARMER',
    sectorId: 'AGRICULTURE_ANIMALS',
    nameAr: 'مربّي دواجن',
    nameEn: 'Poultry Farmer',
    aliases: ['دواجن', 'دجاج'],
    profileTypes: ['مهني', 'حرفي'],
    specializationIds: ['poultry'],
    serviceIds: ['breeding', 'feeding', 'consulting'],
  },
  {
    id: 'FALCONER',
    sectorId: 'AGRICULTURE_ANIMALS',
    nameAr: 'صقّار',
    nameEn: 'Falconer',
    aliases: ['صقور', 'مقناص'],
    profileTypes: ['حرفي', 'موهوب'],
    specializationIds: ['falconry'],
    serviceIds: ['training_animals', 'breeding', 'consulting'],
  },
  {
    id: 'HORSE_TRAINER',
    sectorId: 'AGRICULTURE_ANIMALS',
    nameAr: 'مدرّب خيول',
    nameEn: 'Horse Trainer',
    aliases: ['خيول', 'فروسية'],
    profileTypes: ['متخصص', 'موهوب'],
    specializationIds: ['horses', 'sports_equestrian'],
    serviceIds: ['training_animals', 'consulting'],
  },
  {
    id: 'FISHERMAN',
    sectorId: 'AGRICULTURE_ANIMALS',
    nameAr: 'صيّاد',
    nameEn: 'Fisherman',
    aliases: ['صيد', 'أسماك'],
    profileTypes: ['حرفي', 'مهني'],
    specializationIds: ['fishing', 'seafood'],
    serviceIds: ['fishing', 'preparation'],
  },
  {
    id: 'FARMER',
    sectorId: 'AGRICULTURE_ANIMALS',
    nameAr: 'مزارع',
    nameEn: 'Farmer',
    aliases: ['زراعة', 'مزارع'],
    profileTypes: ['مهني', 'حرفي'],
    specializationIds: ['farming', 'dates', 'honey', 'plants'],
    serviceIds: ['farming', 'breeding', 'consulting'],
  },
  {
    id: 'BEEKEEPER',
    sectorId: 'AGRICULTURE_ANIMALS',
    nameAr: 'نحّال',
    nameEn: 'Beekeeper',
    aliases: ['عسل', 'نحل'],
    profileTypes: ['مهني', 'حرفي'],
    specializationIds: ['honey'],
    serviceIds: ['breeding', 'feeding', 'fabrication'],
  },
  {
    id: 'DATE_FARMER',
    sectorId: 'AGRICULTURE_ANIMALS',
    nameAr: 'مزارع تمور',
    nameEn: 'Date Farmer',
    aliases: ['تمور', 'نخيل'],
    profileTypes: ['مهني', 'حرفي'],
    specializationIds: ['dates'],
    serviceIds: ['farming', 'harvesting', 'packaging'],
  },

  // PERFORMING_ARTS
  {
    id: 'QURAN_READER',
    sectorId: 'PERFORMING_ARTS',
    nameAr: 'قارئ قرآن',
    nameEn: 'Quran Reciter',
    aliases: ['مقرئ', 'تلاوة'],
    profileTypes: ['موهوب'],
    specializationIds: ['recitation_tajweed', 'recitation_maqamat'],
    serviceIds: ['recitation', 'teaching'],
  },
  {
    id: 'STORYTELLER',
    sectorId: 'PERFORMING_ARTS',
    nameAr: 'قاص / راوي',
    nameEn: 'Storyteller',
    aliases: ['سرد قصص', 'حكواتي'],
    profileTypes: ['موهوب', 'مبدع'],
    specializationIds: ['storytelling_children', 'storytelling_heritage'],
    serviceIds: ['storytelling', 'content_creation'],
  },
  {
    id: 'ACTOR',
    sectorId: 'PERFORMING_ARTS',
    nameAr: 'ممثل',
    nameEn: 'Actor',
    aliases: ['تمثيل', 'مسرح', 'دراما'],
    profileTypes: ['موهوب', 'مبدع'],
    specializationIds: ['drama_theater', 'drama_tv', 'comedy', 'stunts'],
    serviceIds: ['acting', 'hosting'],
  },
  {
    id: 'MUSICIAN',
    sectorId: 'PERFORMING_ARTS',
    nameAr: 'موسيقي',
    nameEn: 'Musician',
    aliases: ['عزف', 'مطرب', 'مؤلف موسيقي'],
    profileTypes: ['موهوب', 'مبدع'],
    specializationIds: ['events', 'weddings', 'drama_tv'],
    serviceIds: ['performance', 'recording', 'teaching'],
  },
  {
    id: 'DANCER',
    sectorId: 'PERFORMING_ARTS',
    nameAr: 'راقص / راقصة',
    nameEn: 'Dancer',
    aliases: ['رقص', 'استعراض'],
    profileTypes: ['موهوب'],
    specializationIds: ['events', 'weddings', 'stunts'],
    serviceIds: ['performance', 'training'],
  },
  {
    id: 'MAGICIAN',
    sectorId: 'PERFORMING_ARTS',
    nameAr: 'ساحر / مؤدي خفة',
    nameEn: 'Magician',
    aliases: ['خفة', 'سحر'],
    profileTypes: ['موهوب'],
    specializationIds: ['events'],
    serviceIds: ['performance', 'hosting'],
  },

  // SPORTS_FITNESS
  {
    id: 'FOOTBALL_COACH',
    sectorId: 'SPORTS_FITNESS',
    nameAr: 'مدرّب كرة قدم',
    nameEn: 'Football Coach',
    aliases: ['كرة قدم', 'مدرب'],
    profileTypes: ['متخصص', 'موهوب'],
    specializationIds: ['sports_football'],
    serviceIds: ['training', 'consulting'],
  },
  {
    id: 'BASKETBALL_COACH',
    sectorId: 'SPORTS_FITNESS',
    nameAr: 'مدرّب كرة سلة',
    nameEn: 'Basketball Coach',
    aliases: ['كرة سلة'],
    profileTypes: ['متخصص', 'موهوب'],
    specializationIds: ['sports_basketball'],
    serviceIds: ['training', 'consulting'],
  },
  {
    id: 'SWIMMING_COACH',
    sectorId: 'SPORTS_FITNESS',
    nameAr: 'مدرّب سباحة',
    nameEn: 'Swimming Coach',
    aliases: ['سباحة'],
    profileTypes: ['متخصص', 'موهوب'],
    specializationIds: ['sports_swimming'],
    serviceIds: ['training', 'consulting'],
  },
  {
    id: 'MARTIAL_ARTS_COACH',
    sectorId: 'SPORTS_FITNESS',
    nameAr: 'مدرّب فنون قتالية',
    nameEn: 'Martial Arts Coach',
    aliases: ['كاراتيه', 'جودو', 'مصارعة'],
    profileTypes: ['متخصص', 'موهوب'],
    specializationIds: ['sports_martial'],
    serviceIds: ['training', 'consulting'],
  },
  {
    id: 'EQUESTRIAN_COACH',
    sectorId: 'SPORTS_FITNESS',
    nameAr: 'مدرّب فروسية',
    nameEn: 'Equestrian Coach',
    aliases: ['فروسية', 'خيول'],
    profileTypes: ['متخصص', 'موهوب'],
    specializationIds: ['sports_equestrian', 'horses'],
    serviceIds: ['training', 'consulting'],
  },
  {
    id: 'GYMNASTICS_COACH',
    sectorId: 'SPORTS_FITNESS',
    nameAr: 'مدرّب جمباز',
    nameEn: 'Gymnastics Coach',
    aliases: ['جمباز'],
    profileTypes: ['متخصص', 'موهوب'],
    specializationIds: ['sports_gymnastics'],
    serviceIds: ['training', 'consulting'],
  },
  {
    id: 'PERSONAL_TRAINER',
    sectorId: 'SPORTS_FITNESS',
    nameAr: 'مدرّب لياقة شخصي',
    nameEn: 'Personal Trainer',
    aliases: ['لياقة', 'فتنس', 'تدريب شخصي'],
    profileTypes: ['متخصص', 'مقدم خدمة'],
    specializationIds: ['sports_fitness'],
    serviceIds: ['training', 'consulting'],
  },
  {
    id: 'SPORTS_NUTRITIONIST',
    sectorId: 'SPORTS_FITNESS',
    nameAr: 'أخصائي تغذية رياضية',
    nameEn: 'Sports Nutritionist',
    aliases: ['تغذية', 'دايت', 'نظام غذائي'],
    profileTypes: ['متخصص'],
    specializationIds: ['sports_fitness', 'healthy_food'],
    serviceIds: ['consulting'],
  },

  // EDUCATION_TRAINING
  {
    id: 'PRIVATE_TUTOR',
    sectorId: 'EDUCATION_TRAINING',
    nameAr: 'معلّم خصوصي',
    nameEn: 'Private Tutor',
    aliases: ['تدريس خصوصي', 'مدرس خاص'],
    profileTypes: ['مهني', 'متخصص'],
    specializationIds: ['tutoring', 'language', 'religious', 'stem'],
    serviceIds: ['teaching', 'mentoring'],
  },
  {
    id: 'LANGUAGE_INSTRUCTOR',
    sectorId: 'EDUCATION_TRAINING',
    nameAr: 'مدرّب لغات',
    nameEn: 'Language Instructor',
    aliases: ['إنجليزي', 'عربي', 'لغات'],
    profileTypes: ['مهني', 'متخصص'],
    specializationIds: ['language'],
    serviceIds: ['teaching', 'translation'],
  },
  {
    id: 'RELIGIOUS_TEACHER',
    sectorId: 'EDUCATION_TRAINING',
    nameAr: 'معلّم علوم شرعية',
    nameEn: 'Religious Studies Teacher',
    aliases: ['دين', 'قرآن', 'حديث'],
    profileTypes: ['مهني', 'متخصص'],
    specializationIds: ['religious', 'recitation_tajweed'],
    serviceIds: ['teaching', 'mentoring'],
  },
  {
    id: 'STEM_TUTOR',
    sectorId: 'EDUCATION_TRAINING',
    nameAr: 'معلّم علوم وتقنية',
    nameEn: 'STEM Tutor',
    aliases: ['رياضيات', 'فيزياء', 'برمجة'],
    profileTypes: ['مهني', 'متخصص'],
    specializationIds: ['stem', 'programming'],
    serviceIds: ['teaching', 'mentoring'],
  },
  {
    id: 'EARLY_CHILDHOOD_TEACHER',
    sectorId: 'EDUCATION_TRAINING',
    nameAr: 'معلّم طفولة مبكرة',
    nameEn: 'Early Childhood Teacher',
    aliases: ['روضة', 'أطفال'],
    profileTypes: ['مهني'],
    specializationIds: ['early_childhood'],
    serviceIds: ['teaching', 'caregiving'],
  },
  {
    id: 'CURRICULUM_DEVELOPER',
    sectorId: 'EDUCATION_TRAINING',
    nameAr: 'مطوّر مناهج',
    nameEn: 'Curriculum Developer',
    aliases: ['مناهج', 'تعليم'],
    profileTypes: ['متخصص', 'خبير / مستشار'],
    specializationIds: ['curriculum'],
    serviceIds: ['development', 'consulting', 'training'],
  },
  {
    id: 'CORPORATE_TRAINER',
    sectorId: 'EDUCATION_TRAINING',
    nameAr: 'مدرّب corporate',
    nameEn: 'Corporate Trainer',
    aliases: ['تدريب شركات', 'تطوير موظفين'],
    profileTypes: ['خبير / مستشار', 'مهني'],
    specializationIds: ['training_delivery', 'hr', 'operations'],
    serviceIds: ['training', 'consulting'],
  },
  {
    id: 'MENTOR',
    sectorId: 'EDUCATION_TRAINING',
    nameAr: 'موجّه / مرشد',
    nameEn: 'Mentor',
    aliases: ['مرشد', 'توجيه'],
    profileTypes: ['خبير / مستشار'],
    specializationIds: ['mentoring'],
    serviceIds: ['mentoring', 'consulting', 'advisory'],
  },

  // MANAGEMENT_CONSULTING
  {
    id: 'BUSINESS_CONSULTANT',
    sectorId: 'MANAGEMENT_CONSULTING',
    nameAr: 'مستشار أعمال',
    nameEn: 'Business Consultant',
    aliases: ['أعمال', 'تطوير أعمال'],
    profileTypes: ['خبير / مستشار'],
    specializationIds: ['strategy', 'operations'],
    serviceIds: ['consulting', 'advisory', 'training'],
  },
  {
    id: 'STRATEGY_CONSULTANT',
    sectorId: 'MANAGEMENT_CONSULTING',
    nameAr: 'مستشار استراتيجي',
    nameEn: 'Strategy Consultant',
    aliases: ['استراتيجية', 'خطط'],
    profileTypes: ['خبير / مستشار'],
    specializationIds: ['strategy'],
    serviceIds: ['consulting', 'advisory'],
  },
  {
    id: 'PROJECT_MANAGER',
    sectorId: 'MANAGEMENT_CONSULTING',
    nameAr: 'مدير مشاريع',
    nameEn: 'Project Manager',
    aliases: ['إدارة مشاريع', 'PM'],
    profileTypes: ['مهني', 'متخصص'],
    specializationIds: ['operations', 'project_coordination'],
    serviceIds: ['consulting', 'coordination', 'supervision'],
  },
  {
    id: 'QUALITY_CONSULTANT',
    sectorId: 'MANAGEMENT_CONSULTING',
    nameAr: 'مستشار جودة',
    nameEn: 'Quality Consultant',
    aliases: ['جودة', 'ISO'],
    profileTypes: ['خبير / مستشار', 'متخصص'],
    specializationIds: ['quality'],
    serviceIds: ['consulting', 'auditing', 'training'],
  },
  {
    id: 'SAFETY_CONSULTANT',
    sectorId: 'MANAGEMENT_CONSULTING',
    nameAr: 'مستشار سلامة',
    nameEn: 'Safety Consultant',
    aliases: ['سلامة', 'أمن وسلامة'],
    profileTypes: ['خبير / مستشار', 'متخصص'],
    specializationIds: ['safety'],
    serviceIds: ['consulting', 'training', 'auditing'],
  },
  {
    id: 'PROCUREMENT_SPECIALIST',
    sectorId: 'MANAGEMENT_CONSULTING',
    nameAr: 'أخصائي مشتريات',
    nameEn: 'Procurement Specialist',
    aliases: ['مشتريات', 'توريد'],
    profileTypes: ['مهني', 'متخصص'],
    specializationIds: ['procurement', 'logistics'],
    serviceIds: ['consulting', 'coordination'],
  },
  {
    id: 'LOGISTICS_CONSULTANT',
    sectorId: 'MANAGEMENT_CONSULTING',
    nameAr: 'مستشار لوجستيات',
    nameEn: 'Logistics Consultant',
    aliases: ['لوجستيات', 'نقل', 'تخزين'],
    profileTypes: ['خبير / مستشار', 'مهني'],
    specializationIds: ['logistics', 'operations'],
    serviceIds: ['consulting', 'coordination'],
  },
  {
    id: 'VOLUNTEER_COORDINATOR',
    sectorId: 'MANAGEMENT_CONSULTING',
    nameAr: 'منسّق تطوع',
    nameEn: 'Volunteer Coordinator',
    aliases: ['تطوع', 'جمعيات'],
    profileTypes: ['مهني', 'مقدم خدمة'],
    specializationIds: ['volunteer_coordination'],
    serviceIds: ['coordination', 'training', 'volunteering'],
  },

  // ─────────────────────────────────────────────────────────────
  // Expanded catalog: manual trades, technical, vehicles, domestic
  // ─────────────────────────────────────────────────────────────

  // Metal, electrical, doors, solar
  {
    id: 'METAL_TECHNICIAN',
    sectorId: 'MANUAL_TRADES',
    nameAr: 'فني ميتال / تشكيل معادن',
    nameEn: 'Metal Technician / Fabricator',
    aliases: ['ميتال', 'حداد ميتال', 'تشكيل حديد', 'مصفح معدني'],
    profileTypes: ['حرفي', 'فني'],
    specializationIds: ['metal_fabrication', 'metal_finishing', 'structural', 'decorative'],
    serviceIds: ['fabrication', 'welding', 'cutting', 'design', 'installation', 'polishing', 'repair', 'maintenance'],
  },
  {
    id: 'AUTOMATIC_DOOR_TECHNICIAN',
    sectorId: 'MANUAL_TRADES',
    nameAr: 'فني أبواب أوتوماتيكية',
    nameEn: 'Automatic Door Technician',
    aliases: ['أبواب أوتوماتيك', 'باب اوتوماتيك', 'فني بوابات'],
    profileTypes: ['حرفي', 'فني'],
    specializationIds: ['automatic_doors', 'sliding_doors', 'revolving_doors'],
    serviceIds: ['installation', 'maintenance', 'repair', 'consulting'],
  },
  {
    id: 'SHUTTER_TECHNICIAN',
    sectorId: 'MANUAL_TRADES',
    nameAr: 'فني شتر / بوابات سحّابة',
    nameEn: 'Shutter & Rolling Door Technician',
    aliases: ['شتر', 'رول', 'بوابة سحابة', 'ستارة سحابة'],
    profileTypes: ['حرفي', 'فني'],
    specializationIds: ['roller_shutters', 'security_shutters', 'aluminum_shutters'],
    serviceIds: ['installation', 'repair', 'maintenance', 'consulting'],
  },
  {
    id: 'SOLAR_TECHNICIAN',
    sectorId: 'MANUAL_TRADES',
    nameAr: 'فني طاقة شمسية',
    nameEn: 'Solar Energy Technician',
    aliases: ['طاقة شمسية', 'فوتوفولتائيك', 'فني سولار', 'تركيب ألواح'],
    profileTypes: ['فني', 'متخصص'],
    specializationIds: ['solar_panels', 'solar_water_heaters', 'off_grid_systems', 'solar'],
    serviceIds: ['installation', 'maintenance', 'repair', 'consulting', 'diagnosis'],
  },

  // Vehicles & security tech
  {
    id: 'VEHICLE_GPS_TECHNICIAN',
    sectorId: 'VEHICLES_TRANSPORT',
    nameAr: 'فني GPS وملاحة للمركبات',
    nameEn: 'Vehicle GPS & Navigation Technician',
    aliases: ['GPS', 'جي بي اس', 'تتبع مركبات', 'فني ملاحة'],
    profileTypes: ['فني', 'متخصص'],
    specializationIds: ['vehicle_gps', 'fleet_tracking', 'navigation_systems'],
    serviceIds: ['installation', 'gps_programming', 'fleet_setup', 'maintenance', 'consulting'],
  },
  {
    id: 'CCTV_TECHNICIAN',
    sectorId: 'TECHNICAL_SERVICES',
    nameAr: 'فني كاميرات مراقبة وأنظمة أمنية',
    nameEn: 'CCTV & Security Systems Technician',
    aliases: ['كاميرات مراقبة', 'CCTV', 'سي سي تي في', 'أنظمة أمنية'],
    profileTypes: ['فني', 'متخصص'],
    specializationIds: ['cctv', 'ip_cameras', 'security_alarms', 'access_control'],
    serviceIds: ['installation', 'maintenance', 'repair', 'consulting', 'diagnosis'],
  },

  // Professional & paperwork
  {
    id: 'TRANSACTION_FACILITATOR',
    sectorId: 'PROFESSIONAL_SERVICES',
    nameAr: 'معقب معاملات / إنجاز إجراءات',
    nameEn: 'Transaction Facilitator',
    aliases: ['معقب', 'إنجاز معاملات', 'إجراءات حكومية', 'تخليص'],
    profileTypes: ['مهني', 'مقدم خدمة'],
    specializationIds: ['government_procedures', 'commercial_licenses', 'residency_services', 'company_registration'],
    serviceIds: ['paperwork', 'government_filing', 'coordination', 'consulting', 'brokerage'],
  },

  // Events, media & performing
  {
    id: 'WEDDING_PLANNER',
    sectorId: 'CREATIVE_MEDIA',
    nameAr: 'منسّق / منظّم أفراح وزواج',
    nameEn: 'Wedding Planner & Event Coordinator',
    aliases: ['أفراح', 'زواج', 'منسق أعراس', 'منظم مناسبات'],
    profileTypes: ['مبدع', 'مقدم خدمة'],
    specializationIds: ['wedding_planning', 'wedding_coordination', 'events', 'weddings'],
    serviceIds: ['design', 'coordination', 'consulting', 'execution'],
  },
  {
    id: 'MESAHARTY',
    sectorId: 'PERFORMING_ARTS',
    nameAr: 'مسحراتي',
    nameEn: 'Mesaharty (Ramadan Drummer)',
    aliases: ['مسحراتي', 'طبول رمضان', 'صاحب مسحر'],
    profileTypes: ['موهوب', 'مقدم خدمة'],
    specializationIds: ['ramadan_drum', 'neighborhood_calls'],
    serviceIds: ['performance', 'hosting'],
  },
  {
    id: 'HADITH_NARRATOR',
    sectorId: 'EDUCATION_TRAINING',
    nameAr: 'راوي حديث / محدّث',
    nameEn: 'Hadith Narrator',
    aliases: ['راوي حديث', 'محدث', 'حديث نبوي'],
    profileTypes: ['مهني', 'موهوب'],
    specializationIds: ['hadith', 'sunnah', 'religious'],
    serviceIds: ['teaching', 'storytelling', 'mentoring', 'consulting'],
  },

  // Agriculture & animals
  {
    id: 'AQUARIUM_TECHNICIAN',
    sectorId: 'AGRICULTURE_ANIMALS',
    nameAr: 'فني أحواض أسماك وزينة',
    nameEn: 'Aquarium Technician',
    aliases: ['أحواض سمك', 'حوض سمك', 'أكواريوم'],
    profileTypes: ['حرفي', 'فني'],
    specializationIds: ['aquarium_setup', 'marine_tanks', 'freshwater_tanks'],
    serviceIds: ['installation', 'maintenance', 'cleaning', 'consulting'],
  },
  {
    id: 'BIRD_BREEDER',
    sectorId: 'AGRICULTURE_ANIMALS',
    nameAr: 'مربي طيور زينة',
    nameEn: 'Ornamental Bird Breeder',
    aliases: ['طيور زينة', 'مربي طيور', 'عصافير'],
    profileTypes: ['حرفي', 'مهني'],
    specializationIds: ['ornamental_birds', 'poultry'],
    serviceIds: ['breeding', 'feeding', 'bird_care', 'consulting'],
  },
  {
    id: 'FEED_TECHNICIAN',
    sectorId: 'AGRICULTURE_ANIMALS',
    nameAr: 'فني أعلاف',
    nameEn: 'Animal Feed Technician',
    aliases: ['أعلاف', 'فني علف', 'تصنيع أعلاف'],
    profileTypes: ['فني', 'مهني'],
    specializationIds: ['animal_feed', 'poultry_feed', 'livestock_feed'],
    serviceIds: ['feed_formulation', 'consulting'],
  },
  {
    id: 'HORSE_GROOM',
    sectorId: 'AGRICULTURE_ANIMALS',
    nameAr: 'سايس خيل / مضمّر',
    nameEn: 'Horse Groom / Stable Hand',
    aliases: ['سايس', 'سايس خيل', 'مضمر خيول', 'عناية بالخيول'],
    profileTypes: ['حرفي', 'مهني'],
    specializationIds: ['horse_care', 'stable_management', 'sports_equestrian'],
    serviceIds: ['horse_grooming', 'stable_cleaning', 'feeding', 'training_animals'],
  },
  {
    id: 'CAMEL_BREEDER',
    sectorId: 'AGRICULTURE_ANIMALS',
    nameAr: 'مربي إبل / هجان',
    nameEn: 'Camel Breeder',
    aliases: ['إبل', 'هجن', 'مربي هجن', 'هجان'],
    profileTypes: ['حرفي', 'مهني'],
    specializationIds: ['camel_care', 'camel_racing', 'livestock'],
    serviceIds: ['breeding', 'feeding', 'camel_training', 'consulting'],
  },

  // Care
  {
    id: 'HOME_NURSE',
    sectorId: 'CARE_GIVING',
    nameAr: 'ممرض / ممرضة منزلية',
    nameEn: 'Home Nurse',
    aliases: ['ممرض منزلي', 'ممرضة منزلية', 'ممرض كبار السن', 'تمريض منزلي'],
    profileTypes: ['متخصص', 'مقدم خدمة'],
    specializationIds: ['home_nursing', 'elderly_nursing', 'pediatric_nursing', 'patient_care'],
    serviceIds: ['nursing', 'caregiving', 'consulting'],
    requiresLicense: true,
  },

  // Traditional crafts
  {
    id: 'HAND_EMBROIDERER',
    sectorId: 'TRADITIONAL_CRAFTS',
    nameAr: 'مطرّز / مطرّزة يدوية',
    nameEn: 'Hand Embroiderer',
    aliases: ['تطريز يدوي', 'مطرز يدوي', 'تطريز تقليدي'],
    profileTypes: ['حرفي', 'مبدع'],
    specializationIds: ['embroidery_hand', 'traditional_dress'],
    serviceIds: ['embroidery', 'sewing', 'design'],
  },
  {
    id: 'HOOKAH_CRAFTSMAN',
    sectorId: 'TRADITIONAL_CRAFTS',
    nameAr: 'صانع أرجيلة ومستلزماتها',
    nameEn: 'Hookah Craftsman',
    aliases: ['أرجيلة', 'شيشة', 'نارجيلة', 'صناعة شيشة'],
    profileTypes: ['حرفي', 'مبدع'],
    specializationIds: ['hookah_manufacturing', 'hookah_accessories'],
    serviceIds: ['fabrication', 'design', 'repair', 'consulting'],
    requiresLicense: true,
  },

  // Domestic services
  {
    id: 'DOMESTIC_HELPER',
    sectorId: 'DOMESTIC_SERVICES',
    nameAr: 'عامل / عاملة منزلية',
    nameEn: 'Domestic Helper',
    aliases: ['خادمة', 'خادم', 'مساعد منزلي', 'عمالة منزلية'],
    profileTypes: ['مقدم خدمة'],
    specializationIds: ['domestic_cleaning', 'home_care'],
    serviceIds: ['cleaning', 'cooking', 'caregiving'],
  },
  {
    id: 'CHILDCARE_PROVIDER',
    sectorId: 'DOMESTIC_SERVICES',
    nameAr: 'مربية / جليسة أطفال',
    nameEn: 'Childcare Provider / Nanny',
    aliases: ['مربية أطفال', 'جليسة أطفال', 'بيبي سيتر', 'حاضنة'],
    profileTypes: ['مقدم خدمة', 'مهني'],
    specializationIds: ['childcare', 'nursery', 'early_childhood'],
    serviceIds: ['caregiving', 'teaching'],
  },
  {
    id: 'HOME_CARETAKER',
    sectorId: 'DOMESTIC_SERVICES',
    nameAr: 'حارس منزل / بواب / ناطور',
    nameEn: 'Home Caretaker / Doorman',
    aliases: ['ناطور', 'بواب', 'حارس منزل', 'حارس باب'],
    profileTypes: ['مقدم خدمة', 'مهني'],
    specializationIds: ['home_security', 'gatekeeping'],
    serviceIds: ['guarding', 'cleaning', 'maintenance'],
  },

  // Vehicles & transport
  {
    id: 'CAR_RENTAL_AGENT',
    sectorId: 'VEHICLES_TRANSPORT',
    nameAr: 'وكيل / مكتب تأجير سيارات',
    nameEn: 'Car Rental Agent',
    aliases: ['تأجير سيارات', 'مكتب تأجير', 'استئجار سيارات'],
    profileTypes: ['مهني', 'مقدم خدمة'],
    specializationIds: ['car_rental', 'fleet_rental'],
    serviceIds: ['rental', 'coordination', 'consulting'],
  },
  {
    id: 'PRIVATE_DRIVER',
    sectorId: 'VEHICLES_TRANSPORT',
    nameAr: 'سائق خاص',
    nameEn: 'Private Driver',
    aliases: ['سائق', 'سواق', 'سائق خاص', 'توصيل'],
    profileTypes: ['مقدم خدمة', 'مهني'],
    specializationIds: ['personal_driving', 'airport_transfers'],
    serviceIds: ['driving', 'coordination'],
  },

  // High-level engineering & administrative
  {
    id: 'ENGINEER',
    sectorId: 'PROFESSIONAL_SERVICES',
    nameAr: 'مهندس',
    nameEn: 'Engineer',
    aliases: ['مهندس', 'مهندسة', 'engineering'],
    profileTypes: ['مهني', 'متخصص'],
    specializationIds: ['civil_engineering', 'electrical_engineering', 'mechanical_engineering', 'architectural_engineering', 'structural_engineering'],
    serviceIds: ['design', 'consulting', 'supervision', 'execution', 'development'],
  },
  {
    id: 'ADMINISTRATIVE_MANAGER',
    sectorId: 'MANAGEMENT_CONSULTING',
    nameAr: 'مدير إداري / مدير مكتب',
    nameEn: 'Administrative Manager / Office Manager',
    aliases: ['مدير إداري', 'مدير مكتب', 'إداري', 'إدارة'],
    profileTypes: ['مهني', 'خبير / مستشار'],
    specializationIds: ['office_management', 'administrative_operations', 'facilities_management', 'hr', 'operations'],
    serviceIds: ['consulting', 'coordination', 'supervision', 'advisory'],
  },

  // ─────────────────────────────────────────────────────────────
  // Final classification round: elevators, security, camels,
  // jewelry/locks, and regulated healthcare professions
  // ─────────────────────────────────────────────────────────────

  // Elevators, escalators & moving walkways
  {
    id: 'ELEVATOR_TECHNICIAN',
    sectorId: 'MANUAL_TRADES',
    nameAr: 'فني مصاعد',
    nameEn: 'Elevator Technician',
    aliases: ['مصعد', 'فني مصاعد', 'مصاعد', 'تركيب مصاعد', 'صيانة مصاعد'],
    profileTypes: ['فني'],
    specializationIds: [
      'elevator_installation',
      'elevator_maintenance',
      'elevator_faults',
      'elevator_control',
      'elevator_doors',
      'elevator_cabins',
      'elevator_hydraulic',
      'home_elevators',
      'cargo_elevators',
      'car_elevators',
      'restaurant_elevators',
    ],
    serviceIds: ['installation', 'maintenance', 'repair', 'diagnosis', 'consulting', 'emergency'],
  },
  {
    id: 'ESCALATOR_TECHNICIAN',
    sectorId: 'MANUAL_TRADES',
    nameAr: 'فني سلالم كهربائية',
    nameEn: 'Escalator Technician',
    aliases: ['سلم كهربائي', 'سلالم كهربائية', 'فني سلالم'],
    profileTypes: ['فني'],
    specializationIds: ['escalator_installation', 'escalator_maintenance', 'escalator_faults', 'escalator_control'],
    serviceIds: ['installation', 'maintenance', 'repair', 'diagnosis', 'emergency'],
  },
  {
    id: 'MOVING_WALKWAY_TECHNICIAN',
    sectorId: 'MANUAL_TRADES',
    nameAr: 'فني ممرات متحركة',
    nameEn: 'Moving Walkway Technician',
    aliases: ['ممر متحرك', 'ممرات متحركة', 'فني ممرات'],
    profileTypes: ['فني'],
    specializationIds: ['moving_walkway_installation', 'moving_walkway_maintenance', 'moving_walkway_faults', 'moving_walkway_control'],
    serviceIds: ['installation', 'maintenance', 'repair', 'diagnosis', 'emergency'],
  },

  // Fire alarm
  {
    id: 'FIRE_ALARM_TECHNICIAN',
    sectorId: 'TECHNICAL_SERVICES',
    nameAr: 'فني أنظمة إنذار الحريق',
    nameEn: 'Fire Alarm Technician',
    aliases: ['إنذار حريق', 'Fire Alarm', 'كشف دخان', 'كواشف دخان', 'لوحة إنذار حريق'],
    profileTypes: ['فني', 'متخصص'],
    specializationIds: ['fire_alarm_panels', 'smoke_detectors', 'heat_detectors', 'sirens', 'addressable_systems', 'conventional_systems', 'fire_alarm_testing'],
    serviceIds: ['installation', 'maintenance', 'repair', 'testing', 'consulting', 'diagnosis'],
    requiresLicense: true,
  },

  // Smart access
  {
    id: 'SMART_LOCK_TECHNICIAN',
    sectorId: 'TECHNICAL_SERVICES',
    nameAr: 'فني أقفال ذكية',
    nameEn: 'Smart Lock Technician',
    aliases: ['قفل ذكي', 'أقفال ذكية', 'قفل إلكتروني', 'Keyless Entry'],
    profileTypes: ['فني', 'متخصص'],
    specializationIds: ['smart_locks', 'electronic_locks', 'keyless_entry'],
    serviceIds: ['installation', 'programming', 'repair', 'consulting'],
  },
  {
    id: 'ACCESS_CONTROL_TECHNICIAN',
    sectorId: 'TECHNICAL_SERVICES',
    nameAr: 'فني أنظمة دخول وتحكم',
    nameEn: 'Access Control Technician',
    aliases: ['Access Control', 'أنظمة دخول', 'تحكم بالدخول', 'بوابات دخول'],
    profileTypes: ['فني', 'متخصص'],
    specializationIds: ['access_control', 'card_readers', 'barriers', 'turnstiles'],
    serviceIds: ['installation', 'maintenance', 'repair', 'consulting'],
  },
  {
    id: 'BIOMETRIC_ACCESS_TECHNICIAN',
    sectorId: 'TECHNICAL_SERVICES',
    nameAr: 'فني بصمة ودخول ذكي',
    nameEn: 'Biometric Access Technician',
    aliases: ['بصمة', 'دخول ذكي', 'Face Recognition', 'تعرف وجه', 'بصمة إصبع'],
    profileTypes: ['فني', 'متخصص'],
    specializationIds: ['biometric_access', 'fingerprint', 'face_recognition', 'palm_recognition'],
    serviceIds: ['installation', 'programming', 'repair', 'consulting'],
  },

  // Professional security
  {
    id: 'SECURITY_GUARD',
    sectorId: 'SECURITY_SERVICES',
    nameAr: 'حارس أمن',
    nameEn: 'Security Guard',
    aliases: ['حارس أمن', 'أمن', 'حراسة'],
    profileTypes: ['مهني', 'مقدم خدمة'],
    specializationIds: ['security_guarding', 'security_patrol', 'crowd_control'],
    serviceIds: ['guarding', 'consulting'],
    requiresLicense: true,
  },
  {
    id: 'SECURITY_SUPERVISOR',
    sectorId: 'SECURITY_SERVICES',
    nameAr: 'مشرف أمن',
    nameEn: 'Security Supervisor',
    aliases: ['مشرف أمن', 'مشرف حراسة'],
    profileTypes: ['مهني', 'خبير / مستشار'],
    specializationIds: ['security_supervision', 'security_guarding', 'facility_security'],
    serviceIds: ['supervision', 'consulting', 'training'],
    requiresLicense: true,
  },
  {
    id: 'FACILITY_SECURITY_GUARD',
    sectorId: 'SECURITY_SERVICES',
    nameAr: 'حارس أمن منشآت',
    nameEn: 'Facility Security Guard',
    aliases: ['حارس منشآت', 'أمن منشآت', 'حراسة منشآت'],
    profileTypes: ['مهني', 'مقدم خدمة'],
    specializationIds: ['facility_security', 'security_guarding', 'security_patrol'],
    serviceIds: ['guarding', 'consulting'],
    requiresLicense: true,
  },

  // Camel care split
  {
    id: 'CAMEL_CARETAKER',
    sectorId: 'AGRICULTURE_ANIMALS',
    nameAr: 'سايس إبل',
    nameEn: 'Camel Caretaker',
    aliases: ['سايس جمل', 'سايس نوق', 'عناية بالإبل'],
    profileTypes: ['حرفي', 'مهني'],
    specializationIds: ['camel_care', 'camel_grooming', 'livestock'],
    serviceIds: ['feeding', 'caregiving', 'cleaning'],
  },
  {
    id: 'CAMEL_RACING_TRAINER',
    sectorId: 'AGRICULTURE_ANIMALS',
    nameAr: 'مضمر هجن',
    nameEn: 'Camel Racing Trainer',
    aliases: ['مضمر', 'مضمر هجن', 'تضمير هجن'],
    profileTypes: ['حرفي', 'متخصص'],
    specializationIds: ['camel_racing', 'camel_care', 'camel_training'],
    serviceIds: ['training_animals', 'feeding', 'consulting'],
  },
  {
    id: 'CAMEL_TRAINER',
    sectorId: 'AGRICULTURE_ANIMALS',
    nameAr: 'مدرب هجن',
    nameEn: 'Camel Trainer',
    aliases: ['مدرب هجن', 'هجان', 'تدريب إبل'],
    profileTypes: ['حرفي', 'متخصص'],
    specializationIds: ['camel_training', 'camel_care', 'camel_racing'],
    serviceIds: ['training_animals', 'consulting'],
  },

  // Jewelry, watches, keys & locks
  {
    id: 'GOLDSMITH',
    sectorId: 'TRADITIONAL_CRAFTS',
    nameAr: 'صائغ ذهب',
    nameEn: 'Goldsmith',
    aliases: ['صائغ', 'صياغة ذهب', 'ذهب'],
    profileTypes: ['حرفي', 'مبدع'],
    specializationIds: ['goldsmithing', 'jewelry_making'],
    serviceIds: ['fabrication', 'design', 'repair', 'polishing'],
  },
  {
    id: 'SILVERSMITH',
    sectorId: 'TRADITIONAL_CRAFTS',
    nameAr: 'صائغ فضة',
    nameEn: 'Silversmith',
    aliases: ['صياغة فضة', 'فضة'],
    profileTypes: ['حرفي', 'مبدع'],
    specializationIds: ['silversmithing', 'jewelry_making'],
    serviceIds: ['fabrication', 'design', 'repair', 'polishing'],
  },
  {
    id: 'JEWELER',
    sectorId: 'TRADITIONAL_CRAFTS',
    nameAr: 'صانع مجوهرات',
    nameEn: 'Jeweler',
    aliases: ['مجوهرات', 'صناعة مجوهرات'],
    profileTypes: ['حرفي', 'مبدع'],
    specializationIds: ['jewelry_making', 'goldsmithing', 'silversmithing'],
    serviceIds: ['fabrication', 'design', 'repair', 'consulting'],
  },
  {
    id: 'JEWELRY_REPAIRER',
    sectorId: 'TRADITIONAL_CRAFTS',
    nameAr: 'مصلح مجوهرات',
    nameEn: 'Jewelry Repairer',
    aliases: ['إصلاح مجوهرات', 'تصليح ذهب', 'تصليح فضة'],
    profileTypes: ['حرفي'],
    specializationIds: ['jewelry_repair', 'jewelry_making'],
    serviceIds: ['repair', 'polishing', 'cleaning'],
  },
  {
    id: 'WATCHMAKER',
    sectorId: 'TRADITIONAL_CRAFTS',
    nameAr: 'ساعاتي / مصلح ساعات',
    nameEn: 'Watchmaker / Watch Repairer',
    aliases: ['ساعاتي', 'إصلاح ساعات', 'تصليح ساعات'],
    profileTypes: ['حرفي', 'فني'],
    specializationIds: ['watch_repair'],
    serviceIds: ['repair', 'maintenance', 'cleaning'],
  },
  {
    id: 'KEY_CUTTER',
    sectorId: 'TRADITIONAL_CRAFTS',
    nameAr: 'صانع مفاتيح',
    nameEn: 'Key Cutter',
    aliases: ['قص مفاتيح', 'كوالين', 'مفاتيح'],
    profileTypes: ['حرفي'],
    specializationIds: ['key_cutting'],
    serviceIds: ['key_cutting_service'],
  },
  {
    id: 'LOCKSMITH',
    sectorId: 'TRADITIONAL_CRAFTS',
    nameAr: 'فني أقفال وكوالين',
    nameEn: 'Locksmith',
    aliases: ['كوالين', 'فتح أقفال', 'أقفال', 'قفل'],
    profileTypes: ['حرفي', 'فني'],
    specializationIds: ['lock_repair', 'lock_installation', 'key_cutting'],
    serviceIds: ['lock_repair_service', 'lock_installation_service', 'key_cutting_service'],
  },
  {
    id: 'CAR_KEY_TECHNICIAN',
    sectorId: 'VEHICLES_TRANSPORT',
    nameAr: 'فني مفاتيح سيارات',
    nameEn: 'Car Key Technician',
    aliases: ['مفاتيح سيارات', 'برمجة مفاتيح', 'مفتاح سيارة', 'فتح سيارات'],
    profileTypes: ['فني', 'حرفي'],
    specializationIds: ['car_key_programming', 'key_cutting'],
    serviceIds: ['car_key_programming_service', 'key_cutting_service', 'diagnosis'],
  },

  // Regulated healthcare professions
  {
    id: 'PHARMACIST',
    sectorId: 'PROFESSIONAL_SERVICES',
    nameAr: 'صيدلي',
    nameEn: 'Pharmacist',
    aliases: ['صيدلي', 'صيدلانية', 'دواء'],
    profileTypes: ['مهني', 'متخصص'],
    specializationIds: ['pharmacy'],
    serviceIds: ['dispensing', 'consulting', 'advisory'],
    requiresLicense: true,
  },
  {
    id: 'RADIOLOGY_TECHNICIAN',
    sectorId: 'PROFESSIONAL_SERVICES',
    nameAr: 'فني أشعة',
    nameEn: 'Radiology Technician',
    aliases: ['فني أشعة', 'أشعة', 'أخصائي أشعة'],
    profileTypes: ['مهني', 'متخصص'],
    specializationIds: ['radiology'],
    serviceIds: ['imaging', 'consulting'],
    requiresLicense: true,
  },
  {
    id: 'LAB_TECHNICIAN',
    sectorId: 'PROFESSIONAL_SERVICES',
    nameAr: 'فني مختبر',
    nameEn: 'Laboratory Technician',
    aliases: ['فني مختبر', 'مختبر', 'تحاليل'],
    profileTypes: ['مهني', 'متخصص'],
    specializationIds: ['laboratory'],
    serviceIds: ['lab_testing', 'consulting'],
    requiresLicense: true,
  },
  {
    id: 'DIETITIAN',
    sectorId: 'PROFESSIONAL_SERVICES',
    nameAr: 'أخصائي تغذية',
    nameEn: 'Dietitian',
    aliases: ['تغذية', 'أخصائية تغذية', 'دايت', 'رجيم'],
    profileTypes: ['مهني', 'متخصص'],
    specializationIds: ['dietetics', 'healthy_food'],
    serviceIds: ['nutrition_planning', 'consulting', 'advisory'],
    requiresLicense: true,
  },
  {
    id: 'HEALTHCARE_ASSISTANT',
    sectorId: 'CARE_GIVING',
    nameAr: 'مساعد صحي',
    nameEn: 'Healthcare Assistant',
    aliases: ['مساعد صحي', 'مساعد تمريض', 'مساعد طبي'],
    profileTypes: ['مقدم خدمة', 'مهني'],
    specializationIds: ['healthcare_assisting', 'patient_care', 'home_care'],
    serviceIds: ['caregiving', 'nursing', 'consulting'],
    requiresLicense: true,
  },
  {
    id: 'ELDERLY_CARE_NURSE',
    sectorId: 'CARE_GIVING',
    nameAr: 'ممرض / ممرضة كبار السن',
    nameEn: 'Elderly Care Nurse',
    aliases: ['ممرض كبار السن', 'ممرضة كبار السن', 'تمريض مسنين'],
    profileTypes: ['متخصص', 'مقدم خدمة'],
    specializationIds: ['elderly_nursing', 'patient_care', 'home_care'],
    serviceIds: ['nursing', 'caregiving', 'consulting'],
    requiresLicense: true,
  },
];

function normalizeLookup(text: string): string {
  return text
    .toLowerCase()
    .trim()
    .replace(/[إأآا]/g, 'ا')
    .replace(/ى/g, 'ي')
    .replace(/ة/g, 'ه')
    .replace(/ـ/g, '')
    .replace(/[-_]/g, '')
    .replace(/\s+/g, '');
}

export function getProfession(id: string): ProfessionOption | undefined {
  if (!id) return undefined;
  const byId = professions.find((p) => p.id === id);
  if (byId) return byId;
  const q = normalizeLookup(id);
  return professions.find((p) => {
    if (normalizeLookup(p.nameAr) === q) return true;
    if (p.nameEn && normalizeLookup(p.nameEn) === q) return true;
    return p.aliases.some((a) => normalizeLookup(a) === q);
  });
}

export function getProfessionsBySector(sectorId: string): ProfessionOption[] {
  return professions.filter((p) => p.sectorId === sectorId);
}
