import { ServiceOption } from './types';

export const services: ServiceOption[] = [
  { id: 'installation', nameAr: 'تركيب', nameEn: 'Installation' },
  { id: 'maintenance', nameAr: 'صيانة', nameEn: 'Maintenance' },
  { id: 'repair', nameAr: 'إصلاح', nameEn: 'Repair' },
  { id: 'diagnosis', nameAr: 'فحص وتشخيص', nameEn: 'Diagnosis' },
  { id: 'fabrication', nameAr: 'تفصيل وتصنيع', nameEn: 'Fabrication' },
  { id: 'design', nameAr: 'تصميم', nameEn: 'Design' },
  { id: 'execution', nameAr: 'تنفيذ', nameEn: 'Execution' },
  { id: 'consulting', nameAr: 'استشارة', nameEn: 'Consulting' },
  { id: 'training', nameAr: 'تدريب', nameEn: 'Training' },
  { id: 'supervision', nameAr: 'إشراف', nameEn: 'Supervision' },
  { id: 'emergency', nameAr: 'طوارئ', nameEn: 'Emergency' },
  { id: 'mobile_service', nameAr: 'خدمة متنقلة', nameEn: 'Mobile Service' },
  { id: 'cleaning', nameAr: 'تنظيف', nameEn: 'Cleaning' },
  { id: 'polishing', nameAr: 'تلميع', nameEn: 'Polishing' },
  { id: 'painting', nameAr: 'دهان', nameEn: 'Painting' },
  { id: 'welding', nameAr: 'لحام', nameEn: 'Welding' },
  { id: 'cutting', nameAr: 'قص', nameEn: 'Cutting' },
  { id: 'bending', nameAr: 'ثني', nameEn: 'Bending' },
  { id: 'programming', nameAr: 'برمجة', nameEn: 'Programming' },
  { id: 'photography', nameAr: 'تصوير', nameEn: 'Photography' },
  { id: 'video', nameAr: 'فيديو', nameEn: 'Video' },
  { id: 'montage', nameAr: 'مونتاج', nameEn: 'Montage' },
  { id: 'sound', nameAr: 'تعليق صوتي', nameEn: 'Voiceover' },
  { id: 'hosting', nameAr: 'تقديم', nameEn: 'Hosting' },
  { id: 'shaving', nameAr: 'حلاقة ذقن', nameEn: 'Shaving' },
  { id: 'makeup', nameAr: 'مكياج', nameEn: 'Makeup' },
  { id: 'alterations', nameAr: 'تصليحات', nameEn: 'Alterations' },
  { id: 'recording', nameAr: 'تسجيل', nameEn: 'Recording' },
  { id: 'mentoring', nameAr: 'توجيه', nameEn: 'Mentoring' },
  { id: 'nursing', nameAr: 'تمريض', nameEn: 'Nursing' },
  { id: 'caregiving', nameAr: 'رعاية', nameEn: 'Caregiving' },
  { id: 'guiding', nameAr: 'إرشاد', nameEn: 'Guiding' },
  { id: 'rental', nameAr: 'تأجير', nameEn: 'Rental' },
  { id: 'brokerage', nameAr: 'وساطة', nameEn: 'Brokerage' },
  { id: 'coordination', nameAr: 'تنسيق', nameEn: 'Coordination' },
  { id: 'sewing', nameAr: 'خياطة', nameEn: 'Sewing' },
  { id: 'embroidery', nameAr: 'تطريز', nameEn: 'Embroidery' },
  { id: 'butchery', nameAr: 'جزارة', nameEn: 'Butchery' },
  { id: 'cooking', nameAr: 'طبخ', nameEn: 'Cooking' },
  { id: 'harvesting', nameAr: 'حصاد', nameEn: 'Harvesting' },
  { id: 'packaging', nameAr: 'تعبئة وتغليف', nameEn: 'Packaging' },
  { id: 'haircut', nameAr: 'قص شعر', nameEn: 'Haircut' },
  { id: 'styling', nameAr: 'تسريح', nameEn: 'Styling' },
  { id: 'preparation', nameAr: 'تحضير', nameEn: 'Preparation' },
  { id: 'farming', nameAr: 'زراعة', nameEn: 'Farming' },
  { id: 'fishing', nameAr: 'صيد', nameEn: 'Fishing' },
  { id: 'performance', nameAr: 'أداء', nameEn: 'Performance' },
  { id: 'breeding', nameAr: 'تربية', nameEn: 'Breeding' },
  { id: 'feeding', nameAr: 'تغذية', nameEn: 'Feeding' },
  { id: 'training_animals', nameAr: 'تدريب حيوانات', nameEn: 'Animal Training' },
  { id: 'recitation', nameAr: 'تلاوة', nameEn: 'Recitation' },
  { id: 'storytelling', nameAr: 'سرد قصص', nameEn: 'Storytelling' },
  { id: 'acting', nameAr: 'تمثيل', nameEn: 'Acting' },
  { id: 'content_creation', nameAr: 'صناعة محتوى', nameEn: 'Content Creation' },
  { id: 'development', nameAr: 'تطوير', nameEn: 'Development' },
  { id: 'accounting', nameAr: 'محاسبة', nameEn: 'Accounting' },
  { id: 'auditing', nameAr: 'تدقيق', nameEn: 'Auditing' },
  { id: 'advisory', nameAr: 'استشارات', nameEn: 'Advisory' },
  { id: 'volunteering', nameAr: 'تطوع', nameEn: 'Volunteering' },
  { id: 'teaching', nameAr: 'تعليم', nameEn: 'Teaching' },
  { id: 'translation', nameAr: 'ترجمة', nameEn: 'Translation' },
  // Vehicles & tech
  { id: 'gps_programming', nameAr: 'برمجة GPS', nameEn: 'GPS Programming' },
  { id: 'fleet_setup', nameAr: 'إعداد أسطول', nameEn: 'Fleet Setup' },
  // Paperwork
  { id: 'paperwork', nameAr: 'إنجاز معاملات', nameEn: 'Paperwork' },
  { id: 'government_filing', nameAr: 'تقديم طلبات حكومية', nameEn: 'Government Filing' },
  // Agriculture & animals
  { id: 'bird_care', nameAr: 'رعاية طيور', nameEn: 'Bird Care' },
  { id: 'feed_formulation', nameAr: 'تصنيع أعلاف', nameEn: 'Feed Formulation' },
  { id: 'stable_cleaning', nameAr: 'تنظيف إسطبلات', nameEn: 'Stable Cleaning' },
  { id: 'horse_grooming', nameAr: 'تهذيب الخيول', nameEn: 'Horse Grooming' },
  { id: 'camel_training', nameAr: 'تدريب إبل', nameEn: 'Camel Training' },
  // Domestic & care
  { id: 'guarding', nameAr: 'حراسة', nameEn: 'Guarding' },
  { id: 'driving', nameAr: 'قيادة', nameEn: 'Driving' },
  // Testing & healthcare
  { id: 'testing', nameAr: 'اختبار', nameEn: 'Testing' },
  { id: 'dispensing', nameAr: 'صرف أدوية', nameEn: 'Dispensing' },
  { id: 'imaging', nameAr: 'تصوير طبي', nameEn: 'Medical Imaging' },
  { id: 'lab_testing', nameAr: 'تحاليل مختبرية', nameEn: 'Lab Testing' },
  { id: 'therapy', nameAr: 'علاج', nameEn: 'Therapy' },
  { id: 'nutrition_planning', nameAr: 'تخطيط تغذي', nameEn: 'Nutrition Planning' },
  // Locks & keys
  { id: 'key_cutting_service', nameAr: 'قص مفاتيح', nameEn: 'Key Cutting' },
  { id: 'lock_repair_service', nameAr: 'إصلاح أقفال', nameEn: 'Lock Repair' },
  { id: 'lock_installation_service', nameAr: 'تركيب أقفال', nameEn: 'Lock Installation' },
  { id: 'car_key_programming_service', nameAr: 'برمجة مفاتيح سيارات', nameEn: 'Car Key Programming' },
];

export function getService(id: string): ServiceOption | undefined {
  return services.find((s) => s.id === id);
}
