import { SpecializationOption } from './types';

export const specializations: SpecializationOption[] = [
  { id: 'residential', nameAr: 'منازل', nameEn: 'Residential', aliases: ['سكني'] },
  { id: 'commercial', nameAr: 'تجاري', nameEn: 'Commercial', aliases: ['محلات', 'مولات'] },
  { id: 'industrial', nameAr: 'صناعي', nameEn: 'Industrial', aliases: ['مصانع'] },
  { id: 'high_voltage', nameAr: 'جهد عالي', nameEn: 'High Voltage' },
  { id: 'low_voltage', nameAr: 'جهد منخفض', nameEn: 'Low Voltage' },
  { id: 'solar', nameAr: 'طاقة شمسية', nameEn: 'Solar Energy', aliases: ['فوتوفولتائيك'] },
  { id: 'networks', nameAr: 'شبكات', nameEn: 'Networks', aliases: ['كابلات', 'إنترنت'] },
  { id: 'hvac', nameAr: 'تكييف', nameEn: 'HVAC', aliases: ['مكيفات'] },
  { id: 'auto_electrical', nameAr: 'كهرباء سيارات', nameEn: 'Auto Electrical' },
  { id: 'home_appliances', nameAr: 'أجهزة منزلية', nameEn: 'Home Appliances', aliases: ['ثلاجات', 'غسالات'] },
  { id: 'mobile_phones', nameAr: 'هواتف جوالة', nameEn: 'Mobile Phones', aliases: ['جوالات'] },
  { id: 'computers', nameAr: 'حاسوب', nameEn: 'Computers', aliases: ['كمبيوتر', 'لابتوب'] },
  { id: 'tables', nameAr: 'طاولات', nameEn: 'Tables' },
  { id: 'chairs', nameAr: 'كراسي', nameEn: 'Chairs' },
  { id: 'doors', nameAr: 'أبواب', nameEn: 'Doors' },
  { id: 'windows', nameAr: 'نوافذ', nameEn: 'Windows' },
  { id: 'cabinets', nameAr: 'مطابخ وخزائن', nameEn: 'Cabinets', aliases: ['دواليب'] },
  { id: 'upholstery', nameAr: 'تنجيد', nameEn: 'Upholstery' },
  { id: 'wood', nameAr: 'أخشاب', nameEn: 'Wood' },
  { id: 'aluminum', nameAr: 'ألمنيوم', nameEn: 'Aluminum' },
  { id: 'steel', nameAr: 'حديد وصلب', nameEn: 'Steel', aliases: ['معادن'] },
  { id: 'pvc', nameAr: 'PVC وبلاستيك', nameEn: 'PVC & Plastic' },
  { id: 'glass', nameAr: 'زجاج', nameEn: 'Glass' },
  { id: 'gypsum', nameAr: 'جبس', nameEn: 'Gypsum', aliases: ['جبس بورد'] },
  { id: 'plumbing', nameAr: 'سباكة', nameEn: 'Plumbing', aliases: ['مواسير'] },
  { id: 'tile_work', nameAr: 'بلاط ورخام', nameEn: 'Tiling & Marble', aliases: ['سيراميك'] },
  { id: 'painting_interior', nameAr: 'دهان داخلي', nameEn: 'Interior Painting' },
  { id: 'painting_exterior', nameAr: 'دهان خارجي', nameEn: 'Exterior Painting' },
  { id: 'industrial_painting', nameAr: 'دهان صناعي', nameEn: 'Industrial Painting' },
  { id: 'cnc', nameAr: 'CNC', nameEn: 'CNC Machining' },
  { id: 'metalwork', nameAr: 'حدادة', nameEn: 'Metalwork' },
  { id: 'blacksmithing', nameAr: 'نجارة حديد', nameEn: 'Blacksmithing' },
  { id: 'decorative', nameAr: 'ديكور', nameEn: 'Decorative' },
  { id: 'structural', nameAr: 'إنشائي', nameEn: 'Structural' },
  { id: 'tig', nameAr: 'لحام TIG', nameEn: 'TIG Welding' },
  { id: 'mig', nameAr: 'لحام MIG', nameEn: 'MIG Welding' },
  { id: 'arc', nameAr: 'لحام قوسي', nameEn: 'Arc Welding' },
  { id: 'branding', nameAr: 'هوية بصرية', nameEn: 'Branding' },
  { id: 'ui_ux', nameAr: 'UI/UX', nameEn: 'UI/UX Design' },
  { id: 'packaging', nameAr: 'تغليف', nameEn: 'Packaging' },
  { id: 'motion', nameAr: 'موشن جرافيك', nameEn: 'Motion Graphics' },
  { id: 'illustration', nameAr: 'رسم توضيحي', nameEn: 'Illustration' },
  { id: 'social_media', nameAr: 'سوشال ميديا', nameEn: 'Social Media' },
  { id: 'copywriting', nameAr: 'كتابة إعلانية', nameEn: 'Copywriting', aliases: ['كوبي رايتينغ'] },
  { id: 'translation', nameAr: 'ترجمة', nameEn: 'Translation' },
  { id: 'interior_design', nameAr: 'تصميم داخلي', nameEn: 'Interior Design' },
  { id: 'landscape', nameAr: 'تصميم خارجي', nameEn: 'Landscape' },
  { id: 'events', nameAr: 'فعاليات', nameEn: 'Events' },
  { id: 'weddings', nameAr: 'أعراس', nameEn: 'Weddings' },
  { id: 'exhibitions', nameAr: 'معارض', nameEn: 'Exhibitions' },
  { id: 'portrait', nameAr: 'بورتريه', nameEn: 'Portrait' },
  { id: 'product', nameAr: 'منتجات', nameEn: 'Product' },
  { id: 'aerial', nameAr: 'تصوير جوي', nameEn: 'Aerial', aliases: ['درون'] },
  { id: 'food', nameAr: 'تصوير طعام', nameEn: 'Food Photography' },
  { id: 'short_form', nameAr: 'فيديوهات قصيرة', nameEn: 'Short Form' },
  { id: 'documentary', nameAr: 'وثائقي', nameEn: 'Documentary' },
  { id: 'ads', nameAr: 'إعلانات', nameEn: 'Ads' },
  { id: 'voice_drama', nameAr: 'دراما صوتية', nameEn: 'Voice Drama' },
  { id: 'voice_ads', nameAr: 'إعلانات صوتية', nameEn: 'Voice Ads' },
  { id: 'voice_elearning', nameAr: 'تعليم إلكتروني', nameEn: 'E-Learning Voiceover' },
  { id: 'accounting_bookkeeping', nameAr: 'مسك الدفاتر', nameEn: 'Bookkeeping' },
  { id: 'accounting_taxes', nameAr: 'ضرائب', nameEn: 'Tax Accounting' },
  { id: 'accounting_payroll', nameAr: 'رواتب', nameEn: 'Payroll' },
  { id: 'accounting_audit', nameAr: 'تدقيق مالي', nameEn: 'Financial Audit' },
  { id: 'it_support', nameAr: 'دعم فني', nameEn: 'IT Support' },
  { id: 'web_development', nameAr: 'تطوير مواقع', nameEn: 'Web Development' },
  { id: 'app_development', nameAr: 'تطوير تطبيقات', nameEn: 'App Development' },
  { id: 'devops', nameAr: 'DevOps', nameEn: 'DevOps' },
  { id: 'data_analysis', nameAr: 'تحليل بيانات', nameEn: 'Data Analysis' },
  { id: 'cybersecurity', nameAr: 'أمن سيبراني', nameEn: 'Cybersecurity' },
  { id: 'network_setup', nameAr: 'تمديد شبكات', nameEn: 'Network Setup' },
  { id: 'elderly_care', nameAr: 'رعاية مسنين', nameEn: 'Elderly Care' },
  { id: 'child_care', nameAr: 'رعاية أطفال', nameEn: 'Child Care' },
  { id: 'special_needs', nameAr: 'احتياجات خاصة', nameEn: 'Special Needs' },
  { id: 'patient_care', nameAr: 'رعاية مرضى', nameEn: 'Patient Care' },
  { id: 'home_care', nameAr: 'رعاية منزلية', nameEn: 'Home Care' },
  { id: 'tourism_local', nameAr: 'سياحة محلية', nameEn: 'Local Tourism' },
  { id: 'tourism_religious', nameAr: 'سياحة دينية', nameEn: 'Religious Tourism' },
  { id: 'tourism_medical', nameAr: 'سياحة علاجية', nameEn: 'Medical Tourism' },
  { id: 'tourism_adventure', nameAr: 'سياحة مغامرة', nameEn: 'Adventure Tourism' },
  { id: 'men_cuts', nameAr: 'قص رجالي', nameEn: "Men's Cuts" },
  { id: 'women_hair', nameAr: 'تسريحات نسائية', nameEn: "Women's Hair" },
  { id: 'shaving', nameAr: 'حلاقة ذقن', nameEn: 'Shaving' },
  { id: 'skincare', nameAr: 'عناية بالبشرة', nameEn: 'Skincare' },
  { id: 'makeup', nameAr: 'مكياج', nameEn: 'Makeup' },
  { id: 'henna', nameAr: 'نقش حناء', nameEn: 'Henna' },
  { id: 'embroidery_hand', nameAr: 'تطريز يدوي', nameEn: 'Hand Embroidery' },
  { id: 'embroidery_machine', nameAr: 'تطريز آلي', nameEn: 'Machine Embroidery' },
  { id: 'tailoring', nameAr: 'خياطة', nameEn: 'Tailoring' },
  { id: 'alterations', nameAr: 'تصليحات', nameEn: 'Alterations' },
  { id: 'menswear', nameAr: 'ملابس رجالية', nameEn: "Men's Wear" },
  { id: 'womenswear', nameAr: 'ملابس نسائية', nameEn: "Women's Wear" },
  { id: 'childrenswear', nameAr: 'ملابس أطفال', nameEn: "Children's Wear" },
  { id: 'traditional_dress', nameAr: 'زي تقليدي', nameEn: 'Traditional Dress' },
  { id: 'leather_goods', nameAr: 'منتجات جلدية', nameEn: 'Leather Goods' },
  { id: 'perfume', nameAr: 'عطور', nameEn: 'Perfume' },
  { id: 'incense', nameAr: 'بخور', nameEn: 'Incense' },
  { id: 'cosmetics', nameAr: 'مستحضرات تجميل', nameEn: 'Cosmetics' },
  { id: 'natural_soap', nameAr: 'صابون طبيعي', nameEn: 'Natural Soap' },
  { id: 'catering', nameAr: 'تموين', nameEn: 'Catering' },
  { id: 'pastry', nameAr: 'معجنات', nameEn: 'Pastry' },
  { id: 'sweets', nameAr: 'حلويات', nameEn: 'Sweets' },
  { id: 'coffee', nameAr: 'قهوة', nameEn: 'Coffee' },
  { id: 'grill', nameAr: 'مشويات', nameEn: 'Grill' },
  { id: 'seafood', nameAr: 'بحري', nameEn: 'Seafood' },
  { id: 'healthy_food', nameAr: 'أكل صحي', nameEn: 'Healthy Food' },
  { id: 'livestock', nameAr: 'مواشٍ', nameEn: 'Livestock', aliases: ['أغنام', 'إبل'] },
  { id: 'poultry', nameAr: 'دواجن', nameEn: 'Poultry' },
  { id: 'falconry', nameAr: 'صقور', nameEn: 'Falconry' },
  { id: 'horses', nameAr: 'خيول', nameEn: 'Horses' },
  { id: 'fishing', nameAr: 'صيد', nameEn: 'Fishing' },
  { id: 'farming', nameAr: 'زراعة', nameEn: 'Farming' },
  { id: 'honey', nameAr: 'عسل', nameEn: 'Honey' },
  { id: 'dates', nameAr: 'تمور', nameEn: 'Dates' },
  { id: 'plants', nameAr: 'نباتات', nameEn: 'Plants' },
  { id: 'recitation_tajweed', nameAr: 'تجويد', nameEn: 'Tajweed' },
  { id: 'recitation_maqamat', nameAr: 'مقامات', nameEn: 'Maqamat' },
  { id: 'storytelling_children', nameAr: 'أطفال', nameEn: "Children's Stories" },
  { id: 'storytelling_heritage', nameAr: 'تراث', nameEn: 'Heritage Stories' },
  { id: 'drama_theater', nameAr: 'مسرح', nameEn: 'Theater' },
  { id: 'drama_tv', nameAr: 'تلفزيون', nameEn: 'TV Drama' },
  { id: 'comedy', nameAr: 'كوميديا', nameEn: 'Comedy' },
  { id: 'stunts', nameAr: 'استعراضات', nameEn: 'Stunts' },
  { id: 'sports_football', nameAr: 'كرة قدم', nameEn: 'Football' },
  { id: 'sports_basketball', nameAr: 'كرة سلة', nameEn: 'Basketball' },
  { id: 'sports_swimming', nameAr: 'سباحة', nameEn: 'Swimming' },
  { id: 'sports_martial', nameAr: 'فنون قتالية', nameEn: 'Martial Arts' },
  { id: 'sports_equestrian', nameAr: 'فروسية', nameEn: 'Equestrian' },
  { id: 'sports_gymnastics', nameAr: 'جمباز', nameEn: 'Gymnastics' },
  { id: 'sports_fitness', nameAr: 'لياقة بدنية', nameEn: 'Fitness' },
  { id: 'mentoring', nameAr: 'توجيه', nameEn: 'Mentoring' },
  { id: 'tutoring', nameAr: 'تدريس خصوصي', nameEn: 'Tutoring' },
  { id: 'curriculum', nameAr: 'تأليف مناهج', nameEn: 'Curriculum' },
  { id: 'language', nameAr: 'لغات', nameEn: 'Languages' },
  { id: 'religious', nameAr: 'علوم شرعية', nameEn: 'Religious Studies' },
  { id: 'stem', nameAr: 'علوم وتقنية', nameEn: 'STEM' },
  { id: 'early_childhood', nameAr: 'طفولة مبكرة', nameEn: 'Early Childhood' },
  { id: 'strategy', nameAr: 'استراتيجية', nameEn: 'Strategy' },
  { id: 'operations', nameAr: 'عمليات', nameEn: 'Operations' },
  { id: 'hr', nameAr: 'موارد بشرية', nameEn: 'Human Resources' },
  { id: 'legal', nameAr: 'استشارات قانونية', nameEn: 'Legal Advisory' },
  { id: 'realestate', nameAr: 'عقارات', nameEn: 'Real Estate' },
  { id: 'investment', nameAr: 'استثمار', nameEn: 'Investment' },
  { id: 'marketing', nameAr: 'تسويق', nameEn: 'Marketing' },
  { id: 'logistics', nameAr: 'لوجستيات', nameEn: 'Logistics' },
  { id: 'quality', nameAr: 'جودة', nameEn: 'Quality' },
  { id: 'safety', nameAr: 'سلامة', nameEn: 'Safety' },
  { id: 'programming', nameAr: 'برمجة', nameEn: 'Programming' },
  { id: 'video_production', nameAr: 'إنتاج فيديو', nameEn: 'Video Production' },
  { id: 'video_editing', nameAr: 'مونتاج فيديو', nameEn: 'Video Editing' },
  { id: 'voice_recitation', nameAr: 'تلاوة وإنشاد', nameEn: 'Recitation' },
  { id: 'nursing_care', nameAr: 'تمريض ورعاية', nameEn: 'Nursing Care' },
  { id: 'butchery', nameAr: 'جزارة ولحوم', nameEn: 'Butchery' },
  { id: 'training_delivery', nameAr: 'تقديم تدريب', nameEn: 'Training Delivery' },
  { id: 'project_coordination', nameAr: 'تنسيق مشاريع', nameEn: 'Project Coordination' },
  { id: 'volunteer_coordination', nameAr: 'تنسيق متطوعين', nameEn: 'Volunteer Coordination' },
  { id: 'procurement', nameAr: 'مشتريات', nameEn: 'Procurement' },
  // Metal, electrical, doors, solar
  { id: 'metal_fabrication', nameAr: 'تشكيل المعادن', nameEn: 'Metal Fabrication' },
  { id: 'metal_finishing', nameAr: 'تشطيب المعادن', nameEn: 'Metal Finishing' },
  { id: 'escalators', nameAr: 'سلالم كهربائية', nameEn: 'Escalators' },
  { id: 'elevators', nameAr: 'مصاعد', nameEn: 'Elevators' },
  { id: 'automatic_doors', nameAr: 'أبواب أوتوماتيكية', nameEn: 'Automatic Doors' },
  { id: 'sliding_doors', nameAr: 'أبواب انزلاقية', nameEn: 'Sliding Doors' },
  { id: 'revolving_doors', nameAr: 'أبواب دوارة', nameEn: 'Revolving Doors' },
  { id: 'roller_shutters', nameAr: 'شتر سحّاب', nameEn: 'Roller Shutters', aliases: ['رول'] },
  { id: 'security_shutters', nameAr: 'شتر أمني', nameEn: 'Security Shutters' },
  { id: 'aluminum_shutters', nameAr: 'شتر ألمنيوم', nameEn: 'Aluminum Shutters' },
  { id: 'solar_panels', nameAr: 'ألواح شمسية', nameEn: 'Solar Panels' },
  { id: 'solar_water_heaters', nameAr: 'سخانات شمسية', nameEn: 'Solar Water Heaters' },
  { id: 'off_grid_systems', nameAr: 'أنظمة منفصلة عن الشبكة', nameEn: 'Off-Grid Systems' },
  // Vehicles & security tech
  { id: 'vehicle_gps', nameAr: 'GPS مركبات', nameEn: 'Vehicle GPS', aliases: ['جي بي اس'] },
  { id: 'fleet_tracking', nameAr: 'تتبع الأساطيل', nameEn: 'Fleet Tracking' },
  { id: 'navigation_systems', nameAr: 'أنظمة ملاحة', nameEn: 'Navigation Systems' },
  { id: 'cctv', nameAr: 'كاميرات مراقبة', nameEn: 'CCTV', aliases: ['سي سي تي في'] },
  { id: 'ip_cameras', nameAr: 'كاميرات IP', nameEn: 'IP Cameras' },
  { id: 'security_alarms', nameAr: 'أنظمة إنذار', nameEn: 'Security Alarms' },
  { id: 'access_control', nameAr: 'التحكم بالدخول', nameEn: 'Access Control' },
  // Paperwork & government
  { id: 'government_procedures', nameAr: 'إجراءات حكومية', nameEn: 'Government Procedures' },
  { id: 'commercial_licenses', nameAr: 'تراخيص تجارية', nameEn: 'Commercial Licenses' },
  { id: 'residency_services', nameAr: 'خدمات الإقامة', nameEn: 'Residency Services' },
  { id: 'company_registration', nameAr: 'تأسيس شركات', nameEn: 'Company Registration' },
  // Traditional & agriculture
  { id: 'hookah_manufacturing', nameAr: 'صناعة الأرجيلة', nameEn: 'Hookah Manufacturing', aliases: ['شيشة'] },
  { id: 'hookah_accessories', nameAr: 'مستلزمات الأرجيلة', nameEn: 'Hookah Accessories' },
  { id: 'aquarium_setup', nameAr: 'تركيب أحواض', nameEn: 'Aquarium Setup' },
  { id: 'marine_tanks', nameAr: 'أحواض مياه مالحة', nameEn: 'Marine Tanks' },
  { id: 'freshwater_tanks', nameAr: 'أحواض مياه عذبة', nameEn: 'Freshwater Tanks' },
  { id: 'ornamental_birds', nameAr: 'طيور زينة', nameEn: 'Ornamental Birds' },
  { id: 'animal_feed', nameAr: 'أعلاف حيوانية', nameEn: 'Animal Feed' },
  { id: 'poultry_feed', nameAr: 'أعلاف دواجن', nameEn: 'Poultry Feed' },
  { id: 'livestock_feed', nameAr: 'أعلاف مواشٍ', nameEn: 'Livestock Feed' },
  { id: 'horse_care', nameAr: 'رعاية الخيول', nameEn: 'Horse Care' },
  { id: 'stable_management', nameAr: 'إدارة إسطبلات', nameEn: 'Stable Management' },
  { id: 'camel_care', nameAr: 'رعاية الإبل', nameEn: 'Camel Care' },
  { id: 'camel_racing', nameAr: 'سباقات الهجن', nameEn: 'Camel Racing' },
  // Care & domestic
  { id: 'home_nursing', nameAr: 'تمريض منزلي', nameEn: 'Home Nursing' },
  { id: 'elderly_nursing', nameAr: 'تمريض كبار السن', nameEn: 'Elderly Nursing' },
  { id: 'pediatric_nursing', nameAr: 'تمريض أطفال', nameEn: 'Pediatric Nursing' },
  { id: 'domestic_cleaning', nameAr: 'تنظيف منزلي', nameEn: 'Domestic Cleaning' },
  { id: 'childcare', nameAr: 'رعاية أطفال', nameEn: 'Childcare' },
  { id: 'nursery', nameAr: 'حضانة', nameEn: 'Nursery' },
  { id: 'home_security', nameAr: 'أمن منزلي', nameEn: 'Home Security' },
  { id: 'gatekeeping', nameAr: 'بوابة / نطور', nameEn: 'Gatekeeping' },
  { id: 'personal_driving', nameAr: 'قيادة خاصة', nameEn: 'Personal Driving' },
  { id: 'airport_transfers', nameAr: 'توصيل المطار', nameEn: 'Airport Transfers' },
  { id: 'car_rental', nameAr: 'تأجير سيارات', nameEn: 'Car Rental' },
  { id: 'fleet_rental', nameAr: 'تأجير أساطيل', nameEn: 'Fleet Rental' },
  // Events & religious
  { id: 'wedding_planning', nameAr: 'تخطيط أفراح', nameEn: 'Wedding Planning' },
  { id: 'wedding_coordination', nameAr: 'تنسيق أفراح', nameEn: 'Wedding Coordination' },
  { id: 'ramadan_drum', nameAr: 'مسحراتي / طبول رمضان', nameEn: 'Ramadan Drum' },
  { id: 'neighborhood_calls', nameAr: 'جولة الأحياء', nameEn: 'Neighborhood Calls' },
  { id: 'hadith', nameAr: 'حديث شريف', nameEn: 'Hadith' },
  { id: 'sunnah', nameAr: 'سنة نبوية', nameEn: 'Sunnah' },
  // Engineering & admin
  { id: 'civil_engineering', nameAr: 'هندسة مدنية', nameEn: 'Civil Engineering' },
  { id: 'electrical_engineering', nameAr: 'هندسة كهربائية', nameEn: 'Electrical Engineering' },
  { id: 'mechanical_engineering', nameAr: 'هندسة ميكانيكية', nameEn: 'Mechanical Engineering' },
  { id: 'architectural_engineering', nameAr: 'هندسة معمارية', nameEn: 'Architectural Engineering' },
  { id: 'structural_engineering', nameAr: 'هندسة إنشائية', nameEn: 'Structural Engineering' },
  { id: 'office_management', nameAr: 'إدارة مكاتب', nameEn: 'Office Management' },
  { id: 'administrative_operations', nameAr: 'عمليات إدارية', nameEn: 'Administrative Operations' },
  { id: 'facilities_management', nameAr: 'إدارة مرافق', nameEn: 'Facilities Management' },
  // Elevators & escalators
  { id: 'elevator_installation', nameAr: 'تركيب مصاعد', nameEn: 'Elevator Installation' },
  { id: 'elevator_maintenance', nameAr: 'صيانة مصاعد', nameEn: 'Elevator Maintenance' },
  { id: 'elevator_faults', nameAr: 'أعطال مصاعد', nameEn: 'Elevator Faults' },
  { id: 'elevator_control', nameAr: 'كنترول مصاعد', nameEn: 'Elevator Control' },
  { id: 'elevator_doors', nameAr: 'أبواب مصاعد', nameEn: 'Elevator Doors' },
  { id: 'elevator_cabins', nameAr: 'كبائن مصاعد', nameEn: 'Elevator Cabins' },
  { id: 'elevator_hydraulic', nameAr: 'مصاعد هيدروليك', nameEn: 'Hydraulic Elevators' },
  { id: 'home_elevators', nameAr: 'مصاعد منزلية', nameEn: 'Home Elevators' },
  { id: 'cargo_elevators', nameAr: 'مصاعد بضائع', nameEn: 'Cargo Elevators' },
  { id: 'car_elevators', nameAr: 'مصاعد سيارات', nameEn: 'Car Elevators' },
  { id: 'restaurant_elevators', nameAr: 'مصاعد مطاعم', nameEn: 'Restaurant Elevators' },
  { id: 'escalator_installation', nameAr: 'تركيب سلالم كهربائية', nameEn: 'Escalator Installation' },
  { id: 'escalator_maintenance', nameAr: 'صيانة سلالم كهربائية', nameEn: 'Escalator Maintenance' },
  { id: 'escalator_faults', nameAr: 'أعطال سلالم كهربائية', nameEn: 'Escalator Faults' },
  { id: 'escalator_control', nameAr: 'كنترول سلالم كهربائية', nameEn: 'Escalator Control' },
  { id: 'moving_walkway_installation', nameAr: 'تركيب ممرات متحركة', nameEn: 'Moving Walkway Installation' },
  { id: 'moving_walkway_maintenance', nameAr: 'صيانة ممرات متحركة', nameEn: 'Moving Walkway Maintenance' },
  { id: 'moving_walkway_faults', nameAr: 'أعطال ممرات متحركة', nameEn: 'Moving Walkway Faults' },
  { id: 'moving_walkway_control', nameAr: 'كنترول ممرات متحركة', nameEn: 'Moving Walkway Control' },
  // Fire alarm
  { id: 'fire_alarm_panels', nameAr: 'لوحات إنذار حريق', nameEn: 'Fire Alarm Panels' },
  { id: 'smoke_detectors', nameAr: 'كواشف دخان', nameEn: 'Smoke Detectors' },
  { id: 'heat_detectors', nameAr: 'كواشف حرارة', nameEn: 'Heat Detectors' },
  { id: 'sirens', nameAr: 'صفارات إنذار', nameEn: 'Sirens' },
  { id: 'addressable_systems', nameAr: 'أنظمة Addressable', nameEn: 'Addressable Systems' },
  { id: 'conventional_systems', nameAr: 'أنظمة Conventional', nameEn: 'Conventional Systems' },
  { id: 'fire_alarm_testing', nameAr: 'اختبار وصيانة إنذار حريق', nameEn: 'Fire Alarm Testing & Maintenance' },
  // Smart access
  { id: 'smart_locks', nameAr: 'أقفال ذكية', nameEn: 'Smart Locks' },
  { id: 'electronic_locks', nameAr: 'أقفال إلكترونية', nameEn: 'Electronic Locks' },
  { id: 'keyless_entry', nameAr: 'دخول بدون مفتاح', nameEn: 'Keyless Entry' },
  { id: 'card_readers', nameAr: 'قارئات بطاقات', nameEn: 'Card Readers' },
  { id: 'barriers', nameAr: 'حواجز دخول', nameEn: 'Access Barriers' },
  { id: 'turnstiles', nameAr: 'بوابات دوارة', nameEn: 'Turnstiles' },
  { id: 'biometric_access', nameAr: 'دخول بيومتري', nameEn: 'Biometric Access' },
  { id: 'fingerprint', nameAr: 'بصمة إصبع', nameEn: 'Fingerprint Recognition' },
  { id: 'face_recognition', nameAr: 'تعرف على الوجه', nameEn: 'Face Recognition' },
  { id: 'palm_recognition', nameAr: 'تعرف على راحة اليد', nameEn: 'Palm Recognition' },
  // Security services
  { id: 'security_guarding', nameAr: 'حراسة أمنية', nameEn: 'Security Guarding' },
  { id: 'facility_security', nameAr: 'أمن منشآت', nameEn: 'Facility Security' },
  { id: 'security_supervision', nameAr: 'إشراف أمني', nameEn: 'Security Supervision' },
  { id: 'security_patrol', nameAr: 'دوريات أمنية', nameEn: 'Security Patrol' },
  { id: 'crowd_control', nameAr: 'ضبط الجمهور', nameEn: 'Crowd Control' },
  // Camel care
  { id: 'camel_training', nameAr: 'تدريب الإبل', nameEn: 'Camel Training' },
  { id: 'camel_grooming', nameAr: 'تهذيب الإبل', nameEn: 'Camel Grooming' },
  // Jewelry, watches, locks
  { id: 'goldsmithing', nameAr: 'صياغة ذهب', nameEn: 'Goldsmithing' },
  { id: 'silversmithing', nameAr: 'صياغة فضة', nameEn: 'Silversmithing' },
  { id: 'jewelry_making', nameAr: 'صناعة مجوهرات', nameEn: 'Jewelry Making' },
  { id: 'jewelry_repair', nameAr: 'إصلاح مجوهرات', nameEn: 'Jewelry Repair' },
  { id: 'watch_repair', nameAr: 'إصلاح ساعات', nameEn: 'Watch Repair' },
  { id: 'key_cutting', nameAr: 'قص مفاتيح', nameEn: 'Key Cutting' },
  { id: 'lock_repair', nameAr: 'إصلاح أقفال', nameEn: 'Lock Repair' },
  { id: 'lock_installation', nameAr: 'تركيب أقفال', nameEn: 'Lock Installation' },
  { id: 'car_key_programming', nameAr: 'برمجة مفاتيح سيارات', nameEn: 'Car Key Programming' },
  // Healthcare
  { id: 'pharmacy', nameAr: 'صيدلة', nameEn: 'Pharmacy' },
  { id: 'radiology', nameAr: 'أشعة', nameEn: 'Radiology' },
  { id: 'laboratory', nameAr: 'مختبر', nameEn: 'Laboratory' },
  { id: 'physiotherapy', nameAr: 'علاج طبيعي', nameEn: 'Physiotherapy' },
  { id: 'dietetics', nameAr: 'تغذية علاجية', nameEn: 'Dietetics' },
  { id: 'healthcare_assisting', nameAr: 'مساعدة صحية', nameEn: 'Healthcare Assisting' },
];

export function getSpecialization(id: string): SpecializationOption | undefined {
  return specializations.find((s) => s.id === id);
}
