export function render(container, lang = "ar") {
  container.innerHTML = `<section id="contact" class="section"><h2 class="section__title" data-i18n="sectionContact">Contact</h2><p class="lang-en" style="margin-bottom: var(--space-8);"></p><p class="lang-ar" style="margin-bottom: var(--space-8);">نود أن نسمع منك. تواصل معنا للشراكات أو الاستشارات أو
استفسارات العضوية.</p><div class="direct-contact-box"><h4 class="lang-en"></h4><h4 class="lang-ar">الاتصال المباشر — للتواصل فقط</h4><p class="lang-en" style="margin-bottom: var(--space-4); font-size: 0.9rem;"></p><p class="lang-ar" style="margin-bottom: var(--space-4); font-size: 0.9rem;">البريد والهاتف للتواصل المباشر مع
الصندوق.</p><dl class="direct-contact-dl"><dt class="lang-en"></dt><dt class="lang-ar">البريد الإلكتروني</dt><dd><a href="mailto:info@iiffund.com" id="contact-email">info@iiffund.com</a></dd><dt class="lang-en"></dt><dt class="lang-ar">رقم الهاتف</dt><dd id="contact-phone">—</dd></dl></div><div class="contact-grid"><div class="contact-info"><h4 class="lang-en"></h4><h4 class="lang-ar">المقر الرئيسي</h4><p>11 RUE de Magdebourg<br />75116 Paris 16e Arrondissement<br />FRANCE</p><p><span class="lang-en"></span><span class="lang-ar">البريد (للتواصل):</span><a
href="mailto:info@iiffund.com">info@iiffund.com</a></p><p><span class="lang-en"></span><span class="lang-ar">الهاتف:</span><span
id="contact-phone-office">—</span></p><h4 class="lang-en" style="margin-top: var(--space-6);"></h4><h4 class="lang-ar" style="margin-top: var(--space-6);">الفرع</h4><p>Texas · Houston · Sugar Land</p><p class="lang-en"></p><p class="lang-ar">ساعات العمل: الاثنين–الجمعة</p></div><p class="location-verify-note lang-en">We may record your location at the time of contact to verify the
authenticity of your interaction.</p><p class="location-verify-note lang-ar">قد نسجّل موقعك وقت التواصل للتحقق من صدق تعاملك.</p><form id="form-contact" action="#" method="post"><label for="name" class="lang-en"></label><label for="name" class="lang-ar">الاسم</label><input type="text" id="name" name="name" required maxlength="200" autocomplete="name" /><label for="email" class="lang-en"></label><label for="email" class="lang-ar">البريد الإلكتروني</label><input type="email" id="email" name="email" required maxlength="254" autocomplete="email" /><label for="msg" class="lang-en"></label><label for="msg" class="lang-ar">الرسالة</label><textarea id="msg" name="message" required maxlength="5000"></textarea><div class="kyc-block"><h4 class="kyc-block__title lang-en">Know Your Customer (KYC)</h4><h4 class="kyc-block__title lang-ar">اعرف عميلك</h4><p class="kyc-block__intro lang-en">Required for compliance. Please provide identification and address
details.</p><p class="kyc-block__intro lang-ar">مطلوب للامتثال. يرجى تقديم بيانات الهوية والعنوان.</p><div class="form-row"><div class="form-group"><label for="contact-kyc-dob"><span class="lang-en"></span><span class="lang-ar">تاريخ
الميلاد</span></label><input type="date" id="contact-kyc-dob" name="kyc_dob" required /></div><div class="form-group"><label for="contact-kyc-nationality"><span class="lang-en"></span><span
class="lang-ar">الجنسية</span></label><select id="contact-kyc-nationality" name="kyc_nationality" required><option value="">— Select / اختر —</option><option value="SA">Saudi Arabia</option><option value="AE">United Arab Emirates</option><option value="EG">Egypt</option><option value="JO">Jordan</option><option value="FR">France</option><option value="US">United States</option><option value="GB">United Kingdom</option><option value="OTHER">Other</option></select></div></div><div class="form-row"><div class="form-group"><label for="contact-kyc-id-type"><span class="lang-en"></span><span class="lang-ar">نوع
الوثيقة</span></label><select id="contact-kyc-id-type" name="kyc_id_type" required><option value="">— Select / اختر —</option><option value="passport">Passport / جواز سفر</option><option value="national_id">National ID / هوية وطنية</option><option value="other">Other / أخرى</option></select></div><div class="form-group"><label for="contact-kyc-id-number"><span class="lang-en"></span><span
class="lang-ar">رقم الوثيقة</span></label><input type="text" id="contact-kyc-id-number" name="kyc_id_number" required maxlength="80" /></div></div><div class="form-group"><label for="contact-kyc-address"><span class="lang-en"></span><span
class="lang-ar">العنوان</span></label><input type="text" id="contact-kyc-address" name="kyc_address" required maxlength="200" /></div><div class="form-row"><div class="form-group"><label for="contact-kyc-city"><span class="lang-en"></span><span
class="lang-ar">المدينة</span></label><input type="text" id="contact-kyc-city" name="kyc_city" required maxlength="100" /></div><div class="form-group"><label for="contact-kyc-postal"><span class="lang-en"></span><span
class="lang-ar">الرمز البريدي (اختياري)</span></label><input type="text" id="contact-kyc-postal" name="kyc_postal" maxlength="20" /></div></div><div class="form-group"><label for="contact-kyc-country"><span class="lang-en"></span><span
class="lang-ar">دولة الإقامة</span></label><select id="contact-kyc-country" name="kyc_country" required><option value="">— Select / اختر —</option></select></div><div class="form-group"><label for="contact-kyc-request"><span class="lang-en"></span><span
class="lang-ar">شرح تكلم عن طلبك</span></label><textarea id="contact-kyc-request" name="kyc_request" rows="3" maxlength="2000" placeholder=""></textarea></div></div><button type="submit" class="btn btn--primary lang-en">Send</button><button type="submit" class="btn btn--primary lang-ar">إرسال</button></form></div></div></section>`;
}
