export function render(container, lang = "ar") {
  container.innerHTML = `<section id="investor-registration" class="section"><div class="investor-registration"><span class="investor-registration__badge" data-i18n="invBadge">For investors</span><h3 data-i18n="invTitle">Investor registration</h3><p class="intro" data-i18n="invIntro">Join our network of institutional and qualified investors. Register to
receive curated opportunities, deal flow, and direct engagement with the Fund.</p><div class="investor-payment-box payment-method-box"><p class="payment-secure-badge lang-en">Secure &amp; regulated</p><p class="payment-secure-badge lang-ar">آمنة ونظامية</p><h4 class="lang-en"></h4><h4 class="lang-ar">طريقة الدفع — إضافة رأس المال</h4><p class="lang-en" style="margin-bottom: var(--space-4); font-size: 0.9rem;"></p><p class="lang-ar" style="margin-bottom: var(--space-4); font-size: 0.9rem;">لإضافة رأس المال كمستثمر، استخدم
الحساب البنكي الرسمي للصندوق أدناه. تحويلات فقط؛ تتم المعالجة وفقاً للأنظمة المعمول بها.</p><dl class="payment-method-dl"><dt class="lang-en"></dt><dt class="lang-ar">اسم الحساب</dt><dd id="investor-payment-account-name">—</dd><dt class="lang-en"></dt><dt class="lang-ar">رقم الحساب</dt><dd id="investor-payment-account-number">—</dd></dl><p class="payment-regulatory lang-en">Official account only. Data handled in strict confidence.</p><p class="payment-regulatory lang-ar">حساب رسمي فقط. معالجة البيانات بسرية تامة.</p><div class="payment-remember-wrap"><label class="payment-remember-label"><input type="checkbox" id="payment-remember-investor" /><span
class="lang-en"></span><span class="lang-ar">تذكر طريقة الدفع
للدفعات القادمة</span></label><p class="payment-saved-hint lang-en" id="payment-saved-hint-investor" hidden>Your saved payment method:
Bank transfer (official account).</p><p class="payment-saved-hint lang-ar" id="payment-saved-hint-investor-ar" hidden>طريقة الدفع المحفوظة: تحويل
بنكي (الحساب الرسمي).</p></div></div><form id="form-investor-registration" method="post" action="#"><div class="form-row"><div class="form-group"><label for="inv-name"><span class="lang-en"></span><span class="lang-ar">الاسم
الكامل / اسم الكيان</span></label><input type="text" id="inv-name" name="entity_name" required /></div><div class="form-group"><label for="inv-email"><span class="lang-en"></span><span class="lang-ar">البريد
الإلكتروني</span></label><input type="email" id="inv-email" name="email" required /></div></div><div class="form-row"><div class="form-group"><label for="inv-entity"><span class="lang-en"></span><span class="lang-ar">نوع
الكيان</span></label><select id="inv-entity" name="entity_type" required><option value="">— Select / اختر —</option><option value="state">State / Government / دولة / حكومة</option><option value="government_org">Government organizations / منظمات حكومية</option><option value="civil_society">Civil society organizations / منظمات أهلية</option><option value="associations">Associations (all types) / جمعيات بأنواعها</option><option value="company">Companies / شركات</option><option value="institution">Institutions / مؤسسات</option><option value="person">Individuals / أفراد</option></select></div><div class="form-group"><label for="inv-country"><span class="lang-en"></span><span class="lang-ar">الدولة</span></label><select id="inv-country" name="country" required><option value="">— Select country / اختر الدولة —</option><option value="SA">Saudi Arabia</option><option value="AE">United Arab Emirates</option><option value="BH">Bahrain</option><option value="KW">Kuwait</option><option value="OM">Oman</option><option value="QA">Qatar</option><option value="EG">Egypt</option><option value="JO">Jordan</option><option value="MA">Morocco</option><option value="TR">Turkey</option><option value="PK">Pakistan</option><option value="ID">Indonesia</option><option value="FR">France</option><option value="US">United States</option><option value="GB">United Kingdom</option><option value="DE">Germany</option><option value="CN">China</option><option value="OTHER">Other</option></select></div></div><div class="form-group"><label for="inv-focus"><span class="lang-en"></span><span class="lang-ar">مجال
الاستثمار (اختياري)</span></label><select id="inv-focus" name="investment_focus"><option value="">— Select / اختر —</option><option value="energy">Energy & Water</option><option value="health">Health & Education</option><option value="agriculture">Agriculture & Food Security</option><option value="tech">Technology & AI</option><option value="industry">Industry & Real Assets</option><option value="environment">Environment & Youth</option><option value="general">General / متعدد</option></select></div><div class="form-group"><label for="inv-msg"><span class="lang-en"></span><span class="lang-ar">رسالة
(اختياري)</span></label><textarea id="inv-msg" name="message" rows="3"
style="width:100%; padding:0.6rem 0.8rem; border-radius:8px; border:1px solid var(--color-border-subtle); background:rgba(255,255,255,0.04); color:var(--color-text-main); font-family:inherit;"></textarea></div><div class="kyc-block"><h4 class="kyc-block__title lang-en">Know Your Customer (KYC)</h4><h4 class="kyc-block__title lang-ar">اعرف عميلك</h4><p class="kyc-block__intro lang-en">Required for compliance. Please provide identification and address
details.</p><p class="kyc-block__intro lang-ar">مطلوب للامتثال. يرجى تقديم بيانات الهوية والعنوان.</p><div class="form-row"><div class="form-group"><label for="inv-kyc-dob"><span class="lang-en"></span><span class="lang-ar">تاريخ
الميلاد</span></label><input type="date" id="inv-kyc-dob" name="kyc_dob" required /></div><div class="form-group"><label for="inv-kyc-nationality"><span class="lang-en"></span><span
class="lang-ar">الجنسية</span></label><select id="inv-kyc-nationality" name="kyc_nationality" required><option value="">— Select / اختر —</option><option value="SA">Saudi Arabia</option><option value="AE">United Arab Emirates</option><option value="EG">Egypt</option><option value="JO">Jordan</option><option value="FR">France</option><option value="US">United States</option><option value="GB">United Kingdom</option><option value="OTHER">Other</option></select></div></div><div class="form-row"><div class="form-group"><label for="inv-kyc-id-type"><span class="lang-en"></span><span class="lang-ar">نوع
الوثيقة</span></label><select id="inv-kyc-id-type" name="kyc_id_type" required><option value="">— Select / اختر —</option><option value="passport">Passport / جواز سفر</option><option value="national_id">National ID / هوية وطنية</option><option value="other">Other / أخرى</option></select></div><div class="form-group"><label for="inv-kyc-id-number"><span class="lang-en"></span><span
class="lang-ar">رقم الوثيقة</span></label><input type="text" id="inv-kyc-id-number" name="kyc_id_number" required maxlength="80" /></div></div><div class="form-group"><label for="inv-kyc-address"><span class="lang-en"></span><span
class="lang-ar">العنوان</span></label><input type="text" id="inv-kyc-address" name="kyc_address" required maxlength="200" /></div><div class="form-row"><div class="form-group"><label for="inv-kyc-city"><span class="lang-en"></span><span class="lang-ar">المدينة</span></label><input type="text" id="inv-kyc-city" name="kyc_city" required maxlength="100" /></div><div class="form-group"><label for="inv-kyc-postal"><span class="lang-en"></span><span
class="lang-ar">الرمز البريدي (اختياري)</span></label><input type="text" id="inv-kyc-postal" name="kyc_postal" maxlength="20" /></div></div><div class="form-group"><label for="inv-kyc-country"><span class="lang-en"></span><span class="lang-ar">دولة
الإقامة</span></label><select id="inv-kyc-country" name="kyc_country" required><option value="">— Select / اختر —</option></select></div><div class="form-group"><label for="inv-kyc-request"><span class="lang-en"></span><span class="lang-ar">شرح
تكلم عن طلبك</span></label><textarea id="inv-kyc-request" name="kyc_request" rows="3" maxlength="2000" placeholder=""></textarea></div></div><button type="submit" class="btn btn--primary"><span class="lang-en"></span><span
class="lang-ar">تسجيل كمستثمر</span></button></form></div></section>`;
}
