export function render(container, lang = "ar") {
  container.innerHTML = `<section id="careers" class="section"><h2 class="section__title"><span class="lang-en"></span><span class="lang-ar">التوظيف</span></h2><p class="lang-en" style="margin-bottom: var(--space-6);"></p><p class="lang-ar" style="margin-bottom: var(--space-6);">انضم إلى صندوق الاستثمار الدولي. نرحب بالمرشحين المؤهلين
في المجال المالي والعمليات والامتثال وإدارة المشاريع. أرسل سيرتك الذاتية وسنتواصل معك عند توفر فرصة مناسبة.</p><div class="careers-box"><h3 class="lang-en"></h3><h3 class="lang-ar">التقديم / إرسال السيرة الذاتية</h3><form id="form-careers" class="careers-form"><div class="form-row"><div class="form-group"><label for="careers-name"><span class="lang-en"></span><span class="lang-ar">الاسم
الكامل</span></label><input type="text" id="careers-name" name="name" required maxlength="120" /></div><div class="form-group"><label for="careers-email"><span class="lang-en"></span><span class="lang-ar">البريد
الإلكتروني</span></label><input type="email" id="careers-email" name="email" required /></div></div><div class="form-row"><div class="form-group"><label for="careers-phone"><span class="lang-en"></span><span class="lang-ar">الهاتف
(اختياري)</span></label><input type="tel" id="careers-phone" name="phone" /></div><div class="form-group"><label for="careers-position"><span class="lang-en"></span><span
class="lang-ar">الوظيفة أو مجال الاهتمام</span></label><input type="text" id="careers-position" name="position" maxlength="200" placeholder="" /></div></div><div class="form-group"><label for="careers-message"><span class="lang-en"></span><span
class="lang-ar">خطاب تقديم أو ملاحظة (اختياري)</span></label><textarea id="careers-message" name="message" rows="4" maxlength="2000"></textarea></div><p class="careers-note lang-en">You can also send your CV directly to <a
href="mailto:info@iiffund.com">info@iiffund.com</a> with the subject line "Career application".</p><p class="careers-note lang-ar">يمكنك أيضاً إرسال سيرتك الذاتية إلى <a
href="mailto:info@iiffund.com">info@iiffund.com</a> مع وضع "طلب توظيف" في موضوع الرسالة.</p><div class="kyc-block"><h4 class="kyc-block__title lang-en">Know Your Customer (KYC)</h4><h4 class="kyc-block__title lang-ar">اعرف عميلك</h4><p class="kyc-block__intro lang-en">Required for compliance. Please provide identification and address
details.</p><p class="kyc-block__intro lang-ar">مطلوب للامتثال. يرجى تقديم بيانات الهوية والعنوان.</p><div class="form-row"><div class="form-group"><label for="careers-kyc-dob"><span class="lang-en"></span><span class="lang-ar">تاريخ
الميلاد</span></label><input type="date" id="careers-kyc-dob" name="kyc_dob" required /></div><div class="form-group"><label for="careers-kyc-nationality"><span class="lang-en"></span><span
class="lang-ar">الجنسية</span></label><select id="careers-kyc-nationality" name="kyc_nationality" required><option value="">— Select / اختر —</option><option value="SA">Saudi Arabia</option><option value="AE">United Arab Emirates</option><option value="EG">Egypt</option><option value="JO">Jordan</option><option value="FR">France</option><option value="US">United States</option><option value="GB">United Kingdom</option><option value="OTHER">Other</option></select></div></div><div class="form-row"><div class="form-group"><label for="careers-kyc-id-type"><span class="lang-en"></span><span class="lang-ar">نوع
الوثيقة</span></label><select id="careers-kyc-id-type" name="kyc_id_type" required><option value="">— Select / اختر —</option><option value="passport">Passport / جواز سفر</option><option value="national_id">National ID / هوية وطنية</option><option value="other">Other / أخرى</option></select></div><div class="form-group"><label for="careers-kyc-id-number"><span class="lang-en"></span><span
class="lang-ar">رقم الوثيقة</span></label><input type="text" id="careers-kyc-id-number" name="kyc_id_number" required maxlength="80" /></div></div><div class="form-group"><label for="careers-kyc-address"><span class="lang-en"></span><span
class="lang-ar">العنوان</span></label><input type="text" id="careers-kyc-address" name="kyc_address" required maxlength="200" /></div><div class="form-row"><div class="form-group"><label for="careers-kyc-city"><span class="lang-en"></span><span
class="lang-ar">المدينة</span></label><input type="text" id="careers-kyc-city" name="kyc_city" required maxlength="100" /></div><div class="form-group"><label for="careers-kyc-postal"><span class="lang-en"></span><span
class="lang-ar">الرمز البريدي (اختياري)</span></label><input type="text" id="careers-kyc-postal" name="kyc_postal" maxlength="20" /></div></div><div class="form-group"><label for="careers-kyc-country"><span class="lang-en"></span><span
class="lang-ar">دولة الإقامة</span></label><select id="careers-kyc-country" name="kyc_country" required><option value="">— Select / اختر —</option></select></div><div class="form-group"><label for="careers-kyc-request"><span class="lang-en"></span><span
class="lang-ar">شرح تكلم عن طلبك</span></label><textarea id="careers-kyc-request" name="kyc_request" rows="3" maxlength="2000" placeholder=""></textarea></div></div><button type="submit" class="btn btn--primary"><span class="lang-en"></span><span class="lang-ar">إرسال الطلب</span></button></form><div id="careers-success" class="careers-success" hidden aria-live="polite"><span class="lang-en"></span><span class="lang-ar">شكراً لك. تم استلام طلبك. سنتواصل معك في حال توافق الفرصة.</span></div></div></section>`;
}
