export function render(container, lang = "ar") {
  container.innerHTML = `<section id="feasibility-study" class="section"><h2 class="section__title"><span class="lang-en"></span><span
class="lang-ar">اطلب دراسة جدوى لمشروعك</span></h2><div id="feasibility-gate" class="feasibility-gate" role="alert" aria-live="polite"><h3 class="lang-en"></h3><h3 class="lang-ar">مرحباً بك — للأعضاء فقط</h3><p class="lang-en"></p><p class="lang-ar">طلب دراسة جدوى لمشروعك متاح لجميع الأعضاء بجميع درجات العضوية (تعاوني وبريميوم). إذا لم تكن
عضواً بعد، ندعوك للانضمام إلى الصندوق للاستفادة من هذه الخدمة وباقي المزايا.</p><a href="#membership" class="btn btn--primary" id="feasibility-gate-request-membership"><span class="lang-en"></span><span class="lang-ar">اطلب العضوية</span></a></div><div id="feasibility-member-box" class="feasibility-study-box" style="display: none;"><p class="lang-en" style="margin-bottom: var(--space-4);"></p><p class="lang-ar" style="margin-bottom: var(--space-4);">قدّم مشروعك ودراسة الجدوى. وضّح مشروعك في الحقل أدناه
وارفق مستندات الدراسة (PDF، Word، Excel، وغيرها).</p><form id="form-feasibility-study" method="post" action="#" enctype="multipart/form-data"><div class="form-group"><label for="feasibility-description"><span class="lang-en"></span><span class="lang-ar">وضّح مشروعك</span></label><textarea id="feasibility-description" name="project_description" required
placeholder="Describe the project, objectives, scope, and any relevant details for the feasibility study."></textarea></div><div class="kyc-block"><h4 class="kyc-block__title lang-en">Know Your Customer (KYC)</h4><h4 class="kyc-block__title lang-ar">اعرف عميلك</h4><p class="kyc-block__intro lang-en">Required for compliance. Please provide identification and address
details.</p><p class="kyc-block__intro lang-ar">مطلوب للامتثال. يرجى تقديم بيانات الهوية والعنوان.</p><div class="form-row"><div class="form-group"><label for="feas-kyc-dob"><span class="lang-en"></span><span class="lang-ar">تاريخ
الميلاد</span></label><input type="date" id="feas-kyc-dob" name="kyc_dob" required /></div><div class="form-group"><label for="feas-kyc-nationality"><span class="lang-en"></span><span
class="lang-ar">الجنسية</span></label><select id="feas-kyc-nationality" name="kyc_nationality" required><option value="">— Select / اختر —</option><option value="SA">Saudi Arabia</option><option value="AE">United Arab Emirates</option><option value="EG">Egypt</option><option value="JO">Jordan</option><option value="FR">France</option><option value="US">United States</option><option value="GB">United Kingdom</option><option value="OTHER">Other</option></select></div></div><div class="form-row"><div class="form-group"><label for="feas-kyc-id-type"><span class="lang-en"></span><span class="lang-ar">نوع
الوثيقة</span></label><select id="feas-kyc-id-type" name="kyc_id_type" required><option value="">— Select / اختر —</option><option value="passport">Passport / جواز سفر</option><option value="national_id">National ID / هوية وطنية</option><option value="other">Other / أخرى</option></select></div><div class="form-group"><label for="feas-kyc-id-number"><span class="lang-en"></span><span
class="lang-ar">رقم الوثيقة</span></label><input type="text" id="feas-kyc-id-number" name="kyc_id_number" required maxlength="80" /></div></div><div class="form-group"><label for="feas-kyc-address"><span class="lang-en"></span><span
class="lang-ar">العنوان</span></label><input type="text" id="feas-kyc-address" name="kyc_address" required maxlength="200" /></div><div class="form-row"><div class="form-group"><label for="feas-kyc-city"><span class="lang-en"></span><span class="lang-ar">المدينة</span></label><input type="text" id="feas-kyc-city" name="kyc_city" required maxlength="100" /></div><div class="form-group"><label for="feas-kyc-postal"><span class="lang-en"></span><span
class="lang-ar">الرمز البريدي (اختياري)</span></label><input type="text" id="feas-kyc-postal" name="kyc_postal" maxlength="20" /></div></div><div class="form-group"><label for="feas-kyc-country"><span class="lang-en"></span><span class="lang-ar">دولة
الإقامة</span></label><select id="feas-kyc-country" name="kyc_country" required><option value="">— Select / اختر —</option></select></div><div class="form-group"><label for="feas-kyc-request"><span class="lang-en"></span><span class="lang-ar">شرح
تكلم عن طلبك</span></label><textarea id="feas-kyc-request" name="kyc_request" rows="3" maxlength="2000" placeholder=""></textarea></div></div><div class="upload-zone" id="feasibility-upload-zone"><input type="file" id="feasibility-files" name="feasibility_files" multiple
accept=".pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.odt,.ods,.txt,.jpg,.jpeg,.png,.gif,.webp,.mp4,.webm,.mov" /><p class="lang-en"></p><p class="lang-ar">اسحب ملفات دراسة الجدوى هنا أو انقر للاختيار — مستندات، صور، فيديو</p><p class="upload-types lang-en">Accepted: PDF, Word, Excel, PowerPoint, ODT, ODS, TXT — Images: JPG, PNG,
GIF, WebP — Video: MP4, WebM, MOV (max 10 MB/file, 50 MB total)</p><p class="upload-types lang-ar">المقبول: PDF، Word، Excel، PowerPoint، ODT، ODS، TXT — صور: JPG، PNG، GIF،
WebP — فيديو: MP4، WebM، MOV (حد 10 ميجا/ملف، 50 ميجا إجمالي)</p></div><button type="submit" class="btn btn--primary" style="margin-top: var(--space-6);"><span class="lang-en"></span><span class="lang-ar">إرسال دراسة الجدوى</span></button></form></div></section>`;
}
