export function render(container, lang = "ar") {
  container.innerHTML = `<section id="upload-submit" class="section"><h2 class="section__title" data-i18n="sectionUpload">Upload documents & project description</h2><p class="lang-en" style="margin-bottom: var(--space-4);"></p><p class="lang-ar" style="margin-bottom: var(--space-8);">جميع الرفوعات تُستقبل بشكل آمن ولا <strong>يتاح الاطلاع
عليها إلا للإدارة</strong>. التوزيع على المختصين والإرسال يتم من لوحة التحكم.</p><div class="upload-submit-box" style="margin-top: 0; margin-bottom: var(--space-8);"><div class="project-description-wrap"><label for="project-description"><span class="lang-en"></span><span class="lang-ar">شرح عن المشروع (يستوعب 1000 حرف)</span></label><textarea id="project-description" name="project_description" form="form-upload-submit" maxlength="1000"
minlength="100" required data-i18n="projectDescPlaceholder"
placeholder="Describe the project, objectives, expected outcomes, or your investment interest. Up to 1000 characters. / اشرح المشروع أو اهتمامك الاستثماري. حتى 1000 حرف."
data-min-chars="100" data-max-chars="1000"></textarea><div class="char-counter" id="project-char-counter" aria-live="polite"></div></div></div><div class="upload-grid-four"><div class="card upload-type-card upload-type-card--docs"><h3 class="lang-en"></h3><h3 class="lang-ar">مستندات فقط</h3><p class="lang-en" style="font-size:0.9rem;"></p><p class="lang-ar" style="font-size:0.9rem;">PDF، Word، Excel، PowerPoint، ODT، TXT. حد 10 ميجا/ملف.</p><form class="upload-form" id="form-upload-docs" enctype="multipart/form-data"><div class="upload-zone upload-zone--docs"><input type="file" id="upload-docs" name="docs" multiple
accept=".pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.odt,.ods,.txt,.rtf" data-max-size="10485760" /><p class="lang-en"></p><p class="lang-ar">اسحب أو انقر — مستندات فقط</p></div><button type="submit" class="btn btn--primary btn--sm"><span class="lang-en"></span><span
class="lang-ar">إرسال المستندات</span></button></form></div><div class="card upload-type-card upload-type-card--images"><h3 class="lang-en"></h3><h3 class="lang-ar">صور فقط</h3><p class="lang-en" style="font-size:0.9rem;"></p><p class="lang-ar" style="font-size:0.9rem;">JPG، PNG، GIF، WebP. حد 10 ميجا/ملف.</p><form class="upload-form" id="form-upload-images" enctype="multipart/form-data"><div class="upload-zone upload-zone--images"><input type="file" id="upload-images" name="images" multiple accept=".jpg,.jpeg,.png,.gif,.webp"
data-max-size="10485760" /><p class="lang-en"></p><p class="lang-ar">اسحب أو انقر — صور فقط</p></div><button type="submit" class="btn btn--primary btn--sm"><span class="lang-en"></span><span
class="lang-ar">إرسال الصور</span></button></form></div><div class="card upload-type-card upload-type-card--video"><h3 class="lang-en"></h3><h3 class="lang-ar">فيديو فقط</h3><p class="lang-en" style="font-size:0.9rem;"></p><p class="lang-ar" style="font-size:0.9rem;">MP4، WebM، MOV. حد 50 ميجا/ملف.</p><form class="upload-form" id="form-upload-video" enctype="multipart/form-data"><div class="upload-zone upload-zone--video"><input type="file" id="upload-video" name="video" accept=".mp4,.webm,.mov" data-max-size="52428800" /><p class="lang-en"></p><p class="lang-ar">اختر ملف الفيديو</p></div><button type="submit" class="btn btn--primary btn--sm"><span class="lang-en"></span><span
class="lang-ar">إرسال الفيديو</span></button></form></div><div class="card upload-type-card upload-type-card--live"><h3 class="lang-en"></h3><h3 class="lang-ar">تصوير مباشر (صورة أو فيديو)</h3><p class="lang-en" style="font-size:0.9rem;"></p><p class="lang-ar" style="font-size:0.9rem;">استخدم الكاميرا للتصوير الآن. يُستقبل بشكل منفصل من الإدارة.</p><div class="live-capture-wrap"><div class="live-capture-preview" id="live-capture-preview"><video id="live-video" autoplay playsinline muted
style="display:none; width:100%; max-height:200px; background:#000;"></video><canvas id="live-canvas" style="display:none;"></canvas><p class="live-capture-placeholder lang-en" id="live-placeholder">Camera off</p><p class="live-capture-placeholder lang-ar" id="live-placeholder-ar">الكاميرا مغلقة</p></div><div class="live-capture-btns"><button type="button" class="btn btn--ghost btn--sm" id="live-start"><span class="lang-en"></span><span class="lang-ar">تشغيل الكاميرا</span></button><button type="button" class="btn btn--primary btn--sm" id="live-capture-photo" disabled><span
class="lang-en"></span><span class="lang-ar">التقاط صورة</span></button><button type="button" class="btn btn--primary btn--sm" id="live-capture-video" disabled><span
class="lang-en"></span><span class="lang-ar">تسجيل فيديو</span></button><button type="button" class="btn btn--ghost btn--sm" id="live-stop" disabled><span
class="lang-en"></span><span class="lang-ar">إيقاف</span></button></div><form id="form-upload-live" style="margin-top:var(--space-3);"><input type="hidden" id="live-capture-data" name="live_data" /><button type="submit" class="btn btn--primary btn--sm" id="live-submit-btn" disabled><span
class="lang-en"></span><span class="lang-ar">إرسال التصوير
للإدارة</span></button></form></div></div></div><div class="upload-submit-box" style="margin-top: var(--space-6);"><form id="form-upload-submit" method="post" action="#" enctype="multipart/form-data"><div class="kyc-block"><h4 class="kyc-block__title lang-en">Know Your Customer (KYC)</h4><h4 class="kyc-block__title lang-ar">اعرف عميلك</h4><p class="kyc-block__intro lang-en">Required for compliance. Please provide identification and address
details.</p><p class="kyc-block__intro lang-ar">مطلوب للامتثال. يرجى تقديم بيانات الهوية والعنوان.</p><div class="form-row"><div class="form-group"><label for="upload-kyc-dob"><span class="lang-en"></span><span class="lang-ar">تاريخ
الميلاد</span></label><input type="date" id="upload-kyc-dob" name="kyc_dob" required /></div><div class="form-group"><label for="upload-kyc-nationality"><span class="lang-en"></span><span
class="lang-ar">الجنسية</span></label><select id="upload-kyc-nationality" name="kyc_nationality" required><option value="">— Select / اختر —</option><option value="SA">Saudi Arabia</option><option value="AE">United Arab Emirates</option><option value="EG">Egypt</option><option value="JO">Jordan</option><option value="FR">France</option><option value="US">United States</option><option value="GB">United Kingdom</option><option value="OTHER">Other</option></select></div></div><div class="form-row"><div class="form-group"><label for="upload-kyc-id-type"><span class="lang-en"></span><span class="lang-ar">نوع
الوثيقة</span></label><select id="upload-kyc-id-type" name="kyc_id_type" required><option value="">— Select / اختر —</option><option value="passport">Passport / جواز سفر</option><option value="national_id">National ID / هوية وطنية</option><option value="other">Other / أخرى</option></select></div><div class="form-group"><label for="upload-kyc-id-number"><span class="lang-en"></span><span
class="lang-ar">رقم الوثيقة</span></label><input type="text" id="upload-kyc-id-number" name="kyc_id_number" required maxlength="80" /></div></div><div class="form-group"><label for="upload-kyc-address"><span class="lang-en"></span><span
class="lang-ar">العنوان</span></label><input type="text" id="upload-kyc-address" name="kyc_address" required maxlength="200" /></div><div class="form-row"><div class="form-group"><label for="upload-kyc-city"><span class="lang-en"></span><span
class="lang-ar">المدينة</span></label><input type="text" id="upload-kyc-city" name="kyc_city" required maxlength="100" /></div><div class="form-group"><label for="upload-kyc-postal"><span class="lang-en"></span><span
class="lang-ar">الرمز البريدي (اختياري)</span></label><input type="text" id="upload-kyc-postal" name="kyc_postal" maxlength="20" /></div></div><div class="form-group"><label for="upload-kyc-country"><span class="lang-en"></span><span
class="lang-ar">دولة الإقامة</span></label><select id="upload-kyc-country" name="kyc_country" required><option value="">— Select / اختر —</option></select></div><div class="form-group"><label for="upload-kyc-request"><span class="lang-en"></span><span
class="lang-ar">شرح تكلم عن طلبك</span></label><textarea id="upload-kyc-request" name="kyc_request" rows="3" maxlength="2000" placeholder=""></textarea></div></div><button type="submit" class="btn btn--primary" style="margin-top: var(--space-6);"
data-i18n="btnSubmitUpload">
Submit documents and description
</button></form></div></section>`;
}
