export function render(container, lang = "ar") {
  container.innerHTML = `<section id="user-dashboard" class="section"><h2 class="section__title"><span class="lang-en"></span><span class="lang-ar">ملفي
الشخصي</span></h2><p class="lang-en"></p><p class="lang-ar">إدارة معلوماتك الشخصية وتفضيلات التواصل. تحكم في كيفية تواصل الآخرين معك.</p><div class="user-dashboard-container" style="max-width: 800px; margin: 0 auto;"><div class="card" style="margin-bottom: var(--space-6);"><h3><span class="lang-en"></span><span class="lang-ar">معلومات الملف الشخصي</span></h3><div class="user-profile-info" id="user-profile-info"><div class="profile-photo-section"><div class="profile-photo" id="user-profile-photo"><div class="placeholder-avatar">👤</div></div><button type="button" class="btn btn--primary" id="change-photo-btn"><span class="lang-en"></span><span class="lang-ar">تغيير الصورة</span></button></div><div class="profile-details"><div class="form-group"><label><span class="lang-en"></span><span class="lang-ar">الاسم الكامل</span></label><input type="text" id="user-full-name" class="form-control" placeholder="Enter your name"></div><div class="form-group"><label><span class="lang-en"></span><span class="lang-ar">البريد الإلكتروني</span></label><input type="email" id="user-email" class="form-control" readonly></div><div class="form-group"><label><span class="lang-en"></span><span class="lang-ar">رقم الهاتف</span></label><input type="tel" id="user-phone" class="form-control" placeholder="+1234567890"></div><div class="form-group"><label><span class="lang-en"></span><span
class="lang-ar">الشركة/المنظمة</span></label><input type="text" id="user-company" class="form-control" placeholder="Your company name"></div><div class="form-group"><label><span class="lang-en"></span><span class="lang-ar">المنصب</span></label><input type="text" id="user-position" class="form-control" placeholder="Your position"></div></div></div></div><div class="card" style="margin-bottom: var(--space-6);"><h3><span class="lang-en"></span><span class="lang-ar">إعدادات خصوصية التواصل</span></h3><p class="lang-en"></p><p class="lang-ar">اختر كيف يمكن للآخرين التواصل معك عبر المنصة.</p><div class="privacy-settings"><div class="form-group"><label><span class="lang-en"></span><span class="lang-ar">رؤية معلومات
التواصل</span></label><select id="contact-visibility" class="form-control"><option value="all"><span class="lang-en"></span><span class="lang-ar">إظهار
جميع معلومات التواصل</span></option><option value="partial"><span class="lang-en"></span><span
class="lang-ar">إظهار البريد والهاتف فقط</span></option><option value="platform"><span class="lang-en"></span><span
class="lang-ar">التواصل عبر المنصة فقط</span></option><option value="none"><span class="lang-en"></span><span
class="lang-ar">إخفاء جميع معلومات التواصل</span></option></select></div><div class="form-group"><label><span class="lang-en"></span><span class="lang-ar">السماح بالرسائل
من</span></label><div class="checkbox-group"><label class="checkbox-label"><input type="checkbox" id="allow-admin" checked><span class="lang-en"></span><span class="lang-ar">مديرو المنصة</span></label><label class="checkbox-label"><input type="checkbox" id="allow-members"><span class="lang-en"></span><span class="lang-ar">الأعضاء الآخرون</span></label><label class="checkbox-label"><input type="checkbox" id="allow-public"><span class="lang-en"></span><span class="lang-ar">المستخدمون العامون</span></label></div></div></div></div><div class="card" style="margin-bottom: var(--space-6);"><h3><span class="lang-en"></span><span class="lang-ar">معلومات إضافية</span></h3><div class="form-group"><label><span class="lang-en"></span><span class="lang-ar">السيرة الذاتية/الوصف</span></label><textarea id="user-bio" class="form-control" rows="4" placeholder="Tell us about yourself..."></textarea></div><div class="form-group"><label><span class="lang-en"></span><span class="lang-ar">الموقع
الإلكتروني/LinkedIn</span></label><input type="url" id="user-website" class="form-control" placeholder="https://yourwebsite.com"></div><div class="form-group"><label><span class="lang-en"></span><span class="lang-ar">الموقع</span></label><input type="text" id="user-location" class="form-control" placeholder="City, Country"></div></div><div class="form-actions"><button type="button" class="btn btn--primary" id="save-profile-btn"><span class="lang-en"></span><span class="lang-ar">حفظ التغييرات</span></button><button type="button" class="btn btn--ghost" id="cancel-profile-btn"><span class="lang-en"></span><span class="lang-ar">إلغاء</span></button></div></div></section>`;
}
