export function render(container, lang = "ar") {
  container.innerHTML = `<section id="customer-experience" class="section"><h2 class="section__title"><span class="lang-en"></span><span class="lang-ar">أدوات تجربة
العملاء</span></h2><p class="lang-en" style="margin-bottom: var(--space-8);"></p><p class="lang-ar" style="margin-bottom: var(--space-8);">نستخدم التحليلات والإشعارات ونظام إدارة العلاقات لتقديم
خدمة أفضل للمستثمرين والمتابعة في التوقيت المناسب.</p><div class="grid-3"><div class="card cx-tool-card"><h3 class="lang-en"></h3><h3 class="lang-ar">تحليل سلوك المستخدم</h3><p class="lang-en"></p><p class="lang-ar">نرصد تفاعلك داخل الموقع فقط: الأقسام التي تزورها والمشاريع التي تهمك، لتقديم اقتراحات مخصصة
لك.</p><div id="suggested-for-you" class="suggested-for-you" aria-live="polite"></div></div><div class="card cx-tool-card"><h3 class="lang-en"></h3><h3 class="lang-ar">إشعارات الموقع</h3><p class="lang-en"></p><p class="lang-ar">تنبيهات مخصصة حسب ملفك واهتماماتك المسجلة. فعّل الإشعارات أدناه لاستقبال تنبيهات عند ظهور
فرص مناسبة.</p><div class="notification-prefs"><label class="notif-toggle"><input type="checkbox" id="notif-enable" /><span class="lang-en"></span><span class="lang-ar">تفعيل الإشعارات</span></label><p class="notif-note lang-en" style="font-size:0.85rem; margin-top: var(--space-2);">Preferences saved to
your profile. Notifications will be sent when the service is connected.</p><p class="notif-note lang-ar" style="font-size:0.85rem; margin-top: var(--space-2);">يتم حفظ التفضيلات في
ملفك. تُرسل الإشعارات عند ربط الخدمة.</p></div></div><div class="card cx-tool-card"><h3 class="lang-en"></h3><h3 class="lang-ar">نظام CRM متقدم</h3><p class="lang-en"></p><p class="lang-ar">بيانات المستثمر (الجوال، البريد) مربوطة بنظام خدمة العملاء ليذكّر فريقنا بالتواصل معك في
الأوقات المناسبة.</p><dl class="crm-contact-dl"><dt class="lang-en"></dt><dt class="lang-ar">جهة المتابعة للفريق</dt><dd><a href="tel:+966567566616">+966 56 756 6616</a></dd><dd><a href="mailto:talalkenani@gmail.com">talalkenani@gmail.com</a></dd></dl></div></div></section>`;
}
