export function render(container, lang = "ar") {
  container.innerHTML = `<section id="financing-request" class="section"><h2 class="section__title" data-i18n="sectionFinancing">Financing request</h2><p style="margin-bottom: var(--space-8);" data-i18n="finRequestIntro">Are you seeking financing for a project or
initiative? Submit your request. Our team will review and contact you.</p><div class="financing-request"><form id="form-financing-request" method="post" action="#"><div class="form-row"><div class="form-group"><label for="fin-name"><span class="lang-en"></span><span class="lang-ar">الاسم
الكامل / اسم الكيان</span></label><input type="text" id="fin-name" name="entity_name" required /></div><div class="form-group"><label for="fin-email"><span class="lang-en"></span><span class="lang-ar">البريد
الإلكتروني</span></label><input type="email" id="fin-email" name="email" required /></div></div><div class="form-row"><div class="form-group"><label for="fin-entity"><span class="lang-en"></span><span class="lang-ar">نوع
الكيان</span></label><select id="fin-entity" name="entity_type" required><option value="">— Select / اختر —</option><option value="state">State / Government / دولة / حكومة</option><option value="government_org">Government organizations / منظمات حكومية</option><option value="civil_society">Civil society organizations / منظمات أهلية</option><option value="associations">Associations (all types) / جمعيات بأنواعها</option><option value="company">Companies / شركات</option><option value="institution">Institutions / مؤسسات</option><option value="person">Individuals / أفراد</option></select></div><div class="form-group"><label for="fin-country"><span class="lang-en"></span><span class="lang-ar">الدولة</span></label><select id="fin-country" name="country" required><option value="">— Select country / اختر الدولة —</option><option value="SA">Saudi Arabia</option><option value="AE">United Arab Emirates</option><option value="BH">Bahrain</option><option value="KW">Kuwait</option><option value="OM">Oman</option><option value="QA">Qatar</option><option value="EG">Egypt</option><option value="JO">Jordan</option><option value="MA">Morocco</option><option value="TR">Turkey</option><option value="PK">Pakistan</option><option value="ID">Indonesia</option><option value="FR">France</option><option value="US">United States</option><option value="GB">United Kingdom</option><option value="OTHER">Other</option></select></div></div><div class="form-group"><label for="fin-project"><span class="lang-en"></span><span
class="lang-ar">المشروع / القطاع (اختياري)</span></label><input type="text" id="fin-project" name="project_sector" placeholder="e.g. Energy, Health, Agriculture" /></div><div class="form-group"><label for="fin-msg"><span class="lang-en"></span><span class="lang-ar">وصف
احتياجك التمويلي</span></label><textarea id="fin-msg" name="message" rows="4" required
style="width:100%; padding:0.6rem 0.8rem; border-radius:8px; border:1px solid var(--color-border-subtle); background:rgba(255,255,255,0.04); color:var(--color-text-main); font-family:inherit;"></textarea></div><div class="kyc-block"><h4 class="kyc-block__title lang-en">Know Your Customer (KYC)</h4><h4 class="kyc-block__title lang-ar">اعرف عميلك</h4><p class="kyc-block__intro lang-en">Required for compliance. Please provide identification and address
details.</p><p class="kyc-block__intro lang-ar">مطلوب للامتثال. يرجى تقديم بيانات الهوية والعنوان.</p><div class="form-row"><div class="form-group"><label for="fin-kyc-dob"><span class="lang-en"></span><span class="lang-ar">تاريخ
الميلاد</span></label><input type="date" id="fin-kyc-dob" name="kyc_dob" required /></div><div class="form-group"><label for="fin-kyc-nationality"><span class="lang-en"></span><span
class="lang-ar">الجنسية</span></label><select id="fin-kyc-nationality" name="kyc_nationality" required><option value="">— Select / اختر —</option><option value="SA">Saudi Arabia</option><option value="AE">United Arab Emirates</option><option value="EG">Egypt</option><option value="JO">Jordan</option><option value="FR">France</option><option value="US">United States</option><option value="GB">United Kingdom</option><option value="OTHER">Other</option></select></div></div><div class="form-row"><div class="form-group"><label for="fin-kyc-id-type"><span class="lang-en"></span><span class="lang-ar">نوع
الوثيقة</span></label><select id="fin-kyc-id-type" name="kyc_id_type" required><option value="">— Select / اختر —</option><option value="passport">Passport / جواز سفر</option><option value="national_id">National ID / هوية وطنية</option><option value="other">Other / أخرى</option></select></div><div class="form-group"><label for="fin-kyc-id-number"><span class="lang-en"></span><span
class="lang-ar">رقم الوثيقة</span></label><input type="text" id="fin-kyc-id-number" name="kyc_id_number" required maxlength="80" /></div></div><div class="form-group"><label for="fin-kyc-address"><span class="lang-en"></span><span
class="lang-ar">العنوان</span></label><input type="text" id="fin-kyc-address" name="kyc_address" required maxlength="200" /></div><div class="form-row"><div class="form-group"><label for="fin-kyc-city"><span class="lang-en"></span><span class="lang-ar">المدينة</span></label><input type="text" id="fin-kyc-city" name="kyc_city" required maxlength="100" /></div><div class="form-group"><label for="fin-kyc-postal"><span class="lang-en"></span><span
class="lang-ar">الرمز البريدي (اختياري)</span></label><input type="text" id="fin-kyc-postal" name="kyc_postal" maxlength="20" /></div></div><div class="form-group"><label for="fin-kyc-country"><span class="lang-en"></span><span class="lang-ar">دولة
الإقامة</span></label><select id="fin-kyc-country" name="kyc_country" required><option value="">— Select / اختر —</option></select></div><div class="form-group"><label for="fin-kyc-request"><span class="lang-en"></span><span class="lang-ar">شرح
تكلم عن طلبك</span></label><textarea id="fin-kyc-request" name="kyc_request" rows="3" maxlength="2000" placeholder=""></textarea></div></div><button type="submit" class="btn btn--primary"><span class="lang-en"></span><span
class="lang-ar">إرسال طلب التمويل</span></button></form></div></section>`;
}
