export function render(container, lang = "ar") {
  container.innerHTML = `<section id="membership" class="section"><h2 class="section__title" data-i18n="sectionMembership">Membership</h2><p class="lang-en" style="margin-bottom: var(--space-4);"></p><p class="lang-ar" style="margin-bottom: var(--space-4);">انضم إلى مجلس الأعمال الدولي للوصول إلى الشبكات العالمية
وتدفق الصفقات المختارة وفرص التنمية.</p><p class="lang-en" style="margin-bottom: var(--space-8); font-size: 0.95rem; color: var(--color-text-muted);"></p><p class="lang-ar" style="margin-bottom: var(--space-8); font-size: 0.95rem; color: var(--color-text-muted);"><strong>عضو متعاون:</strong> استخدام المميزات (رفع، ترجمة، تنزيل) مشروط بالاشتراك. <strong>143 دولار
سنوياً</strong> أو <strong>29 دولار شهرياً</strong>. المشترك يتحمل رسوم التحويل. <a href="#terms">الشروط</a>.
</p><div class="tiers"><div class="tier"><div class="tier__name">Silver — 2,143 USD</div><ul class="lang-en"></ul><ul class="lang-ar"><li>ميز الصفحات والخدمات — أدنى عضوية مميزة</li><li>الوصول للشبكة والنشرات</li><li>دعوات لفعاليات مختارة</li></ul><a href="#membership-request" class="btn btn--ghost lang-en">Apply</a><a href="#membership-request" class="btn btn--ghost lang-ar">تقدم</a></div><div class="tier tier--featured"><div class="tier__name">Gold — 3,143 USD</div><ul class="lang-en"></ul><ul class="lang-ar"><li>ميز الصفحات والخدمات — المستوى الأوسط</li><li>جميع مزايا الفضية</li><li>معاينات ومحاضرات المشاريع</li><li>استشارات ذات أولوية</li></ul><a href="#membership-request" class="btn btn--primary lang-en">Apply</a><a href="#membership-request" class="btn btn--primary lang-ar">تقدم</a></div><div class="tier"><div class="tier__name">Platinum — 4,143 USD</div><ul class="lang-en"></ul><ul class="lang-ar"><li>ميز الصفحات والخدمات — أعلى مستوى</li><li>مدير علاقات مخصص</li><li>تدفق صفقات مخصص وجولات</li><li>تعريفات استراتيجية</li></ul><a href="#membership-request" class="btn btn--ghost lang-en">Apply</a><a href="#membership-request" class="btn btn--ghost lang-ar">تقدم</a></div></div><div class="membership-request" id="membership-request"><h3 data-i18n="memRequestTitle">Request membership</h3><p style="margin-bottom: var(--space-6);" data-i18n="memRequestIntro">Submit your application to join the
International Business Council. Specify your entity type, country, and desired tier.</p><form id="form-membership-request" method="post" action="#"><div class="form-row"><div class="form-group"><label for="mem-name"><span class="lang-en"></span><span class="lang-ar">الاسم
الكامل / اسم الكيان</span></label><input type="text" id="mem-name" name="entity_name" required /></div><div class="form-group"><label for="mem-email"><span class="lang-en"></span><span class="lang-ar">البريد
الإلكتروني</span></label><input type="email" id="mem-email" name="email" required /></div></div><div class="form-row"><div class="form-group"><label for="mem-entity"><span class="lang-en"></span><span class="lang-ar">نوع
الكيان</span></label><select id="mem-entity" name="entity_type" required><option value="">— Select / اختر —</option><option value="state">State / Government / دولة / حكومة</option><option value="government_org">Government organizations / منظمات حكومية</option><option value="civil_society">Civil society organizations / منظمات أهلية</option><option value="associations">Associations (all types) / جمعيات بأنواعها</option><option value="company">Companies / شركات</option><option value="institution">Institutions / مؤسسات</option><option value="person">Individuals / أفراد</option></select></div><div class="form-group"><label for="mem-country"><span class="lang-en"></span><span class="lang-ar">الدولة</span></label><select id="mem-country" name="country" required><option value="">— Select country / اختر الدولة —</option><option value="SA">Saudi Arabia</option><option value="AE">United Arab Emirates</option><option value="BH">Bahrain</option><option value="KW">Kuwait</option><option value="OM">Oman</option><option value="QA">Qatar</option><option value="EG">Egypt</option><option value="JO">Jordan</option><option value="MA">Morocco</option><option value="TR">Turkey</option><option value="PK">Pakistan</option><option value="ID">Indonesia</option><option value="FR">France</option><option value="US">United States</option><option value="GB">United Kingdom</option><option value="OTHER">Other</option></select></div></div><div class="form-group"><label for="mem-tier"><span class="lang-en"></span><span class="lang-ar">مستوى
العضوية</span></label><select id="mem-tier" name="membership_tier" required><option value="">— Select / اختر —</option><option value="shared">Shared Member / عضو مشترك</option><option value="premium_2143">Silver — 2,143 USD / فضية</option><option value="premium_3143">Gold — 3,143 USD / ذهبية</option><option value="premium_4143">Platinum — 4,143 USD / بلاتينية</option></select></div><div class="form-group"><label for="mem-msg"><span class="lang-en"></span><span class="lang-ar">رسالة
(اختياري)</span></label><textarea id="mem-msg" name="message" rows="4"
style="width:100%; padding:0.6rem 0.8rem; border-radius:8px; border:1px solid var(--color-border-subtle); background:rgba(255,255,255,0.04); color:var(--color-text-main); font-family:inherit;"></textarea></div><div class="kyc-block"><h4 class="kyc-block__title lang-en">Know Your Customer (KYC)</h4><h4 class="kyc-block__title lang-ar">اعرف عميلك</h4><p class="kyc-block__intro lang-en">Required for compliance. Please provide identification and address
details.</p><p class="kyc-block__intro lang-ar">مطلوب للامتثال. يرجى تقديم بيانات الهوية والعنوان.</p><div class="form-row"><div class="form-group"><label for="mem-kyc-dob"><span class="lang-en"></span><span class="lang-ar">تاريخ
الميلاد</span></label><input type="date" id="mem-kyc-dob" name="kyc_dob" required /></div><div class="form-group"><label for="mem-kyc-nationality"><span class="lang-en"></span><span
class="lang-ar">الجنسية</span></label><select id="mem-kyc-nationality" name="kyc_nationality" required><option value="">— Select / اختر —</option><option value="SA">Saudi Arabia</option><option value="AE">United Arab Emirates</option><option value="EG">Egypt</option><option value="JO">Jordan</option><option value="FR">France</option><option value="US">United States</option><option value="GB">United Kingdom</option><option value="OTHER">Other</option></select></div></div><div class="form-row"><div class="form-group"><label for="mem-kyc-id-type"><span class="lang-en"></span><span class="lang-ar">نوع
الوثيقة</span></label><select id="mem-kyc-id-type" name="kyc_id_type" required><option value="">— Select / اختر —</option><option value="passport">Passport / جواز سفر</option><option value="national_id">National ID / هوية وطنية</option><option value="other">Other / أخرى</option></select></div><div class="form-group"><label for="mem-kyc-id-number"><span class="lang-en"></span><span
class="lang-ar">رقم الوثيقة</span></label><input type="text" id="mem-kyc-id-number" name="kyc_id_number" required maxlength="80" /></div></div><div class="form-group"><label for="mem-kyc-address"><span class="lang-en"></span><span
class="lang-ar">العنوان</span></label><input type="text" id="mem-kyc-address" name="kyc_address" required maxlength="200" /></div><div class="form-row"><div class="form-group"><label for="mem-kyc-city"><span class="lang-en"></span><span class="lang-ar">المدينة</span></label><input type="text" id="mem-kyc-city" name="kyc_city" required maxlength="100" /></div><div class="form-group"><label for="mem-kyc-postal"><span class="lang-en"></span><span
class="lang-ar">الرمز البريدي (اختياري)</span></label><input type="text" id="mem-kyc-postal" name="kyc_postal" maxlength="20" /></div></div><div class="form-group"><label for="mem-kyc-country"><span class="lang-en"></span><span class="lang-ar">دولة
الإقامة</span></label><select id="mem-kyc-country" name="kyc_country" required><option value="">— Select / اختر —</option></select></div><div class="form-group"><label for="mem-kyc-request"><span class="lang-en"></span><span class="lang-ar">شرح
تكلم عن طلبك</span></label><textarea id="mem-kyc-request" name="kyc_request" rows="3" maxlength="2000" placeholder=""></textarea></div></div><button type="submit" class="btn btn--primary"><span class="lang-en"></span><span
class="lang-ar">إرسال طلب العضوية</span></button></form></div><div class="payment-section card" id="payment-section"
style="margin-top: var(--space-10); padding: var(--space-8); border: 1px solid var(--color-border-subtle); border-radius: var(--radius-md);"><h3 class="lang-en" style="margin-bottom: var(--space-4);"></h3><h3 class="lang-ar" style="margin-bottom: var(--space-4);">الاشتراك والدفع للحساب البنكي</h3><p class="lang-en" style="margin-bottom: var(--space-6); color: var(--color-text-muted);"></p><p class="lang-ar" style="margin-bottom: var(--space-6); color: var(--color-text-muted);">رسوم التحويل يتحملها
المشترك. بعد الدفع أرسل إثبات الدفع للصندوق؛ تُفعّل العضوية بعد التحقق.</p><div class="payment-tiers" style="display: grid; gap: var(--space-6); margin-bottom: var(--space-8);"><div class="payment-tier"
style="padding: var(--space-4); background: rgba(255,255,255,0.04); border-radius: var(--radius-sm);"><h4 class="lang-en" style="margin: 0 0 var(--space-2);"></h4><h4 class="lang-ar" style="margin: 0 0 var(--space-2);">عضو متعاون — 143 دولار سنوياً أو 29 دولار شهرياً
</h4><p class="lang-en" style="margin: 0; font-size: 0.9rem; color: var(--color-text-muted);"></p><p class="lang-ar" style="margin: 0; font-size: 0.9rem; color: var(--color-text-muted);">ميزات الموقع ورفع
الملفات فقط.</p></div><div class="payment-tier"
style="padding: var(--space-4); background: rgba(255,255,255,0.04); border-radius: var(--radius-sm);"><h4 class="lang-en" style="margin: 0 0 var(--space-2);"></h4><h4 class="lang-ar" style="margin: 0 0 var(--space-2);">عضوية فضية مميزة — 2,143 دولار</h4></div><div class="payment-tier"
style="padding: var(--space-4); background: rgba(255,255,255,0.04); border-radius: var(--radius-sm);"><h4 class="lang-en" style="margin: 0 0 var(--space-2);"></h4><h4 class="lang-ar" style="margin: 0 0 var(--space-2);">عضوية ذهبية مميزة — 3,143 دولار</h4></div><div class="payment-tier"
style="padding: var(--space-4); background: rgba(255,255,255,0.04); border-radius: var(--radius-sm);"><h4 class="lang-en" style="margin: 0 0 var(--space-2);"></h4><h4 class="lang-ar" style="margin: 0 0 var(--space-2);">عضوية بلاتينية مميزة — 4,143 دولار</h4></div></div><div class="bank-details"
style="padding: var(--space-5); background: var(--color-surface-elevated); border-radius: var(--radius-sm); margin-bottom: var(--space-4);"><h4 class="lang-en" style="margin: 0 0 var(--space-3);"></h4><h4 class="lang-ar" style="margin: 0 0 var(--space-3);">الحساب البنكي — مرجع التحويل: بريدك + نوع العضوية</h4><p class="lang-en" style="margin: 0 0 var(--space-2);"></p><p class="lang-ar" style="margin: 0 0 var(--space-2);"><strong>اسم البنك:</strong><span
id="bank-name-ar">[اسم البنك]</span></p><p class="lang-en" style="margin: 0 0 var(--space-2);"></p><p class="lang-ar" style="margin: 0 0 var(--space-2);"><strong>رقم الآيبان:</strong><span
id="bank-iban-ar">[الآيبان]</span></p><p class="lang-en" style="margin: 0 0 var(--space-2);"></p><p class="lang-ar" style="margin: 0 0 var(--space-2);"><strong>سويفت:</strong><span
id="bank-swift-ar">[سويفت]</span></p><p class="lang-en" style="margin: 0 0 var(--space-2);"></p><p class="lang-ar" style="margin: 0 0 var(--space-2);"><strong>اسم الحساب:</strong><span
id="bank-account-name-ar">[اسم الحساب]</span></p><p class="lang-en"
style="margin: 0 0 var(--space-2); font-size: 0.9rem; color: var(--color-accent-gold-soft);"></p><p class="lang-ar"
style="margin: 0 0 var(--space-2); font-size: 0.9rem; color: var(--color-accent-gold-soft);">المرجع: بريدك
الإلكتروني + "عضو متعاون" أو "فضية/ذهبية/بلاتينية مميزة"</p></div><p class="lang-en" style="font-size: 0.85rem; color: var(--color-text-muted);"></p><p class="lang-ar" style="font-size: 0.85rem; color: var(--color-text-muted);">بعد التحويل تواصل مع الصندوق مع
إثبات الدفع لتفعيل عضويتك.</p><div id="certificate-images-section" class="card"
style="margin-top: var(--space-8); padding: var(--space-6); border: 1px solid var(--color-border-subtle); border-radius: var(--radius-md); display: none;"><h4 class="lang-en" style="margin-bottom: var(--space-3);"></h4><h4 class="lang-ar" style="margin-bottom: var(--space-3);">صور شهادتك</h4><p class="lang-en" style="font-size: 0.9rem; color: var(--color-text-muted); margin-bottom: var(--space-4);"></p><p class="lang-ar" style="font-size: 0.9rem; color: var(--color-text-muted); margin-bottom: var(--space-4);">
تسجيل شخصي: أضف صورتك. شركة: أضف شعار الشركة وصورتك. حكومة: أضف علم الدولة وصورتك.</p><div
style="display:flex; gap: var(--space-3); align-items:center; justify-content:space-between; flex-wrap:wrap; margin-bottom: var(--space-4);"><div id="cert-image-diag" style="font-size:0.8rem; color: var(--color-text-muted);"></div><button type="button" class="btn btn--ghost btn-sm" id="cert-clear-images-btn"><span class="lang-en"></span><span class="lang-ar">مسح صور الشهادة المحفوظة</span></button></div><div class="cert-images-grid"
style="display: grid; gap: var(--space-4); grid-template-columns: repeat(auto-fill, minmax(180px, 1fr));"><div class="form-group cert-definition-block" style="grid-column: 1 / -1;"><label class="lang-en" style="font-size: 0.9rem;"></label><label class="lang-ar" style="font-size: 0.9rem;">تعريفك / المسمى (يظهر على الشهادة)</label><p class="cert-definition-hint lang-en">Recommended: Internationally classified global financial expert
</p><p class="cert-definition-hint lang-ar">الوصف الموصى به: خبير مالي دولي مصنف عالمياً</p><div class="form-row"
style="display: grid; grid-template-columns: 1fr 1fr; gap: var(--space-4); margin-top: var(--space-2);"><div><input type="text" id="cert-definition-en" maxlength="400"
placeholder="e.g. Internationally classified global financial expert"
style="padding: 0.6rem; border-radius: var(--radius-sm); border: 1px solid var(--color-border-subtle); background: var(--color-surface); color: var(--color-text-main); width: 100%; min-height: 2.75rem; box-sizing: border-box;" /></div><div><input type="text" id="cert-definition-ar" maxlength="400"
placeholder="مثال: خبير مالي دولي مصنف عالمياً"
style="padding: 0.6rem; border-radius: var(--radius-sm); border: 1px solid var(--color-border-subtle); background: var(--color-surface); color: var(--color-text-main); width: 100%; min-height: 2.75rem; box-sizing: border-box;" /></div></div></div><div class="cert-image-upload"><label class="lang-en" style="font-size: 0.85rem;"></label><label class="lang-ar" style="font-size: 0.85rem;">صورتك</label><div class="cert-image-preview" id="cert-photo-preview"
style="width: 100px; height: 100px; border-radius: 50%; background: var(--color-surface-elevated); margin: var(--space-2) 0; overflow: hidden; display: flex; align-items: center; justify-content: center;"><span style="color: var(--color-text-muted); font-size: 0.8rem;">—</span></div><p class="cert-image-already-msg" id="cert-photo-already-msg"
style="display:none; font-size: 0.8rem; color: var(--color-accent-gold-soft); margin: 0.25rem 0 0;"><span class="lang-en"></span><span class="lang-ar">الصورة مرفوعة سابقاً.</span></p><p class="cert-replace-hint lang-en" id="cert-photo-replace-hint"
style="display:none; font-size: 0.75rem; color: var(--color-text-muted); margin: 0.15rem 0 0;">When
replacing, you will be asked: remove the previous one and upload again?</p><p class="cert-replace-hint lang-ar" id="cert-photo-replace-hint-ar"
style="display:none; font-size: 0.75rem; color: var(--color-text-muted); margin: 0.15rem 0 0;">عند
الاستبدال سيُسألك: هل تريد حذف السابق ورفعها مرة أخرى؟</p><p class="cert-upload-status" id="cert-photo-status" role="status" aria-live="polite"
style="display:none; font-size: 0.85rem; margin: 0.35rem 0 0; padding: 0.4rem 0.5rem; border-radius: var(--radius-sm); background: var(--color-surface-elevated); color: var(--color-accent-gold-soft); min-height: 1.2rem;"></p><input type="file" id="cert-photo-input" accept="image/*" style="font-size: 0.85rem;" /><input type="file" id="cert-photo-capture" accept="image/*" capture="user" style="display:none;" /><div class="cert-img-actions"><button type="button" class="btn btn--ghost btn-sm" data-camera-kind="photo"><span
class="lang-en"></span><span class="lang-ar">التقاط</span></button><button type="button" class="btn btn--ghost btn-sm" data-upload-for="cert-photo-input"><span
class="lang-en"></span><span class="lang-ar">من الملفات</span></button><button type="button" class="btn btn--ghost btn-sm" data-adjust-kind="photo"><span
class="lang-en"></span><span class="lang-ar">وزنها داخل الإطار</span></button><button type="button" class="btn btn--ghost btn-sm" data-delete-image="photo"><span
class="lang-en"></span><span class="lang-ar">حذف الصورة</span></button></div></div><div class="cert-image-upload" id="cert-logo-wrap" style="display: none;"><label class="lang-en" style="font-size: 0.85rem;"></label><label class="lang-ar" style="font-size: 0.85rem;">شعار الشركة</label><div class="cert-image-preview" id="cert-logo-preview"
style="width: 100px; height: 100px; border-radius: var(--radius-sm); background: var(--color-surface-elevated); margin: var(--space-2) 0; overflow: hidden; display: flex; align-items: center; justify-content: center;"><span style="color: var(--color-text-muted); font-size: 0.8rem;">—</span></div><p class="cert-image-already-msg" id="cert-logo-already-msg"
style="display:none; font-size: 0.8rem; color: var(--color-accent-gold-soft); margin: 0.25rem 0 0;"><span class="lang-en"></span><span class="lang-ar">الصورة مرفوعة سابقاً.</span></p><p class="cert-upload-status" id="cert-logo-status" role="status" aria-live="polite"
style="display:none; font-size: 0.85rem; margin: 0.35rem 0 0; padding: 0.4rem 0.5rem; border-radius: var(--radius-sm); background: var(--color-surface-elevated); color: var(--color-accent-gold-soft); min-height: 1.2rem;"></p><input type="file" id="cert-logo-input" accept="image/*" style="font-size: 0.85rem;" /><input type="file" id="cert-logo-capture" accept="image/*" capture="environment" style="display:none;" /><div class="cert-img-actions"><button type="button" class="btn btn--ghost btn-sm" data-camera-kind="logo"><span
class="lang-en"></span><span class="lang-ar">التقاط</span></button><button type="button" class="btn btn--ghost btn-sm" data-upload-for="cert-logo-input"><span
class="lang-en"></span><span class="lang-ar">من الملفات</span></button><button type="button" class="btn btn--ghost btn-sm" data-adjust-kind="logo"><span class="lang-en"></span><span class="lang-ar">وزنها داخل الإطار</span></button><button type="button" class="btn btn--ghost btn-sm" data-delete-image="logo"><span
class="lang-en"></span><span class="lang-ar">حذف الصورة</span></button></div></div><div class="cert-image-upload" id="cert-flag-wrap" style="display: none;"><label class="lang-en" style="font-size: 0.85rem;"></label><label class="lang-ar" style="font-size: 0.85rem;">علم الدولة</label><div class="cert-image-preview" id="cert-flag-preview"
style="width: 100px; height: 60px; border-radius: var(--radius-sm); background: var(--color-surface-elevated); margin: var(--space-2) 0; overflow: hidden; display: flex; align-items: center; justify-content: center;"><span style="color: var(--color-text-muted); font-size: 0.8rem;">—</span></div><p class="cert-image-already-msg" id="cert-flag-already-msg"
style="display:none; font-size: 0.8rem; color: var(--color-accent-gold-soft); margin: 0.25rem 0 0;"><span class="lang-en"></span><span class="lang-ar">الصورة مرفوعة سابقاً.</span></p><p class="cert-upload-status" id="cert-flag-status" role="status" aria-live="polite"
style="display:none; font-size: 0.85rem; margin: 0.35rem 0 0; padding: 0.4rem 0.5rem; border-radius: var(--radius-sm); background: var(--color-surface-elevated); color: var(--color-accent-gold-soft); min-height: 1.2rem;"></p><input type="file" id="cert-flag-input" accept="image/*" style="font-size: 0.85rem;" /><input type="file" id="cert-flag-capture" accept="image/*" capture="environment" style="display:none;" /><div class="cert-img-actions"><button type="button" class="btn btn--ghost btn-sm" data-camera-kind="flag"><span
class="lang-en"></span><span class="lang-ar">التقاط</span></button><button type="button" class="btn btn--ghost btn-sm" data-upload-for="cert-flag-input"><span
class="lang-en"></span><span class="lang-ar">من الملفات</span></button><button type="button" class="btn btn--ghost btn-sm" data-adjust-kind="flag"><span class="lang-en"></span><span class="lang-ar">وزنها داخل الإطار</span></button><button type="button" class="btn btn--ghost btn-sm" data-delete-image="flag"><span
class="lang-en"></span><span class="lang-ar">حذف الصورة</span></button></div></div></div></div><div id="payment-admin-set-membership"
style="margin-top: var(--space-6); padding-top: var(--space-4); border-top: 1px solid var(--color-border-subtle); display: none;"><p class="lang-en" style="font-size: 0.85rem; color: var(--color-text-muted); margin-bottom: var(--space-2);"></p><p class="lang-ar" style="font-size: 0.85rem; color: var(--color-text-muted); margin-bottom: var(--space-2);">
الإدارة أو من لديه صلاحية: تعيين العضوية للمستخدم الحالي (بعد التحقق من الدفع). تاريخ البداية والنهاية
مطلوبان.</p><div class="form-row"
style="display: grid; grid-template-columns: 1fr 1fr; gap: var(--space-3); margin-bottom: var(--space-3);"><div class="form-group"><label class="lang-en" style="font-size: 0.85rem;"></label><label class="lang-ar" style="font-size: 0.85rem;">تاريخ البداية</label><input type="date" id="payment-membership-start"
style="padding: 0.5rem; border-radius: 8px; border: 1px solid var(--color-border-subtle); background: var(--color-surface); color: var(--color-text-main); width: 100%;" /></div><div class="form-group"><label class="lang-en" style="font-size: 0.85rem;"></label><label class="lang-ar" style="font-size: 0.85rem;">تاريخ النهاية</label><input type="date" id="payment-membership-end"
style="padding: 0.5rem; border-radius: 8px; border: 1px solid var(--color-border-subtle); background: var(--color-surface); color: var(--color-text-main); width: 100%;" /></div></div><select id="payment-set-membership-select"
style="padding: 0.5rem 0.75rem; border-radius: 8px; border: 1px solid var(--color-border-subtle); background: var(--color-surface); color: var(--color-text-main); margin-right: 0.5rem;"><option value="">— None —</option><option value="cooperating">Cooperating (143/29)</option><option value="shared">Shared Member / عضو مشترك</option><option value="premium_2143">Premium Silver (2,143)</option><option value="premium_3143">Premium Gold (3,143)</option><option value="premium_4143">Premium Platinum (4,143)</option></select><button type="button" class="btn btn--ghost btn-sm" id="payment-set-membership-btn"><span class="lang-en"></span><span class="lang-ar">تعيين العضوية</span></button></div></div></section>`;
}
