export function render(container, lang = "ar") {
  container.innerHTML = `<section id="translation" class="section"><h2 class="section__title" data-i18n="sectionTranslation">Translation</h2><p class="translation-quality-badge"
style="margin-bottom: var(--space-2); font-size: 1rem; font-weight: 600; color: var(--color-accent-gold-soft);"><span class="lang-en"></span><span class="lang-ar">الترجمة بأعلى معايير الجودة — احترافية واعية بالسياق وفق أفضل الممارسات المعتمدة.</span></p><p class="translation-notice" data-i18n="translationNotice"
style="margin-bottom: var(--space-4); font-size: 0.9rem; color: var(--color-text-muted);">Free services — login
required. Please log in to use translation.</p><div class="translation-google-style" id="translation-text-area"><div class="translation-box-row"><div class="translation-box-wrap"><label class="translation-box-label"><span class="lang-en"></span><span class="lang-ar">مربع
إدخال النص</span></label><label class="translation-box-label" data-i18n="translationSourceLang" style="font-size:0.85rem;"><span
class="lang-en"></span><span class="lang-ar">لغة الإدخال (حسب
بلدك)</span></label><select id="translation-text-from" class="translation-lang-select"><option value="en">English</option><option value="ar">العربية</option><option value="fr">Français</option><option value="de">Deutsch</option><option value="es">Español</option><option value="pt">Português</option><option value="it">Italiano</option><option value="ru">Русский</option><option value="zh">中文</option><option value="ja">日本語</option><option value="ko">한국어</option><option value="hi">हिन्दी</option><option value="bn">বাংলা</option><option value="tr">Türkçe</option><option value="fa">فارسی</option><option value="ur">اردو</option><option value="id">Bahasa Indonesia</option><option value="ms">Bahasa Melayu</option><option value="th">ไทย</option><option value="vi">Tiếng Việt</option><option value="pl">Polski</option><option value="nl">Nederlands</option><option value="el">Ελληνικά</option><option value="sv">Svenska</option><option value="no">Norsk</option><option value="da">Dansk</option><option value="fi">Suomi</option><option value="uk">Українська</option><option value="ro">Română</option><option value="hu">Magyar</option><option value="cs">Čeština</option><option value="sk">Slovenčina</option><option value="bg">Български</option><option value="hr">Hrvatski</option><option value="sr">Српски</option><option value="sl">Slovenščina</option><option value="he">עברית</option><option value="am">አማርኛ</option><option value="sw">Kiswahili</option><option value="ne">नेपाली</option><option value="si">සිංහල</option><option value="my">မြန်မာ</option><option value="km">ភាសាខ្មែរ</option><option value="lo">ລາວ</option><option value="ta">தமிழ்</option><option value="te">తెలుగు</option><option value="mr">मराठी</option><option value="gu">ગુજરાતી</option><option value="kn">ಕನ್ನಡ</option><option value="ml">മലയാളം</option><option value="pa">ਪੰਜਾਬੀ</option><option value="sq">Shqip</option><option value="mk">Македонски</option><option value="hy">Հայերեն</option><option value="ka">ქართული</option><option value="az">Azərbaycan</option><option value="kk">Қазақ</option><option value="uz">Oʻzbek</option><option value="mn">Монгол</option><option value="ca">Català</option><option value="eu">Euskara</option><option value="gl">Galego</option></select><textarea id="translation-text-input" maxlength="5000" class="translation-text-box"
data-i18n="translationTextPlaceholder" placeholder="Paste or type text here (max 5000 characters)"
aria-label="Text to translate"></textarea><div class="translation-input-options"><span class="translation-input-hint lang-en">Enter text by typing or voice</span><span class="translation-input-hint lang-ar">إدخال النص كتابةً أو صوتاً</span><button type="button" class="btn btn--ghost btn--sm" id="translation-voice-input-btn"
aria-label="Voice input" title="Voice input"><span class="translation-voice-icon" aria-hidden="true">🎤</span><span class="lang-en"></span><span class="lang-ar">إدخال صوتي</span></button></div><div class="translation-counters"><span id="translation-text-count">0 / 5000</span><span class="lang-en"></span><span
class="lang-ar">حرف</span></div></div><div class="translation-swap-wrap"><button type="button" class="translation-swap-btn" id="translation-swap-langs-btn"
aria-label="Swap languages" title="Swap / عكس لغة الإدخال ولغة الترجمة"><span aria-hidden="true" style="display:inline-block; font-size:1.2em;">⇄</span></button><span class="lang-en" style="font-size:0.75rem; color: var(--color-text-muted);"></span><span class="lang-ar" style="font-size:0.75rem; color: var(--color-text-muted);">عكس</span></div><div class="translation-box-wrap"><label class="translation-box-label"><span class="lang-en"></span><span
class="lang-ar">مربع الترجمة</span></label><div class="translation-lang-options-box"><label class="translation-box-label" for="translation-text-to"><span class="lang-en"></span><span class="lang-ar">خيارات لغة الترجمة</span></label><select id="translation-text-to" class="translation-lang-select"><option value="ar">العربية</option><option value="en">English</option><option value="fr">Français</option><option value="de">Deutsch</option><option value="es">Español</option><option value="pt">Português</option><option value="it">Italiano</option><option value="ru">Русский</option><option value="zh">中文</option><option value="ja">日本語</option><option value="ko">한국어</option><option value="hi">हिन्दी</option><option value="bn">বাংলা</option><option value="tr">Türkçe</option><option value="fa">فارسی</option><option value="ur">اردو</option><option value="id">Bahasa Indonesia</option><option value="ms">Bahasa Melayu</option><option value="th">ไทย</option><option value="vi">Tiếng Việt</option><option value="pl">Polski</option><option value="nl">Nederlands</option><option value="el">Ελληνικά</option><option value="sv">Svenska</option><option value="no">Norsk</option><option value="da">Dansk</option><option value="fi">Suomi</option><option value="uk">Українська</option><option value="ro">Română</option><option value="hu">Magyar</option><option value="cs">Čeština</option><option value="sk">Slovenčina</option><option value="bg">Български</option><option value="hr">Hrvatski</option><option value="sr">Српски</option><option value="sl">Slovenščina</option><option value="he">עברית</option><option value="am">አማርኛ</option><option value="sw">Kiswahili</option><option value="ne">नेपाली</option><option value="si">සිංහල</option><option value="my">မြန်မာ</option><option value="km">ភាសាខ្មែរ</option><option value="lo">ລາວ</option><option value="ta">தமிழ்</option><option value="te">తెలుగు</option><option value="mr">मराठी</option><option value="gu">ગુજરાતી</option><option value="kn">ಕನ್ನಡ</option><option value="ml">മലയാളം</option><option value="pa">ਪੰਜਾਬੀ</option><option value="sq">Shqip</option><option value="mk">Македонски</option><option value="hy">Հայերեն</option><option value="ka">ქართული</option><option value="az">Azərbaycan</option><option value="kk">Қазақ</option><option value="uz">Oʻzbek</option><option value="mn">Монгол</option><option value="ca">Català</option><option value="eu">Euskara</option><option value="gl">Galego</option></select></div><div class="translation-result translation-text-box" id="translation-text-result" aria-live="polite"
role="region" aria-label="Translation result"></div><div class="translation-result-options"><span class="translation-result-hint lang-en">Written translation — listen in clear voice</span><span class="translation-result-hint lang-ar">الترجمة مكتوبة — سماع بصوت واضح</span><button type="button" class="btn btn--ghost btn--sm" id="translation-listen-btn"
aria-label="Listen to translation in clear voice"
title="Listen in clear voice / سماع الترجمة بصوت واضح"><span class="translation-listen-icon" aria-hidden="true">🔊</span><span class="lang-en"></span><span class="lang-ar">سماع الترجمة بصوت واضح</span></button></div></div></div><div class="translation-actions"><button type="button" class="btn btn--primary" id="translation-text-btn"><span class="lang-en"></span><span class="lang-ar">ترجمة</span></button></div></div></section>`;
}
