export function render(container, lang = "ar") {
  container.innerHTML = `<section id="urgent-consultation-online" class="section urgent-online-section"><h2 class="section__title"><span class="lang-en"></span><span class="lang-ar">استشارة
عاجلة — أونلاين</span></h2><p class="lang-en" style="margin-bottom: var(--space-8); max-width: 720px;"></p><p class="lang-ar" style="margin-bottom: var(--space-8); max-width: 720px;">منصة مخصصة للصندوق الدولي للاستثمار.
استشارة أونلاين احترافية وبجودة عالية مع اتصال مرئي ومسموع آمن، وإضافة أطراف، وشات بوت مشفّر، وربط الدفع (رقم
الحساب) عند الحاجة.</p><div class="grid-3 urgent-online-features"><div class="card urgent-feature-card"><div class="urgent-feature-icon" aria-hidden="true">📹</div><h3 class="lang-en"></h3><h3 class="lang-ar">اتصال مرئي ومسموع</h3><p class="lang-en"></p><p class="lang-ar">اجتماع أونلاين بجودة عالية واحترافية تحت إشراف الصندوق. إمكانية إضافة أطراف متعددة (مرئي
ومسموع). بيئة آمنة ومحمية من الطرف إلى الطرف.</p><button type="button" class="btn btn--primary urgent-request-video-btn" id="urgent-request-video-btn"><span class="lang-en"></span><span class="lang-ar">طلب اتصال مرئي/مسموع</span></button></div><div class="card urgent-feature-card"><div class="urgent-feature-icon" aria-hidden="true">🔒</div><h3 class="lang-en"></h3><h3 class="lang-ar">شات بوت آمن</h3><p class="lang-en"></p><p class="lang-ar">دردشة مشفّرة مع فريق الصندوق. محمية من التصنت أو الاعتراض أو الوصول غير المصرح. لا تجسس ولا
اختراق.</p></div><div class="card urgent-feature-card"><div class="urgent-feature-icon" aria-hidden="true">💳</div><h3 class="lang-en"></h3><h3 class="lang-ar">ربط الدفع</h3><p class="lang-en"></p><p class="lang-ar">إمكانية ربط طريقة الدفع (رقم الحساب البنكي) لتسوية رسوم الاستشارة بشكل آمن ومتوافق. معالجة
بسرية تامة.</p></div></div><div class="payment-method-box"><p class="payment-secure-badge lang-en">Secure &amp; regulated</p><p class="payment-secure-badge lang-ar">آمنة ونظامية</p><h3 class="lang-en"></h3><h3 class="lang-ar">طريقة الدفع — الحساب البنكي الرسمي للصندوق</h3><p class="lang-en" style="margin-bottom: var(--space-4); font-size: 0.9rem;"></p><p class="lang-ar" style="margin-bottom: var(--space-4); font-size: 0.9rem;">لرسوم الاستشارة والمدفوعات
المرتبطة. حساب جاري — جي بي مورغان تشيس. حساب رسمي فقط؛ التحويلات تتم وفقاً للأنظمة المعمول بها.</p><dl class="payment-method-dl"><dt class="lang-en"></dt><dt class="lang-ar">اسم الحساب</dt><dd id="payment-account-name">—</dd><dt class="lang-en"></dt><dt class="lang-ar">رقم الحساب</dt><dd id="payment-account-number">—</dd></dl><p class="payment-regulatory lang-en">Bank transfers only. No third-party payment processors. Data handled in
strict confidence.</p><p class="payment-regulatory lang-ar">تحويلات بنكية فقط. لا وسطاء دفع. معالجة البيانات بسرية تامة.</p><div class="payment-remember-wrap"><label class="payment-remember-label"><input type="checkbox" id="payment-remember-urgent" /><span
class="lang-en"></span><span class="lang-ar">تذكر طريقة الدفع
للدفعات القادمة</span></label><p class="payment-saved-hint lang-en" id="payment-saved-hint-urgent" hidden>Your saved payment method: Bank
transfer (official account).</p><p class="payment-saved-hint lang-ar" id="payment-saved-hint-urgent-ar" hidden>طريقة الدفع المحفوظة: تحويل
بنكي (الحساب الرسمي).</p></div></div><div class="urgent-online-form-wrap" id="urgent-request-form"><h3 class="lang-en"></h3><h3 class="lang-ar">طلب الدخول</h3><form id="form-urgent-online" class="urgent-online-form"><div class="form-row"><div class="form-group"><label for="urgent-name"><span class="lang-en"></span><span class="lang-ar">الاسم
الكامل</span></label><input type="text" id="urgent-name" name="name" required maxlength="120" autocomplete="name" /></div><div class="form-group"><label for="urgent-email"><span class="lang-en"></span><span class="lang-ar">البريد
الإلكتروني</span></label><input type="email" id="urgent-email" name="email" required maxlength="254" autocomplete="email" /></div></div><div class="form-group"><label><span class="lang-en"></span><span class="lang-ar">القناة المفضلة</span></label><select id="urgent-channel" name="channel"><option value="video">Video / audio call — اتصال مرئي/مسموع</option><option value="chat">Secure chatbot — شات بوت آمن</option><option value="both">Both — كلاهما</option></select></div><div class="form-group"><label for="urgent-account"><span class="lang-en"></span><span class="lang-ar">رقم الحساب البنكي (اختياري — لربط الدفع)</span></label><input type="text" id="urgent-account" name="account" maxlength="80" placeholder="IBAN or account number"
autocomplete="off" /></div><div class="form-group"><label for="urgent-notes"><span class="lang-en"></span><span class="lang-ar">ملاحظة
مختصرة (اختياري)</span></label><textarea id="urgent-notes" name="notes" rows="3" maxlength="500" placeholder=""></textarea></div><div class="kyc-block"><h4 class="kyc-block__title lang-en">Know Your Customer (KYC)</h4><h4 class="kyc-block__title lang-ar">اعرف عميلك</h4><p class="kyc-block__intro lang-en">Required for compliance. Please provide identification and address
details.</p><p class="kyc-block__intro lang-ar">مطلوب للامتثال. يرجى تقديم بيانات الهوية والعنوان.</p><div class="form-row"><div class="form-group"><label for="urgent-kyc-dob"><span class="lang-en"></span><span class="lang-ar">تاريخ
الميلاد</span></label><input type="date" id="urgent-kyc-dob" name="kyc_dob" required /></div><div class="form-group"><label for="urgent-kyc-nationality"><span class="lang-en"></span><span
class="lang-ar">الجنسية</span></label><select id="urgent-kyc-nationality" name="kyc_nationality" required><option value="">— Select / اختر —</option><option value="SA">Saudi Arabia</option><option value="AE">United Arab Emirates</option><option value="EG">Egypt</option><option value="JO">Jordan</option><option value="FR">France</option><option value="US">United States</option><option value="GB">United Kingdom</option><option value="OTHER">Other</option></select></div></div><div class="form-row"><div class="form-group"><label for="urgent-kyc-id-type"><span class="lang-en"></span><span class="lang-ar">نوع
الوثيقة</span></label><select id="urgent-kyc-id-type" name="kyc_id_type" required><option value="">— Select / اختر —</option><option value="passport">Passport / جواز سفر</option><option value="national_id">National ID / هوية وطنية</option><option value="other">Other / أخرى</option></select></div><div class="form-group"><label for="urgent-kyc-id-number"><span class="lang-en"></span><span
class="lang-ar">رقم الوثيقة</span></label><input type="text" id="urgent-kyc-id-number" name="kyc_id_number" required maxlength="80" /></div></div><div class="form-group"><label for="urgent-kyc-address"><span class="lang-en"></span><span
class="lang-ar">العنوان</span></label><input type="text" id="urgent-kyc-address" name="kyc_address" required maxlength="200" /></div><div class="form-row"><div class="form-group"><label for="urgent-kyc-city"><span class="lang-en"></span><span
class="lang-ar">المدينة</span></label><input type="text" id="urgent-kyc-city" name="kyc_city" required maxlength="100" /></div><div class="form-group"><label for="urgent-kyc-postal"><span class="lang-en"></span><span
class="lang-ar">الرمز البريدي (اختياري)</span></label><input type="text" id="urgent-kyc-postal" name="kyc_postal" maxlength="20" /></div></div><div class="form-group"><label for="urgent-kyc-country"><span class="lang-en"></span><span
class="lang-ar">دولة الإقامة</span></label><select id="urgent-kyc-country" name="kyc_country" required><option value="">— Select / اختر —</option></select></div><div class="form-group"><label for="urgent-kyc-request"><span class="lang-en"></span><span
class="lang-ar">شرح تكلم عن طلبك</span></label><textarea id="urgent-kyc-request" name="kyc_request" rows="3" maxlength="2000" placeholder=""></textarea></div></div><button type="submit" class="btn btn--primary" id="urgent-online-submit"><span class="lang-en"></span><span class="lang-ar">إرسال الطلب</span></button><p class="urgent-online-form-note lang-en">The Fund will contact you to arrange the secure session. Data is
handled in confidence.</p><p class="urgent-online-form-note lang-ar">سيتواصل الصندوق معك لترتيب الجلسة الآمنة. تتم معالجة البيانات
بسرية.</p></form><div id="urgent-online-success" class="urgent-online-success" hidden aria-live="polite"></div></div></section>`;
}
