export function render(container, lang = "ar") {
  container.innerHTML = `<section id="verification-tools" class="section section--collapsible"><div class="section-collapse-header"><h2 class="section__title"><span class="lang-en"></span><span
class="lang-ar">أدوات التحقق والامتثال</span></h2><button type="button" class="btn btn--ghost btn--sm section-collapse-toggle" id="verification-toggle"
aria-expanded="false" aria-controls="verification-content"><span class="lang-en"></span><span class="lang-ar">إظهار</span></button></div><div id="verification-content" class="section-collapse-content" hidden><p class="lang-en" style="margin-bottom: var(--space-8);"></p><p class="lang-ar" style="margin-bottom: var(--space-8);">نستخدم أدوات مدمجة للتحقق من الهوية وفحص موقع الجلسة
واستخدام البروكسي والربط مع سجلاتنا. يمكن إرسال النتائج للفريق (البريد / واتساب) للمتابعة.</p><div class="grid-3"><div class="card verification-tool-card"><h3 class="lang-en"></h3><h3 class="lang-ar">التحقق من هوية العميل (KYC)</h3><p class="lang-en"></p><p class="lang-ar">يتم التحقق من هوية الشخص أو بيانات الشركة آلياً فور رفع الوثائق. أدوات مدمجة تقوم بالتحقق
بدلاً من البحث اليدوي المجهد.</p><p class="verification-note lang-en">When you submit documents (membership, financing, investor
registration), KYC verification runs once the service is connected.</p><p class="verification-note lang-ar">عند إرسال المستندات (العضوية، التمويل، تسجيل المستثمر)، يتم تشغيل
التحقق KYC عند ربط الخدمة.</p></div><div class="card verification-tool-card"><h3 class="lang-en"></h3><h3 class="lang-ar">فحص IP والبروكسي</h3><p class="lang-en"></p><p class="lang-ar">التحقق من موقع الزائر الجغرافي وما إذا كان يستخدم بروكسي أو VPN لإخفاء الهوية، مما قد
يثير الشبهات.</p><div id="ip-check-result" class="ip-check-box" aria-live="polite"><span class="lang-en"></span><span class="lang-ar">جاري فحص الجلسة…</span></div></div><div class="card verification-tool-card"><h3 class="lang-en"></h3><h3 class="lang-ar">الربط مع البيانات السابقة</h3><p class="lang-en"></p><p class="lang-ar">تحقق مما إذا كان العميل قد تواصل معنا سابقاً (عبر البريد أو الجوال). البحث التلقائي وملخص
السلوك يُرسل إلى الفريق على <a href="mailto:talalkenani@gmail.com">talalkenani@gmail.com</a> وواتساب <a
href="https://wa.me/966567566616">+966 56 756 6616</a> للمتابعة فوراً.</p><p class="verification-note lang-en">Cross-check and send to email/WhatsApp run when the backend is
connected.</p><p class="verification-note lang-ar">الربط والإرسال إلى البريد وواتساب يعملان عند ربط الخادم.</p></div></div><div class="send-summary-wrap"><h4 class="lang-en"></h4><h4 class="lang-ar">إرسال ملخص الجلسة للفريق</h4><p class="lang-en" style="margin-bottom: var(--space-4); font-size: 0.9rem;"></p><p class="lang-ar" style="margin-bottom: var(--space-4); font-size: 0.9rem;">جمع الجلسة الحالية (الموقع، IP)
والأقسام المزارة وملاحظة اختيارية. عند ربط الخادم سيُرسل إلى talalkenani@gmail.com وواتساب +966 56 756 6616.
</p><div class="form-group"><label for="summary-note"><span class="lang-en"></span><span class="lang-ar">ملاحظة
(اختياري)</span></label><input type="text" id="summary-note" maxlength="300" placeholder=""
style="width:100%; max-width:400px; padding:0.6rem 0.8rem; border-radius:8px; border:1px solid var(--color-border-subtle); background:rgba(255,255,255,0.04); color:var(--color-text-main);" /></div><button type="button" class="btn btn--primary" id="send-summary-btn"><span class="lang-en"></span><span class="lang-ar">تحضير وإرسال الملخص للفريق</span></button><div id="summary-preview" class="summary-preview" hidden aria-live="polite"></div></div></div></section>`;
}
